### ISSUE TITLE
[FEATURE]: Implement support for "CIECAM16" colour appearance model.

### ISSUE THREAD

**Issue by ems1111** [colour-science/colour#1013]
CAM16 was approved by the CIE a few months ago, and needs to be changed to CIECAM16. There are slight changes to the forward and inverse equations that need updated, specifically in steps 0 and 3 of the forward transformation.

**Comment by KelSolaar** [comment]
Hi @ems1111,

Thank you, it is on our radar! It is a bit more complicated than that and will require a new separate model as we should not touch CAM16.

Cheers,

Thomas
