### ISSUE TITLE
[BUG]: sd_to_XYZ with k=683 is 100x larger than expected

### ISSUE THREAD

**Issue by tjdcs** [colour-science/colour#1018]
### Description

The constant 683 is often used to convert from a SPD in measurements of radiometric watts to a candela referenced value.
In the equation for computing tristimulus values, if the dλ is 1nm, then the provided example code should result in a value close to Y = 683. However, sd_to_XYZ currently returns 68300. 

Furthermore, for those of us who work in absolute colorimetry (FTW 😁) the exact value of the candela constant is calculated according to the procedure below. It would be nice to include some code for this constant, but I'll settle for just making the 683 assumption correct.

> The candela [...] is defined by taking the fixed numerical value of the luminous efficacy of monochromatic radiation of frequency 540 × 1012 Hz, Kcd, to be 683 when expressed in the unit lm W–1, which is equal to cd sr W–1, or cd sr kg–1 m–2 s3, where the kilogram, metre and second are defined in terms of [h](https://en.wikipedia.org/wiki/Planck_constant), [c](https://en.wikipedia.org/wiki/Speed_of_light_in_vacuum) and [ΔνCs](https://en.wikipedia.org/wiki/Unperturbed_ground_state_hyperfine_transition_frequency_of_the_caesium_133_atom).

### Code for Reproduction

```python
import colour
from colour import SpectralDistribution, SpectralShape, sd_multi_leds, sd_to_XYZ
from colour.plotting import plot_single_sd
import numpy as np

shape = SpectralShape(380,780,1)
values = np.zeros(401)
values[780-555]
spd = SpectralDistribution(np.zeros((401)), domain=shape)

v = spd.values
v[555-380] = 1 #SPD is 1W at 555nm, 0 everywhere else. 
spd.values = v

xyz = sd_to_XYZ(spd, k=683, method="integration")

print(xyz)
```

**Comment by KelSolaar** [comment]
Hey @tjdcs,

This is an interesting one, the output is always a percentage by default so we would expect a division by 100, however it certainly does not make a lot of sense for absolute values. Maybe if `k` is passed we divide by 100 automatically?

Cheers,

Thomas

**Comment by tjdcs** [comment]
The behavior I care about is getting absolute colorimetry with an api that makes `k=683` so dividing by 100 as an implementation detail works for me. I think the more "correct" solution is a design issue related to attaching `units` to `SpectralDistribution` or perhaps subclasses of `SpectralDistribution`. But the design question is longer term and possibly a https://github.com/colour-science/colour/labels/Feature 

I can submit a PR for the bandaid in a few minutes.

**Comment by KelSolaar** [comment]
Looking at this one now @tjdcs, btw, your original snippet could be done as follows:

```python
import colour

sd = colour.sd_zeros()

sd[555] = 1

print(sd)

print(colour.sd_to_XYZ(sd, method="Integration", k=683))
print(colour.sd_to_XYZ(sd, k=683))
```

**Comment by KelSolaar** [comment]
Merged @tjdcs!
