### ISSUE TITLE
[BUG]: TM-30-18 Report shows incorrect CRI R9 value

### ISSUE THREAD

**Issue by kohler-t** [colour-science/colour#1040]
### Description

There is an off-by-one error/typo in [colour/plotting/tm3018/report.py line 525](https://github.com/colour-science/colour/blob/18ba5590d27a20cfc72819e9f82d633e7003121f/colour/plotting/tm3018/report.py#L525) that leads to the R8 value being shown as R9 in the TM-30-18 Report:
<pre>
f"$R_9$` _{float(CRI_spec.Q_as[<b><i>8</i></b>].Q_a):.0f}"
</pre>

Test colour samples indexes to names mapping from [colour/quality/datasets/tcs.py lines 40-56 ](https://github.com/colour-science/colour/blob/18ba5590d27a20cfc72819e9f82d633e7003121f/colour/quality/datasets/tcs.py#L40):
```
INDEXES_TO_NAMES_TCS: Dict = {
    […]
    9: "TCS09",
    […] 
}
```

Fix for actually showing the value of R9:
<pre>
f"$R_9$` {float(CRI_spec.Q_as[<b><i>9</i></b>].Q_a):.0f}"
</pre>

Hopefully, reporting this issue here is the correct way. A pull request for changing a single digit seems excessive.

**Comment by KelSolaar** [comment]
Hi @kohler-t,

Did you actually see an issue in the actual values or is this your assumption by reading the code?

The mapping you reference is kind of error inducing and given that we do not really use it for anything, I'm wondering if we should not use it. With that in mind, Python is 0-based indexed so the nth element is at index n-1. So the 9th element is at index 8 which should be correct in the code.

Cheers,

Thomas

**Comment by kohler-t** [comment]
Hello Thomas,
I did see an issue in the actual values, but it took me some time to notice it after generating some TM-30-18 reports for various LED spectra. The CRI R8 and R9 results are often relatively similar (since TCS08 is "light reddish purple" and TCS09 is "strong red"), but sometimes they differ significantly. As an example, for illuminant FL1:
https://github.com/colour-science/colour/blob/18ba5590d27a20cfc72819e9f82d633e7003121f/colour/quality/tests/test_cri.py#L172
https://github.com/colour-science/colour/blob/18ba5590d27a20cfc72819e9f82d633e7003121f/colour/quality/tests/test_cri.py#L175

But when creating a TM-30-18 report (using colour 0.4.1):
```
import colour
from colour import SDS_ILLUMINANTS
sd = SDS_ILLUMINANTS['FL1']
colour.plotting.plot_single_sd_colour_rendition_report(sd)
```
it shows CRI R9 as 53 (I'm not sure if it's possible to embed images here), while [luxpy](https://github.com/ksmet1977/luxpy), [argyll](https://www.argyllcms.com/) and [Osram color calculator](https://www.osram.us/cb/tools-and-resources/applications/led-colorcalculator/index.jsp) all consistently show CRI R9 as -47 for illuminant FL1.

At first, I suspected that there could be an error in the TCS09 Test Colour Samples Spectral Distribution from [colour/quality/datasets/tcs.py](https://github.com/colour-science/colour/blob/18ba5590d27a20cfc72819e9f82d633e7003121f/colour/quality/datasets/tcs.py), but after checking it against the references it turned out to be perfectly fine. After that, I realized that what is shown as R9 in the report is actually consistent with the value of R8. Then i started looking up the code for creating a TM-30-18 report and found what i posted in the inital issue.

Initially i was unable to discover what was going on here because my brain subliminally mapped the index 8 to element 9, and i was looking for R9, therefore it seemed to be correct… I should have explained comprehensively what I was doing in my initial post, and not just post my solution.

**Comment by KelSolaar** [comment]
Thanks a lot, that was a nasty one!

So the short story is that `CRI_spec.Q_as` is a `Dict` and not an `Array` / `List`. What made it confusing is that the keys are integers.
