### ISSUE TITLE
[BUG]: "Hellwig, Stolitzka and Fairchild (2022)" "Helmholtz–Kohlrausch" effect extension implementation is incorrect.

### ISSUE THREAD

**Issue by ilia3101** [colour-science/colour#1047]
I'm not sure if CAM16/CIECAM02 'hellwig' method implementation is correct. The paper says to calculate chroma using the Hellwig correction, for both CAM16 and CIECAM02:

![Screenshot 2022-10-02 at 21 16 05](https://user-images.githubusercontent.com/23642861/193474471-6111015e-148e-4957-82f9-c90cb7d884b6.png)
![Screenshot 2022-10-02 at 21 14 45](https://user-images.githubusercontent.com/23642861/193474478-fc3300cc-ef64-48a9-adff-385a60427ebf.png)

**Hellwig L, Stolitzka D,Fairchild MD. Extending CIECAM02 and CAM16for the Helmholtz–Kohlrausch effect.Color ResAppl. 2022;47(5):1096-1104. doi:10.1002/col.22793**

but both '02 and '16 implementations of 'hellwig 2022' method use the same old C value:
![Untitled](https://user-images.githubusercontent.com/23642861/193474533-b5d2936c-f3d6-44e4-99c0-6c523252aaa1.jpg)

**Comment by KelSolaar** [comment]
Good catch, this quite a majorly annoying one...

**Comment by ilia3101** [comment]
I also find it surprising that there is no eccentricity coefficients given specific to CAM02, like there was for the hue dependency. They seem so highly fitted...

![Screenshot 2022-10-02 at 23 44 58](https://user-images.githubusercontent.com/23642861/193479627-d0cbf7e2-43a3-48ae-b8a1-7c2ac5ab5c39.png)

(Hellwig L,Fairchild MD. Brightness, lightness, colorfulness,and chroma in CIECAM02 and CAM16.Color ResAppl. 2022;47(5):1083-1095. doi:10.1002/col.22792)

**Comment by KelSolaar** [comment]
So looking at it, this is really Luke's new updated CAM. I think I will drop entirely the CAM16 and CIECAM02 extensions because at this point I will need to gut them out entirely.

**Comment by ilia3101** [comment]
Yeah basically a whole CAM with '16 and '02 variations.

I see two ways forward preserving the '02 variation:
1. Add a parameter similar to `method`, with `cam16` and `ciecam02` as options, to `XYZ_to_Hellwig2022`/`Hellwig2022_to_XYZ`
2. Keep the method parameter in CIECAM02 and CAM16, and implement full Hellwig through there. Which would make `XYZ_to_Hellwig2022`/`Hellwig2022_to_XYZ` redundant.

1 is probably better for clarity.

**Comment by KelSolaar** [comment]
1. would probably be preferred but given the recent adoption of CIECAM16, I'm not sure if it is really worth the effort at this point.

**Comment by ilia3101** [comment]
Understandable

**Comment by tjdcs** [comment]
Good plan. I've been calling it H_CAM for some time. Short for Hellwig

**Comment by KelSolaar** [comment]
Closing that one as we partially reverted the code!
