### ISSUE TITLE
[FEATURE]: Support for cPython 3.11

### ISSUE THREAD

**Issue by JayPalm** [colour-science/colour#1065]
### Description

Request for support of cPython 3.11 in `colour`. I don't know of any breaking changes introduced from Python 3.10 to Python 3.11, but I guess you never know till the tests have been run.

**Comment by KelSolaar** [comment]
Hi @JayPalm,

Thanks this is planned! We are trying to release a new version of Colour in the coming weeks. The tests should all pass but I suspect that there are minor type checking issues.

Cheers,

Thomas

**Comment by KelSolaar** [comment]
Implemented with #1066.
