### ISSUE TITLE
[BUG]: API reference seems to be pointing to the wrong release

### ISSUE THREAD

**Issue by altert** [colour-science/colour#1132]
### Description

LInk to API reference leads to https://colour.readthedocs.io/en/latest/reference.html
which is actually docs for current development state
(e.g. https://colour.readthedocs.io/en/latest/generated/colour.RGB_to_XYZ.html)
while docs for master  leads to https://colour.readthedocs.io/en/master/generated/colour.RGB_to_XYZ.html
which seems to be actual latest release. 
Shouldn't it be the opposite?

**Comment by KelSolaar** [comment]
Hi @altert,

Thank you! It might look odd but this is correct from our standpoint:

- The *latest* code is always that of the `develop` branch: https://github.com/colour-science/colour/tree/develop, consequently, the *latest* documentation points to it.
- The *release* code is that of the of the `master` branch: https://github.com/colour-science/colour/tree/master, it is often months late compared to `develop`. We typically have 2 or 3 releases per-year.

![image](https://user-images.githubusercontent.com/99779/230678614-019f4d7d-c5f0-4113-9350-f29eb7f620e1.png)

Worth noting that we follow the [Git Flow Branching Model](https://nvie.com/posts/a-successful-git-branching-model/):

![](https://nvie.com/img/git-model@2x.png)

**Comment by altert** [comment]
ok, thanks. 
It can cause a bit of confusion though, as it did for me, because if you add latest package via pip and try some of the examples from the API reference, they won't work. Maybe the link to API reference from the github page should go to the master docs then?
Oh, and master API reference is not for 0.4.2 but for 0.4.1  (has no mention of Hellwig2022 for example) and link to 0.4.2 reference from the site goes nowhere: https://colour.readthedocs.io/en/v0.4.2/reference.html

**Comment by KelSolaar** [comment]
Hi,

Thanks, good point I didn't think about! Whilst investigating the 0.4.2 docs being AWOL, I noticed an issue in the way we build related to Github Actions artifacts retention. I will have to put some more thoughts into that and possibly store them elsewhere.

Cheers,

Thomas

**Comment by KelSolaar** [comment]
The API Reference page was updated on the **Website** and in the `README.rst` file.
