### ISSUE TITLE
[BUG]: Wrong behavior of colour.convert method

### ISSUE THREAD

**Issue by teja275** [colour-science/colour#1136]
### Description

I am trying to use the colour.convert method to convert Hexadecimal notation to RGB and it is giving wrong output
Ex: For the HEX code #644E42 the RGB values are [100, 78, 66] however, the above method gives [ 0.12743768  0.07618538  0.05448028] as output

Similarly, when I try to convert from Hexadecimal to CIE Lab notation, it gives wrong outputs 
Ex: For the HEX code #644E42, the above method gives [ 0.35105926  0.07303366  0.1063123 ] as output, however, Lab co-ordinates should be in the range of 0 to 100

### Code for Reproduction

```python
# HEX to RGB
convert(hex_color, "Hexadecimal", "RGB")

# HEX to CIE Lab
convert(hex_color, "Hexadecimal", "CIE Lab")
```

### Environment Information

```shell
===============================================================================
*                                                                             *
*   Interpreter :                                                             *
*       python : 3.9.9 (main, Nov 21 2021, 03:23:44)                          *
*                [Clang 13.0.0 (clang-1300.0.29.3)]                           *
*                                                                             *
*   colour-science.org :                                                      *
*       colour : 0.4.2                                                        *
*                                                                             *
*   Runtime :                                                                 *
*       imageio : 2.26.1                                                      *
*       matplotlib : 3.5.2                                                    *
*       networkx : 2.6.3                                                      *
*       numpy : 1.21.6                                                        *
*       pandas : 1.3.3                                                        *
*       scipy : 1.10.1                                                        *
*       tqdm : 4.64.0                                                         *
*                                                                             *
===============================================================================
```

**Comment by KelSolaar** [comment]
Hi @teja275,

The output of both of your calls are correct. In the first case, "RGB" is representing linear / "scene-referred" values. If you need "gamma" encoded ones, use `Output-Referred RGB` instead of `RGB`. Note that the values are "soft" normalised to [0, 1] which brings me to the second point of normalisation which is written in the docs: The `colour.convert` definition "soft" normalises all the input/output values in domain-range [0, 1]. For the CIE Lab case, you only need to multiply by 100.

Cheers,

Thomas

**Comment by teja275** [comment]
Hi @KelSolaar - This was helpful. Thank you!
