### ISSUE TITLE
[BUG]: Various definitions described by the `colour.describe_conversion_path` definition seem to be missing.

### ISSUE THREAD

**Issue by blue-j** [colour-science/colour#1155]
### Discussed in https://github.com/colour-science/colour/discussions/1154

<div type='discussions-op-text'>

<sup>Originally posted by **blue-j** May 20, 2023</sup>
**CAM16_to_JMh_CAM16**
**CIECAM16_to_JMh_CIECAM16**
**CIECAM02_to_JMh_CIECAM02**
**Hellwig2022_to_JMh_Hellwig2022**

do not appear to exist in the library, but are referenced in the Automatic Conversion Graph and `colour.describe_conversion_path`

Am I missing something?

- J</div>

**Comment by KelSolaar** [comment]
Hi @blue-j,

If they are described it means that there is in a graph, an object behind them. The question then becomes where are they defined? The easiest is to look at the code for the conversion graph itself: https://github.com/colour-science/colour/blob/develop/colour/graph/conversion.py. We typically list all the public module objects in the `__all__` attribute at the top after the imports:

```python
__all__ = [
    "Conversion_Specification",
    "CIECAM02_to_JMh_CIECAM02",
    "JMh_CIECAM02_to_CIECAM02",
    "CAM16_to_JMh_CAM16",
    "JMh_CAM16_to_CAM16",
    "Hellwig2022_to_JMh_Hellwig2022",
    "JMh_Hellwig2022_to_Hellwig2022",
    "XYZ_to_luminance",
    "RGB_luminance_to_RGB",
    "CCT_D_uv_to_mired",
    "mired_to_CCT_D_uv",
    "CONVERSION_SPECIFICATIONS_DATA",
    "CONVERSION_GRAPH_NODE_LABELS",
    "CONVERSION_SPECIFICATIONS",
    "CONVERSION_GRAPH",
    "describe_conversion_path",
    "convert",
]
```

There you can see them all! It could be argued that they could be defined in their respective modules but they are really one liner convenience wrappers so for now we keep them here.

**Comment by KelSolaar** [comment]
You would access the definition as follows: `colour.graph.conversion.CAM16_to_JMh_CAM16` and only need to pass the return value from `colour.XYZ_to_CAM16` to it.
