### ISSUE TITLE
[BUG]: Extra Space Typos in Light Sources Array

### ISSUE THREAD

**Issue by blue-j** [colour-science/colour#1162]
### Description

I hesitate to call this a bug! But these entries seem to have an extra space introduced before "/" ?

'F32T8/TL865 /PLUS (Triphosphor)'
'F34T12/LW/RS /EW'
'F34T12WW/RS /EW (Warm White FL)'
'MHC100/U/MP /3K'
'MHC100/U/MP /4K'

### Environment Information

```shell
https://colour.readthedocs.io/en/v0.4.2/generated/colour.SDS_LIGHT_SOURCES.html
```

**Comment by KelSolaar** [comment]
Hi @blue-j,

For reference, those are the names as they were in Yoshi Ohno spreadsheet. It does make sense to amend them for consistency.

Cheers,

Thomas
