### ISSUE TITLE
[DOCUMENTATION]: Quality metric mismatch

### ISSUE THREAD

**Issue by blue-j** [colour-science/colour#1169]
### Documentation Link

https://github.com/colour-science/colour#light-quality-colour-quality

### Description

Labels are switched around in colour quality section overview:

![Screenshot 2023-06-16 at 1 05 02 PM](https://github.com/colour-science/colour/assets/3990142/57a6939c-f9e6-4413-8f90-09df3a3584f2)

### Suggested Improvement

Switch em

**Comment by KelSolaar** [comment]
Thanks!
