### ISSUE TITLE
[FEATURE]: Implement support for "Canon" v1.2 encodings.

### ISSUE THREAD

**Issue by opanyaki** [colour-science/colour#1176]
### Description

The values in "color.models.rgb.transfer_functions.canon" are different from the Input Transform CTL values that can be downloaded from the Canon website.

#### Canon Log

https://github.com/colour-science/colour/blob/6b8b5d4e010fedd6ea5cbd449c9f5718e6e714fa/colour/models/rgb/transfer_functions/canon.py#L195-L199

"Version 2.0",

```c
/* CanonLog to Linear */
float CanonLog_to_linear (
	float clog
)
{
	float out;

	if(clog < 0.12512248)
		out = -( pow( 10, ( 0.12512248 - clog ) / 0.45310179 ) - 1 ) / 10.1596;
	else
		out = ( pow( 10, ( clog - 0.12512248 ) / 0.45310179 ) - 1 ) / 10.1596;

	return out;
}
```

"Version 1.0",

```c
float CanonLog_to_linear (
	float clog_ire
)
{
	float lin;

	lin = (pow(10,(clog_ire-0.0730597)/0.529136)-1)/10.1596;

	return Clip(lin);

}
```

#### Canon Log 2

https://github.com/colour-science/colour/blob/6b8b5d4e010fedd6ea5cbd449c9f5718e6e714fa/colour/models/rgb/transfer_functions/canon.py#L334-L338

```c
/* CanonLog2 to Linear */
float CanonLog2_to_linear (
	float clog2
)
{
	float out;

	if(clog2 < 0.092864125)
		out = -( pow( 10, ( 0.092864125 - clog2 ) / 0.24136077 ) - 1 ) / 87.099375;
	else
		out = ( pow( 10, ( clog2 - 0.092864125 ) / 0.24136077 ) - 1 ) / 87.099375;

	return out;
}
```

#### Canon Log 3

https://github.com/colour-science/colour/blob/6b8b5d4e010fedd6ea5cbd449c9f5718e6e714fa/colour/models/rgb/transfer_functions/canon.py#L496-L503

```c
/* CanonLog3 to Linear */
float CanonLog3_to_linear (
	float clog3
)
{
	float out;

	if(clog3 < 0.097465473)
		out = -( pow( 10, ( 0.12783901 - clog3 ) / 0.36726845 ) - 1 ) / 14.98325;
	else if(clog3 <= 0.15277891)
		out = ( clog3 - 0.12512219 ) / 1.9754798;
	else
		out = ( pow( 10, ( clog3 - 0.12240537 ) / 0.36726845 ) - 1 ) / 14.98325;

	return out;
}
```

### References

https://github.com/colour-science/colour/blob/6b8b5d4e010fedd6ea5cbd449c9f5718e6e714fa/colour/models/rgb/transfer_functions/canon.py#L20-L29

#### JP

The Japanese website has links to the download page.

- [EOS C300 Mark II用 Input Transform 202007版](https://cweb.canon.jp/drv-upd/dvc/eosc300mk2-idt202007.html)
- [EOS C300 Mark III用 Input Transform 202007版](https://cweb.canon.jp/drv-upd/dvc/eosc300mk3-idt202007.html)
- [Canon Input Transform ver. 2.0 (EOS R5C)](https://cweb.canon.jp/drv-upd/dc/idt20.html)

#### US

- https://www.usa.canon.com/support/p/eos-c300-mark-ii
- https://www.usa.canon.com/support/p/eos-c300-mark-iii

**Comment by KelSolaar** [comment]
It would seem like that they have released some new versions of the transforms without notice. Looks terrible at first glance and will need some detective work. @nick-shaw : Any thoughts on that?

**Comment by opanyaki** [comment]
ampas/aces-dev#132

Canon's IDT in the aces-dev repository was already updated.

**Comment by KelSolaar** [comment]
Yes, I saw that yesterday evening, I can’t believe Canon changed them without renaming the encodings, it is really bad.

**Comment by opanyaki** [comment]
Agreed😞

**Comment by KelSolaar** [comment]
Discussing with @nick-shaw, and kind of inline with what I suspected yesterday, it might be that they baked the legal to full range conversion in the constants. I will try to verify later that this is the case.

**Comment by opanyaki** [comment]
Thank you!

Indeed, when "Scale Full to Legal Levels" is applied to the old one, it appears to match the new one!

**Comment by nick-shaw** [comment]
The `in_normalised_code_value` and `out_normalised_code_value` arguments in the Colour functions for Canon, Panasonic and Sony are designed to handle this. But obviously baking the scaling into constants, and giving them to a particular precision will limit the precision to which the results match.
