### ISSUE TITLE
[BUG]: "Automatic Colour Conversion Graph" broken image link on `https://www.colour-science.org/colour/`

### ISSUE THREAD

**Issue by da5nsy** [colour-science/colour#1179]
### Description

![image](https://github.com/colour-science/colour/assets/3739866/b39c6e5f-8b19-4d33-b7a4-b4dcc7cd4909)

https://colour.readthedocs.io/en/develop/_static/Examples_Colour_Automatic_Conversion_Graph.svg 404s.

**Comment by KelSolaar** [comment]
Thank you, this is fixed!
