### ISSUE TITLE
[DOCUMENTATION]: `colour.plotting.ColourSwatch` class is not documented.

### ISSUE THREAD

**Issue by sobotka** [colour-science/colour#1187]
### Documentation Link

colour.plotting.ColourSwatch

### Description

It seems impossible to find classes and class parameters / methods in the documentation via search.

I believe this used to work. For example, searching for ColourSwatch used to pull up the class instancing parameters etc.

**Comment by KelSolaar** [comment]
Thanks @sobotka! I will look at the RST source, there might be something incorrectly set there.

**Comment by KelSolaar** [comment]
Fixed: https://colour.readthedocs.io/en/develop/generated/colour.plotting.ColourSwatch.html

**Comment by sobotka** [comment]
Nice work. Thank you.

Seemed odd as hell that I couldn’t find the classes!
