### ISSUE TITLE
Order of points in segment changes the result of `intersect_line_segments`

### ISSUE THREAD

**Issue by harshjain30** [colour-science/colour#1191]
In the [intersect_line_segments](https://github.com/colour-science/colour/blame/117d3102d6d3d40ce379672eecc4c469b20d6de6/colour/geometry/intersection.py#L126) method,

`
l_1 = np.array(
            [
                [[325, 421, [0, 0]]],
            ]
        ),
l_2 = np.array(
            [
                [[0, 1023], [0, 0]],
            ]
        )
`
will not produce an intersection, although 

`
l_1 = np.array(
            [
                [[0, 0], [325, 421]],
            ]
        ),
l_2 = np.array(
            [
                [[0, 1023], [0, 0]],
            ]
        )
`
correctly produces (0, 0) as the intersection.

**Comment by KelSolaar** [comment]
Hi @harshjain30,

I think you are seeing precision issues here possibly, I get and intersection in both cases for example on my macBook M1.

From a mathematical standpoint, yes the two points are in the same set so you could consider that they intersect but getting to that result with IEE754 floating point arithmetics is probably too much asking!

![image](https://github.com/colour-science/colour/assets/99779/7a418e04-244c-44cb-8bb8-ec5de4a360e1)

The following all intersect for me:

```python
import colour
import matplotlib.pyplot as plt
import numpy as np

l_1 = np.array(
    [
        [[325, 421], [0, 0]],
    ]
)
l_2 = np.array(
    [
        [[0, 1023], [0, 0]],
    ]
)

l_3 = np.array(
    [
        [[0, 0], [325, 421]],
    ]
)
l_4 = np.array(
    [
        [[0, 1023], [0, 0]],
    ]
)

print(colour.geometry.intersect_line_segments(l_1, l_2))
print(colour.geometry.intersect_line_segments(l_3, l_4))

plt.plot(l_1[0][..., 0], l_1[0][..., 1])
plt.plot(l_2[0][..., 0], l_2[0][..., 1])

plt.show()

l_1 = np.array(
    [
        [[-1, 0], [1, 0]],
    ]
)
l_2 = np.array(
    [
        [[0, -1], [0, 1]],
    ]
)

l_3 = np.array(
    [
        [[1, 0], [-1, 0]],
    ]
)
l_4 = np.array(
    [
        [[0, 1023], [0, 0]],
    ]
)

print(colour.geometry.intersect_line_segments(l_1, l_2))
print(colour.geometry.intersect_line_segments(l_3, l_4))

plt.plot(l_1[0][..., 0], l_1[0][..., 1])
plt.plot(l_2[0][..., 0], l_2[0][..., 1])
plt.show()
```

```
LineSegmentsIntersections_Specification(xy=array([[[ 0.,  0.]]]), intersect=array([[ True]], dtype=bool), parallel=array([[False]], dtype=bool), coincident=array([[False]], dtype=bool))
LineSegmentsIntersections_Specification(xy=array([[[ 0.,  0.]]]), intersect=array([[ True]], dtype=bool), parallel=array([[False]], dtype=bool), coincident=array([[False]], dtype=bool))
LineSegmentsIntersections_Specification(xy=array([[[ 0.,  0.]]]), intersect=array([[ True]], dtype=bool), parallel=array([[False]], dtype=bool), coincident=array([[False]], dtype=bool))
LineSegmentsIntersections_Specification(xy=array([[[ 0.,  0.]]]), intersect=array([[ True]], dtype=bool), parallel=array([[False]], dtype=bool), coincident=array([[False]], dtype=bool))
```

![image](https://github.com/colour-science/colour/assets/99779/bfbabd36-5b50-44ad-92f2-c63edbb64d8f)
