### ISSUE TITLE
[FEATURE]: Implement support for *Apple Log Profile*.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#1204]
### Description

# References
- https://developer.apple.com/download/all/?q=Apple%20log%20profile

**Comment by fredsavoir** [comment]
Hi I could implement that next week if you want me too :)

Let me know I do have time.

Thanks

Fred

**Comment by KelSolaar** [comment]
Sorry Fred for the late reply, been intense at work! Feel free to give it a crack yeah! Thank you.
