### ISSUE TITLE
Investigate where Bruce Lindbloom's "Von Kries" chromatic adaptation transform matrix is coming from.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#121]
The matrix we are using for _Von Kries_ CAT is originating from _Bruce Lindbloom_ website: http://brucelindbloom.com/Eqn_ChromAdapt.html, the issue is that there is no source for it or any of them actually, and I ran into that paper specifying a different _Von Kries_ CAT from _Hunt_, _Pointer_ and _Estevez_: http://infoscience.epfl.ch/record/34049/files/SusstrunkFH01.pdf

_Bruce Lindbloom_:

``` Python
[[ 0.4002400, 0.7076000, -0.0808100]
 [-0.2263000, 1.1653200,  0.0457000]
 [ 0.0000000, 0.0000000,  0.9182200]]
```

_Hunt_, _Pointer_ and _Estevez_:

``` Python
[[ 0.3897, 0.6890, -0.0787]
 [-0.2298, 1.1834,  0.0464]
 [ 0.0000, 0.0000,  1.0000]]
```

**Comment by ValZapod** [comment]
Actually here it is a good questions and such. https://sci-hub.si/10.1002/9780470175637

**Comment by ValZapod** [comment]
@KelSolaar Listen, there was a mistake in cite to this matrix https://en.wikipedia.org/wiki/LMS_color_space#Hunt,_RLAB (Normalized to D65) as can be seen in errata to that cite (a book) http://rit-mcsl.org/fairchild//PDFs/Errata2e.pdf

> The published MCAT02 matrix in Eq. 9.40 is incorrect (it is a version of the HuntPointer-Estevez matrix. The correct MCAT02 matrix is as follows. It is also given correctly in Eq. 16.2

And I am not even talking to the fact it is a matrix used for differenet thing. The correct matrix can be seen in https://sci-hub.si/10.1002/9780470175637 or in https://scholarworks.rit.edu/theses/2858/ (free). Can you check your code is correct? It does not look like you are using it, but still.

**Comment by KelSolaar** [comment]
Hi @ValZapod,

We are using the correct one, thanks for checking though!

https://github.com/colour-science/colour/blob/c8acc31a8507dae1af81d7958490ac3428dc2728/colour/adaptation/datasets/cat.py#L184

Cheers,

Thomas

**Comment by ValZapod** [comment]
@KelSolaar No, you did not undertsand. The mistake was not in CAT02_CAT matrix. It was in the Hunt and RLAB color appearance models (for D65), look into diff in wikipedia.
https://en.wikipedia.org/w/index.php?title=LMS_color_space&diff=946587387&oldid=946584808&diffmode=source
https://github.com/colour-science/colour/blob/c8acc31a8507dae1af81d7958490ac3428dc2728/colour/adaptation/datasets/cat.py#L94-L98

This matrix (if it is for D65) is incorrect.

**Comment by KelSolaar** [comment]
Well, the quote you gave in https://github.com/colour-science/colour/issues/121#issuecomment-601989207 is for CAT02:

```
The published MCAT02 matrix in Eq. 9.40 is incorrect (it is a version of the HuntPointer-Estevez matrix. The correct MCAT02 matrix is as follows. It is also given correctly in Eq. 16.2
```

Hence my answer :)

I will look at the Von Kries one.

**Comment by ValZapod** [comment]
It is complecated, apparently author gave Von_Kries matrix insteed of Mcat02 matrix in the book and even that Von_Kries matrix was for D6X, where X is not 5)) So the matrix for D65 is slightly different as follows 0.4002 & 0.7075 & -0.0807 \\ -0.2280 & 1.1500 & 0.0612 \\ 0 & 0 & 0.9184

**Comment by KelSolaar** [comment]
Note that for IPT, we use the one as given in the model: https://github.com/colour-science/colour/blob/c8acc31a8507dae1af81d7958490ac3428dc2728/colour/models/ipt.py#L47

So it does not really matter in for any of the models, however, if you want to use chromatic adaptation only with that particular matrix, you are using something whose origin is unclear. I might actually contact Lindbloom directly to know more about it.

**Comment by ValZapod** [comment]
My main source is this (it is talking about Von_Kries) https://sci-hub.si/10.1002/9780470175637 page 305.

**Comment by KelSolaar** [comment]
The matrix there is the IPT one, it does not explain where the Von Kries from Lindbloom is coming from though.

**Comment by ValZapod** [comment]
Oh, I found it. Here. https://scholarworks.rit.edu/theses/2858/ Page 128. Looks I make a mistake and RLAB is actually not the same as D65 from IPT. Can you look, please? "The normalized form of the matrix used in the model was derived from multiplying the D65 matrix whose diagonal elements comprise to be D65 white data."

**Comment by KelSolaar** [comment]
Good find! The matrix is sourced from here: https://onlinelibrary.wiley.com/doi/abs/10.1002/col.5080180308

**Comment by KelSolaar** [comment]
Looking at the code it is actually the CIE1994 / Nayatani95 one and we use it directly: 

https://github.com/colour-science/colour/blob/c8acc31a8507dae1af81d7958490ac3428dc2728/colour/appearance/nayatani95.py#L61

https://github.com/colour-science/colour/blob/c8acc31a8507dae1af81d7958490ac3428dc2728/colour/adaptation/cie1994.py#L46

Mistery solved, I might have come to the same conclusion 6 years ago but did not remember.

**Comment by ValZapod** [comment]
So I will revert wikipedia then? It would be perfect to undertand how that get that IPT matrix... Sigh. Okay, then.

**Comment by KelSolaar** [comment]
Unfortunately, it is quite a common issue in this domain, usually arises from errors when reproducing values to precision/rounding related error.

**Comment by ValZapod** [comment]
Reverted all that, very sorry for the noise(( What about IPTPQc2 with reshaping BTW, are you going to do it?? See https://patents.google.com/patent/US20180131938A1/ and here https://github.com/mpv-player/mpv/issues/7326#issuecomment-592221831

**Comment by KelSolaar** [comment]
No worries and you are welcome, I started to sweat a bit when you mentioned CAT02 earlier though :)

> What about IPTPQc2 with reshaping BTW, are you going to do it?? 

If the model is specifically patented, we probably won't! Note that we have ICtCp which is IPT + PQ: and probably very close (if not the same): https://github.com/colour-science/colour/blob/c8acc31a8507dae1af81d7958490ac3428dc2728/colour/models/rgb/ictcp.py

**Comment by ValZapod** [comment]
Yep, like ICtCp except for the second matrix that is just like here for IPT except one number is different...
So nope, it is Dolby Vision)) There is also chroma reshaping that is done in SEI of HDMI (that one is still not implemented in VLC, alas, only in Java in one place) and there are also some other problems, VLC in their placebo partialy done that but alas, colours are not perfect and there some strange colour changes as scene changes https://code.videolan.org/videolan/libplacebo/commit/f850fa2839f9b679092e721068a57b0404608bdc

**Comment by KelSolaar** [comment]
It is patented, so it is pretty much a no-go for a library like Colour.
