### ISSUE TITLE
[DOCUMENTATION]: Typo in spectral upsampling docs

### ISSUE THREAD

**Issue by nestor98** [colour-science/colour#1233]
### Documentation Link

https://colour.readthedocs.io/en/develop/generated/colour.XYZ_to_sd.html

### Description

The first example in the XYZ to sd docs has a typo in the year:

> Jakob and Hanika (**2009**) reflectance recovery

### Suggested Improvement

The year should be 2019:

Wenzel Jakob and Johannes Hanika. A Low-Dimensional Function Space for Efficient Spectral Upsampling. Computer Graphics Forum, 38(2):147–155, May 2019. [doi:10.1111/cgf.13626](https://doi.org/10.1111/cgf.13626).

**Comment by KelSolaar** [comment]
Thanks @nestor98!
