### ISSUE TITLE
[ENHANCEMENT] ARRI White paper now gives matrices to 18 decimal places.

### ISSUE THREAD

**Issue by nick-shaw** [colour-science/colour#1240]
https://github.com/colour-science/colour/blob/8098fbc6c5031a8542ead303b35d080f90a3ffed/colour/models/rgb/datasets/arri.py#L126

I notice that the [ARRI LogC4 white paper](https://www.arri.com/resource/blob/278790/db65b86066de1f74852edb8f15acf082/2023-05-arri-logc4-specification-data.pdf) has been updated, and now gives the NPM coefficients to 18 decimal places. We only use the 10 from the earlier version of the paper.

**Comment by KelSolaar** [comment]
Thanks Nick!
