### ISSUE TITLE
[BUG]: Error in *Google Colab* `colour_how-to_guide.ipynb`.

### ISSUE THREAD

**Issue by javimixet** [colour-science/colour#1271]
### Documentation Link

https://colab.research.google.com/notebook#fileId=1NRcdXSCshivkwoU2nieCvC3y14fx1X4X&offline=true&sandboxMode=true

### Description

This part of the code doesn't work as expected:

```python
gradient = colour.algebra.lerp(
    CAM16UCS[0][np.newaxis],
    CAM16UCS[1][np.newaxis],
    np.linspace(0, 1, 20)[..., np.newaxis])
```

### Suggested Improvement

Should be like this instead:

```python
gradient = colour.algebra.lerp(
    np.linspace(0, 1, steps)[..., np.newaxis],
    CAM16UCS[0][np.newaxis],
    CAM16UCS[1][np.newaxis])
```

**Comment by KelSolaar** [comment]
Thanks a lot @javimixet! We changed `colour.algebra.lerp` signature a while ago but forgot to update the example. This should now be fixed!
