### ISSUE TITLE
[BUG]: Initializing SpectralShape with values outside [360, 780] causes assertion to trigger

### ISSUE THREAD

**Issue by NogginBops** [colour-science/colour#1290]
### Description

When trying to create a `SpectralShape` that is outside the initial `[360, 780]` range the `__init__()` function triggers an assert when setting `self.start = 780` as the setting the property triggers an assert to go off as the `end` property is not yet set to the larger `1200` value.

If the intention is to make it impossible to create shapes outside the `[360, 780]` range this is poorly communicated in the documentation as no such limit is stated.

### Code for Reproduction

```python
color.colorimetry.SpectralShape(start=780, end=1200, interval=1)
```

### Exception Message

```shell
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-242-7cb4c6803d00> in <cell line: 13>()
     11 print("new end", peak_λ + (peak_λ - e_sd.shape.start))
     12 
---> 13 color.colorimetry.SpectralShape(start=780, end=1200, interval=1)
     14 
     15 reversed = e_sd.values[::-1]

/content/colour/colour/colorimetry/spectrum.py in __init__(self, start, end, interval)
    155         self._end: Real = 780
    156         self._interval: Real = 1
--> 157         self.start = start
    158         self.end = end
    159         self.interval = interval

/content/colour/colour/colorimetry/spectrum.py in start(self, value)
    186         )
    187 
--> 188         attest(
    189             bool(value < self._end),
    190             f'"start" attribute value must be strictly less than "{self._end}"!',

/content/colour/colour/utilities/common.py in attest(condition, message)
    462 
    463     if not condition:
--> 464         raise AssertionError(message)
    465 
    466 

AssertionError: "start" attribute value must be strictly less than "780"!
```

### Environment Information

```shell
I'm running colour in a google colab notebook, downloading the latest colour git repo.
```

**Comment by KelSolaar** [comment]
Hi @NogginBops,

You came across an edge case that I thought no one would ever encounter! :) Colour is about visible spectrum after all and you are way outside. This is not an excuse by the way and I will get a fix rolled. So technically, there is no limitation to the values the SpectralShape can take but under the hood, the default values before full initialisation are set to our default computation range.:

https://github.com/colour-science/colour/blob/ebc78d19dd9adad78b9adaf43d23ff7064403315/colour/colorimetry/spectrum.py#L154

What I would recommend until I roll a fix is to do something as follows:

```python
import colour
import numpy as np


class SpectralShape():
    def __new__(self, start, end, interval):
        shape  = colour.SpectralShape(0, np.finfo(np.float64).max, 1)
        shape.end = end
        shape.start = start
        shape.interval = interval
        return  shape

print(SpectralShape(780, 1200, 1))

(780, 1200, 1)
```

**Comment by NogginBops** [comment]
I managed to work around it by first creating a `SpectralShape` with normal parameters and then setting the `end` and `start` in that order to avoid the assert from triggering.

But in the end I realized that by being a little bit smarter about what I was doing I was able to avoid having to create a spectral shape this far outside the visible spectrum. So the bug should probably be fixed still but, I have no stake in it being fixed anymore :)
