### ISSUE TITLE
[DOCUMENTATION]: CONTRIBUTING failed to update after transition to uv & hatch #1300

### ISSUE THREAD

**Issue by wdonofrio** [colour-science/colour#1303]
### Documentation Link

https://www.colour-science.org/contributing/

### Description

The CONTRIBUTING doc did not transition accordingly after #1300 and its introduction to uv and hatch.

### Suggested Improvement

Doc requires modification to replace poetry commands with uv commands. May require additional edits.

### Environment Information

```shell
NA
```

**Comment by KelSolaar** [comment]
Hi @wdonofrio,

Thank you, I'm literally working on it and it will be updated when 0.4.5 is released either today or tomorrow.

Cheers,

Thomas

**Comment by KelSolaar** [comment]
The website has been updated!
