### ISSUE TITLE
[BUG]: Incorrect *Delta E ITP* reference.

### ISSUE THREAD

**Issue by nick-shaw** [colour-science/colour#1308]
https://github.com/colour-science/colour/blob/e7a3ac03c00abd38a153f79b71d31c3f00192395/colour/difference/delta_e.py#L21

The link points to https://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.470-6-199811-S!!PDF-E.pdf when the correct link would seem to be https://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.2124-0-201901-I!!PDF-E.pdf

**Comment by KelSolaar** [comment]
Thank you, good catch, it must be wrong in Zotero.

**Comment by KelSolaar** [comment]
Mmmh... This seems correct, unsure what happened:

![image](https://github.com/user-attachments/assets/65c19082-900a-4dc3-9742-364832da8e55)
