### ISSUE TITLE
Investigate potential issues with "Delta-E CIE 2000" computation code.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#179]
References:
- http://www.ece.rochester.edu/~gsharma/ciede2000/
- http://zschuessler.github.io/DeltaE/learn/

**Comment by KelSolaar** [comment]
We should include the test data from  [Sharma (2004) spreadsheet](http://www.ece.rochester.edu/~gsharma/ciede2000/dataNprograms/CIEDE2000.xls) into the unit tests suite.

**Comment by henczati** [comment]
Hi,
what do you think, how much does this affect CIE dE2000 usability? Should it still be considered the recommended formula for non-textiles?

**Comment by KelSolaar** [comment]
Hi,

This is potential issues with the code and not the formula itself. It is not trivial to implement and the referenced resources highlight the fact that errors may arise as the authors have found some in various online sources.

**Comment by henczati** [comment]
Well, I need to compare altered SPD-s in terms of colorimetric error/difference, and I had trouble even with the colour-space conversions.

This is the first time I'm doing this, and the fact that the XYZ values need to be divided by 100 confused me a bit. I mean, all the places I looked had the normalization factor `k` scale to 100 in the spectral-to-XYZ formulas, I just didn't get why if it has to be rescaled to the [0..1] range for other conversions (e.g. `XYZ_to_sRGB`, `XYZ_to_Lab`). Why not use `k = 1 / sum(SPD * y_bar)` straight away instead?

It did not help either that your IPython notebooks were not consistent on the matter. E.g. I did not find a trace of that division-by-100 in http://nbviewer.ipython.org/github/colour-science/colour-ipython/blob/master/notebooks/colorimetry/correction.ipynb when you compute the error in the end, but you use it in http://nbviewer.ipython.org/github/colour-science/colour-website/blob/master/ipython/about_reflectance_recovery.ipynb, and in the function docstings you also indicate that value correction should be applied.

It also added to my uncertainty, that while I was checking your code and whether I'm using it right, I tried to reproduce some other conversion results found on websites and in papers, but I could never get very close to them, not even by experimenting with rounding values in various stages of the computation and re-aligning the SPD-s. I calculated a CIE dE2000 difference (using your code) to see how significant the differences are. I tried it only for 1-or-2 cases, and got error values in the range 1-2. Maybe that could be acceptable with respect to JND interpretations, but still seems to be a *lot* simply for conversion.

**Comment by henczati** [comment]
I see. Thanks for the clarification.

What does this mean in relation to your implementation? In the light of this possibility, would you still encourage using `delta_E_CIE2000` or rather one of the others?

**Comment by KelSolaar** [comment]
As a safety measure I would use `delta_E_CIE1994` for now. I'll try to get the tests done tonight so that I can confirm the issue if any.

**Comment by henczati** [comment]
Thank you very much. It is much appreciated.

**Comment by henczati** [comment]
Are the JND interpretations of the '94 formula different from the 2000 one?

**Comment by KelSolaar** [comment]
Our implementation is in accordance with Sharma (2004) dataset.
