### ISSUE TITLE
Implement code from "Physically Meaningful Rendering using Tristimulus Colours" paper.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#182]
## References
- Meng, J., Simon, F., & Hanika, J. (2015). Physically Meaningful Rendering using Tristimulus Colours, 34(4).
- https://jo.dreggn.org/home/2015_spectrum_additional.zip

**Comment by KevinJW** [comment]
Interesting, wonder if selecting a different grid sampling - say something more perceptually uniform would improve the result at all, even something simple like starting from u'v' and projecting into xyz as that is still a linear mapping.

**Comment by KelSolaar** [comment]
I was wondering exactly the same: https://twitter.com/colour_science/status/604615013009981440
