### ISSUE TITLE
Extend "colour.plotting.colour_quality_bars_plot" definition support to multiple spd.

### ISSUE THREAD

**Issue by henczati** [colour-science/colour#198]
Feature/Enhancement request.

Like the named function, but...
(in order of priority)

 1. if given a list/array/tuple of multiple SPD-s, it shows a (not necessarily thinner) bar for every SPD for each sample tightly next to each other.
 1. the percentages on top of the bars are vertical (or switchable to be).
 1. ~~fully honours `figure_size` / not hard-wired to be a square plot.~~ Solved by setting the `kwarg` `aspect=None`.

    (bonus:)

 4. has some bar-to-SPD identification, e.g. coloured percentages and/or bar edges (which might look awful), or vertical label with SPD name or order number at the centre of the bar or before/after the percentage over the bar or under the bar/x-axis, or some combination like before/after the percentage when the bar is too low and at the centre of the bar when there is enough space, or something.

The 1st would be the most critical one, then you are welcome to cherry-pick from the rest what is easier to implement (I would need it before the end of the month), but nice enough for a thesis. :)

E.g. for 2 SPDs it could look something like this:
![multi_colour_quality_scale_bars_plot-proposal](https://cloud.githubusercontent.com/assets/5007476/8746316/594ad810-2c88-11e5-955c-357de4856ed0.png)

If you do not have the time to do it before the end of the month, please note.

Thanks in advance.

**Comment by KelSolaar** [comment]
I'll see what I can do!

**Comment by henczati** [comment]
Thanks, you *are* the man!

**Comment by KelSolaar** [comment]
Here is where I'm as of tonight, should be done tomorrow or day after I think:

![image](https://cloud.githubusercontent.com/assets/99779/8800311/c3d51aee-3005-11e5-9ad2-6ded122c7e9c.png)

![image](https://cloud.githubusercontent.com/assets/99779/8800314/c8943f56-3005-11e5-91cc-2215f65c9e0d.png)

![image](https://cloud.githubusercontent.com/assets/99779/8800316/cd932512-3005-11e5-9e1d-72c9a19b365d.png)

**Comment by henczati** [comment]
I think this looks awesome already. :) The pattern filling for identification is quite a good idea.
Thank you *very much*!  You are the man, indeed. :)

However, I have to ask: What is that negative value (-83.9)?
The [CQS article on Wikipedia](https://en.wikipedia.org/wiki/Color_Quality_Scale) says:
> Negative values of CQS are made impossible due to their potential for consumer confusion.

**Comment by KelSolaar** [comment]
> However, I have to ask: What is that negative value (-83.9)?

It is because the plot title is misleading :) It is actually CRI being shown here but the title used is the default of `colour.plotting.colour_quality_bars_plot` definition when no title has been passed. It should be updated correctly once I propagate the changes properly to the various CRI and CQS wrappers!

**Comment by henczati** [comment]
O...k.  I'm not sure I follow...  My understanding is that CQS is a *type* of CRI.  So does that mean that `colour.plotting.colour_quality_bars_plot` is actually plotting a "CIE R_a" CRI?  If so, why does the docstring say "Plots the *colour quality scale* ...", and why does the function call `colour_quality_bars_plot` with `colour_quality_scale` as a  parameter?

**Comment by KelSolaar** [comment]
`colour.plotting.colour_quality_bars_plot` is a generic plotting function that plots colour quality in general either *CRI* or *CQS*, in order to choose which colour quality algorithm you want to use / plot you either use `colour.plotting.colour_rendering_index_bars_plot` or `colour.plotting.colour_quality_scale_bars_plot`.

Take a look a the respective relate modules in the [colour.quality](https://github.com/colour-science/colour/tree/develop/colour/quality) package, it should make things clearer.

**Comment by henczati** [comment]
So `colour.plotting.colour_quality_scale_bars_plot` *does* plot CQS values.  Then I still not get the negative value.  Could it be a CQS implementation error then?

**Comment by henczati** [comment]
...Or the Wikipedia article can be mistaken, too...

**Comment by henczati** [comment]
I get it now. I misread the function name: `colour.plotting.colour_quality_scale_bars_plot` vs. `colour_quality_bars_plot`

**Comment by KelSolaar** [comment]
:]

**Comment by KelSolaar** [comment]
In [v0.3.6](https://github.com/colour-science/colour/tree/feature/v0.3.6):

![image](https://cloud.githubusercontent.com/assets/99779/8821674/af058762-30b3-11e5-9b58-81ecb6a1a730.png)

![image](https://cloud.githubusercontent.com/assets/99779/8821680/b36c7cde-30b3-11e5-8f17-7299b930588e.png)

![image](https://cloud.githubusercontent.com/assets/99779/8821687/b8b1da68-30b3-11e5-9eb8-89389b18dc02.png)

![image](https://cloud.githubusercontent.com/assets/99779/8821689/bf20dec6-30b3-11e5-8a8c-9461ad05377c.png)

Feel free to play with it and let me know if you need anything :)

**Comment by henczati** [comment]
Looks cool, thanks!

Additional notes:
  * The amount of space that is reserved above the bars for the legend looks a bit inconsistent to me: a lot for 1 SPD, almost none for 3, and it seems to vary even for the same amount of SPDs. (I'm too tired now to understand that formula..)
  * It would be nice if I could set some `font_size` or a scale factor for the labels on the bars.  E.g. for 5 SPDs they're already overlapping.
  * Why is the `hatching_repeat` not 1 by default?  It lets more colour to show.  I even tried to set it to a fractional value below 1..  That did not work of course. :)  Also, I'm not sure if it would be possible at all, but could the hatching be set to partially transparent (maybe with a kwarg factor to tweak it)?
  * Would it be possible to set the Q* labels on the x-axis to be (at least more-or-less) at the middle of the batches?
  * I think it's ok that the hatching is on by default in the bars plot, but the single_spd_* wrappers could call it with `hatching=False`.  No need to hatch there.
  * How can I send you beer or something?...I owe you some already... :)

**Comment by KelSolaar** [comment]
I took the liberty of editing your comment to add numbered bullet list, hope you don't mind!

1. Well it is actually proportional to the scale, the limits are set to 120 in the quality space so that there is a bit of room above the bars.
2. I will try to come up with something.
3. It is a left over of my tests. I can't do transparency unfortunately :( I would suggest trying to render and composite two plots together (one with, one without the hatching).
4. Yes of course!
5. Absolutely, wanted to do it and forgot about it! :)
6. Spread the word about the API and I'll be more than happy ;)

**Comment by KelSolaar** [comment]
Here we go:

![image](https://cloud.githubusercontent.com/assets/99779/8848476/b54fcd34-318b-11e5-870a-9d82d207f96c.png)

![image](https://cloud.githubusercontent.com/assets/99779/8848485/bf9d8fa6-318b-11e5-8cb9-4a339aefa302.png)

I took that opportunity to make sure that the CRI plot is all positive, it will issue a warning though. It simplifies the code and makes the plot prettier.

**Comment by henczati** [comment]
Pretty enough, well done. ;)

 1. Thanks. I think this would work well as far as sensible (and simple) defaults go. I almost suggested a much more complicated way of doing it... :) Maybe I would still add a check that when there is no legend to display, only the labels need the space above the 100-line.
 2. Thanks.
 3. Transparency: Not that important anyway (notebooks will be fine without it, publications can just use the workaround you suggested).

    (Future) Hatching: The way you did it seems perfect for my current needs, but occurred to me that later maybe a kwarg to specify a hatching pattern list could prove to be useful (milestone v9.9.9 perhaps :) ).
 4. Thanks.
 5. Thanks.
 6. I will do that anyway. Even if I don't actually know anyone who does colour science (apart from my supervisor, and I found out about your project myself by him showing me the illuminants notebook from your site), :) your package was/is of considerable help (in understanding what I'm trying to do better, doing it, and seeing well implemented python code :P). I'm no expert, but in my opinion it's fairly easy to use (even if it still seems a bit inconsistent in places, but it is still taking shape) while having a really professional quality and being done/implemented conscientiously. I think it has a very real chance of attracting new people (like me) to try and maybe even take up or contribute to the field itself. Kudos, again. :)

    But seriously, you did *fine* work in *short notice* when I *needed* it, and helped me (a perfect stranger) without any obligations whatsoever. Even if we consider the open-source mentality, you could have answered e.g. a month from now. Positive feedback / reward / a treat is much deserved in my opinion. ;)

Another thing: I observed that when I run the plots even in a simple notebook with just
```python
%matplotlib inline
import colour
from colour.plotting import *

single_spd_colour_quality_scale_bars_plot(colour.ILLUMINANTS_RELATIVE_SPDS['f11'])
```
in a "fresh" or restarted IPython kernel (only the first time I run it!), I get the following in a red box above the displayed plot:
`[...]/anaconda/lib/python2.7/site-packages/colour/models/dataset/srgb.py:111: RuntimeWarning: invalid value encountered in power
  1.055 * (value ** (1 / 2.4)) - 0.055)`
What do you think about it? Is this a problem or should I ignore it?

**Comment by KelSolaar** [comment]
1. Well in any case it is still possible to set yourself the limits and display / location of the legend:

```python
multi_spd_colour_rendering_index_bars_plot((
    colour.ILLUMINANTS_RELATIVE_SPDS.get('F2'),
    colour.LIGHT_SOURCES_RELATIVE_SPDS.get('F32T8/TL841 (Triphosphor)'),
    colour.LIGHT_SOURCES_RELATIVE_SPDS.get('Kinoton 75P')),
    limits=[0, 30, 0, 100],
    legend_location='lower right',
    labels=False)
```
![image](https://cloud.githubusercontent.com/assets/99779/8860446/e93dc0be-31d7-11e5-9550-48c7e8b15bca.png)

3. You can set the patterns yourself here: https://github.com/colour-science/colour/blob/feature/v0.3.6/colour/plotting/common.py#L150

:)

**Comment by henczati** [comment]
Ok, looks like you thought it out pretty well.
Thanks again.

**Comment by KelSolaar** [comment]
Cool! I'll merge the branch in *develop* tonight / this weekend.

**Comment by henczati** [comment]
Ok, wait a sec.
I didn't actually test it. I should kinda be doing something else right now (a little refactoring, bugfixing and stuff of my own), and wanted to get back to this a bit later when creating the actual plots I plan to use (maybe during the weekend, but hopefully not later than the first part of next week).

(**TL;DR** in the bottom)

Any good and simple heuristic for x limits to consider?
y has a scale with numbers, but x doesn't, and it does not show itself well from the code either.  

As I was experimenting a little with limits, I also got some weird results:
```python
%matplotlib inline

import colour
from colour.plotting import *

single_spd_colour_quality_scale_bars_plot(colour.ILLUMINANTS_RELATIVE_SPDS['f11'],
                                         limits=[-0.3,10,0,104])
```
![plot_with_limits](https://cloud.githubusercontent.com/assets/5007476/8868494/5d61bfe4-31d9-11e5-90aa-455ea1d704e9.png)
Ok, setting lower limits is probably not the desired use-case scenario, so culling the labels is not essential.  I could imagine a scenario when one would want to show only one or a range of the sample results, e.g. to emphasize one/some of them, but that's nothing a little image editing wouldn't solve afterwards...unless one would want to have it in a notebook...  But I guess it could probably also be done by somehow redefining/rearranging the samples in the `colour_quality_bars_plot` `specification` or something.

However, what I think would be more important is to allow setting `limits` partially so one could override only some of the values.  E.g. `limits=[None, None, None, 104]` would only redefine the ymax limit (or allow something like `limits=dict(ymax=104)` or I don't know).
I realized that I could just use `..., standalone=False); matplotlib.pyplot.ylim(ymax=104); display()`, but isn't the point of `limits` to make things easier?

Also, it could be useful that `limits=[0,...]` sets the border exactly on the edge of the 1st box would I want to make it tight, but if I want to maintain most of the defaults while making a single change, it is a bit unpleasant that I have to experiment to find some arbitrary values when I don't even see the scale.  For the high-x-end, I don't even have that---my impression is that it would be much more difficult to find the exact limit to set there.
Maybe it would also be useful to rescale the x axis so the boxes would always occupy the range from 0 to 100 exactly (the first starting on 0 like now, and the last ending on 100).  I chose 100 because the boxes also range from 0 to 100 on the y axis, but 0-to-1 would work, too, or I don't know, 0-to-15 or 1-to-16 as there are 16 samples in the CQS plot.  I'm sure you'll figure something out that is intuitive, easy to use and easy to implement. You always do. ;)

---

(**TL;DR**) So in a nutshell (not deal-breakers, but for convenience):
 1. Allow `None` in `limits` or some other mechanism for partial definition (e.g. `limits=dict(ymax=104)` or something).
 2. Rescale the x axis so setting xlim-s without seeing the scale would be easier (e.g. 0-to-100, or 0-to-1, or 0-to-15 or 0-to-16, or something).

    (not important, maybe milestone v9.9.9 or just forget about it:)
 3. Cull labels outside the borders.

**Comment by henczati** [comment]
p.s.: You did fine work and I can already use it right now, I just thought it could use a bit more polishing before merging into develop, but if you think it's already good enough, merge ahead.

**Comment by henczati** [comment]
Ok, I think I figured out my simple `x` heuristic: currently bars are always `0.5` wide, starting from `0`. :)
It's not that bad, I can work with this.  Maybe it would be enough to put this in the docstrings or something.

**Comment by henczati** [comment]
It is not critical, but it would also be nice if I could specify the legend columns without having to `..., standalone=False); matplotlib.pyplot.legend(ncol=cols); display()`. But maybe that is already asking for too much.  You have to draw the limit somewhere before manually adding every possible plotting option, don't you... :)

**Comment by KelSolaar** [comment]
1. Could be interesting to handle the limits, margin and bbox this way, I would have to add a layer of logic in this function: https://github.com/colour-science/colour/blob/develop/colour/plotting/common.py#L311, definitely doable but not really a priority right now.
2. This is a bit annoying as it would probably have consequences on text size, etc... You seem to have figured out how to set the limit properly.
3. I forgot to clip the text :)
4. I will add a `kwarg` for legend columns: `legend_columns` and yeah it is indeed hard to find the right balance in the options you want to provide :)

**Comment by henczati** [comment]
Thanks for everything.  I can think of nothing else right now, and I have to go back to work on my code logic. I guess you have better things to do, too. ;)  Best wishes in the meantime.

**Comment by KelSolaar** [comment]
You are welcome! I'll close the issue then :)

By the way, we are working on something with @MichaelMauderer and maybe the stuff you are doing is related, would you mind dropping me a mail so that I can discuss about it with you?

Cheers,

**Comment by henczati** [comment]
1. #209 might be an option. But probably not for the near future. :)

Would that mail be colour-science@googlegroups.com?

**Comment by KelSolaar** [comment]
My gmail please :)
