### ISSUE TITLE
How to perform plots compositing / use subplots?

### ISSUE THREAD

**Issue by henczati** [colour-science/colour#199]
It might be just me, but I am unable to use `subplot`-like features on `colour`-generated plots.
Any pointers?
Thanks.

**Comment by KelSolaar** [comment]
You can take a look at this example for instance: 

https://github.com/colour-science/colour/blob/develop/colour/plotting/phenomenon.py#L107,

The trick lies into setting `standalone=False` in the `**kwargs`: https://github.com/colour-science/colour/blob/develop/colour/plotting/phenomenon.py#L149

Let me know if it works!

**Comment by henczati** [comment]
Thanks.
I looked at it, and simplified the workflow for some trials in an IPython console:
```python
# init:
import matplotlib.pyplot as plt
from colour.plotting import *

# trial (plotfunc1 and plotfunc2 are from colour.plotting):
plt.subplot(121)
plotfunc1(..., standalone=False)
plt.subplot(122)
plotfunc2(...)
```
It works only sometimes. If I don't choose both `plotfunc1` and `plotfunc2` (in any order) from a *good* set of functions, then I get a single empty figure. E.g. `single_colour_plot` was not amongst the *good* ones.

Then I noticed that `the_blue_sky_plot` uses  `single_colour_plot` as a `subplot`, and it works there.
So I found out that there are some...I'll call them *sensitive* functions, for which if I set the `kwarg` `aspect=None`, they work as a `subplot` but not without it.

Plotfuncs that I tried:
 - *good*: `visible_spectrum_plot`, `single_spd_plot`, `multi_spd_plot`
 - *sensitive*: `single_colour_plot`, `multi_colour_plot`, `colour_quality_scale_bars_plot`

I realized that setting `aspect=None` also allows e.g. `colour_quality_scale_bars_plot` to be drawn as a non-square figure (solving the 3. point in my #198 request).

Could you please explain what is the role of the `aspect` keyword exactly, what funcions use it and in which cases and to what values should it be set? Up to now, I did not find where the plotting `kwargs` are documented.

**Comment by KelSolaar** [comment]
The `kwargs` argument are not documented yet, it is part of my TODO list which is not available online.

However they are self-contained in those four definitions:
- [colour.plotting.canvas](https://github.com/colour-science/colour/blob/develop/colour/plotting/common.py#L180)
- [colour.plotting.camera](https://github.com/colour-science/colour/blob/develop/colour/plotting/common.py#L208)
- [colour.plotting.boundaries](https://github.com/colour-science/colour/blob/develop/colour/plotting/common.py#L311)
- [colour.plotting.display](https://github.com/colour-science/colour/blob/develop/colour/plotting/common.py#L250)

**Comment by henczati** [comment]
Thanks.  Good to know that I don't have to look elsewhere.

p.s.:  Btw, I found those even by myself, but they were only of limited help.  I guess I can thank my shallow knowledge of `matplotlib`'s workings for that. :)

**Comment by KelSolaar** [comment]
I'll try to document them in the next release although you indeed need a bit of knowledge of `matplotlib` to understand properly what they do.

**Comment by sdbbs** [comment]
Hi all,

Just wanted to post an example of this, as I had a hard time finding anything similar.

With the code below, you can get a plot within a predefined matplotlib subplot, which looks like this:

![test-colour](https://user-images.githubusercontent.com/48317456/70538614-b1aef680-1b62-11ea-9223-e15a3a8f4d4b.png)

This works in:

* colour.__version__ 0.3.13 in Anaconda, Windows 10
* colour.__version__ 0.3.14 in Ubuntu 18.04

... however, it will fail in colour.__version__ 0.3.11 (which is the current version in MSYS2/MINGW64)

Here is the code:

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import sys

import numpy as np
import matplotlib
print("matplotlib.__version__ {}".format(matplotlib.__version__))
import matplotlib.pyplot as plt

import colour
print("colour.__version__ {}".format(colour.__version__))

from colour.plotting import *

# this gets/sets the colour style for matplotlib plot, https://colour.readthedocs.io/en/develop/_modules/colour/plotting/common.html
colour_style()

RGB = np.random.random((4, 4, 3))

fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(9, 6), dpi=120, gridspec_kw={'height_ratios': [1, 1]}) # sharex=True,
fig.subplots_adjust(hspace=0)

# setup first subplot
pl21, = ax1.plot([0, 100], [0, 200], color="Red")

# via https://colour.readthedocs.io/en/develop/_modules/colour/plotting/common.html
settings = {
  'figure': fig,
  'axes': ax2,
  'uniform': False,
  'aspect': 'auto',
  'font.size': 7,
}

# do the plot of CIE diagram on the figure and axes (subplot) specified in settings:
plot_RGB_chromaticities_in_chromaticity_diagram_CIE1931(
  RGB,
  standalone=False,
  **settings,
)

# do the blackbody curve on top of previous CIE diagram in same figure and axes (subplot) specified in settings:
colour.plotting.temperature.plot_planckian_locus(planckian_locus_colours=None, method='CIE 1931', standalone=False, **settings)

plt.show()
```

**Comment by MichaelMauderer** [comment]
Thanks for the feedback. Could you describe what happens instead? Or if there is an exception, post the backtrace?

**Comment by sdbbs** [comment]
Hi @MichaelMauderer ,

> Could you describe what happens instead? Or if there is an exception, post the backtrace?

Ah, yeah - sorry; about the:

> fail in colour.version 0.3.11 

... it is simply because of API changes, I think; first problem is:

```
$ python3 /tmp/test-colour.py
matplotlib.__version__ 3.1.2
colour.__version__ 0.3.11
C:/msys64/mingw64/lib/python3.8/site-packages\colour\utilities\verbose.py:141: ColourWarning: "x" independent variable is not uniform, unpredictable results may occur!
  warn(*args, **kwargs)
Traceback (most recent call last):
  File "C:/msys64/tmp/test-colour.py", line 18, in <module>
    colour_style()
NameError: name 'colour_style' is not defined
```

Then, if I comment the `colour_style()` line, I get:

```
$ python3 /tmp/test-colour.py
matplotlib.__version__ 3.1.2
colour.__version__ 0.3.11
C:/msys64/mingw64/lib/python3.8/site-packages\colour\utilities\verbose.py:141: ColourWarning: "x" independent variable is not uniform, unpredictable results may occur!
  warn(*args, **kwargs)
Traceback (most recent call last):
  File "C:/msys64/tmp/test-colour.py", line 38, in <module>
    plot_RGB_chromaticities_in_chromaticity_diagram_CIE1931(
NameError: name 'plot_RGB_chromaticities_in_chromaticity_diagram_CIE1931' is not defined
```

I presume `plot_RGB_chromaticities_in_chromaticity_diagram_CIE1931` in v0.3.11 must have been called `RGB_colourspaces_chromaticity_diagram_plot_CIE1931` ( via https://github.com/colour-science/colour/blob/v0.3.11/colour/plotting/models.py )

**Comment by KelSolaar** [comment]
`colour.plotting.colour_style` _equivalent_ would be `colour.plotting.colour_plotting_defaults` in 0.3.11.

> I presume plot_RGB_chromaticities_in_chromaticity_diagram_CIE1931 in v0.3.11 must have been called RGB_colourspaces_chromaticity_diagram_plot_CIE1931 ( via https://github.com/colour-science/colour/blob/v0.3.11/colour/plotting/models.py )

Yes! [0.3.12](https://github.com/colour-science/colour/releases/tag/v0.3.12) was a rather large release and a ton of stuff has been renamed, we support forward migration, e.g. redirected the old object name to the new one and emit a warning but it only works one way :)
