### ISSUE TITLE
How to change "DEFAULT_*" settings from "colour.plotting"?

### ISSUE THREAD

**Issue by henczati** [colour-science/colour#205]
1. Say, if I want a different figure width in my workflow, could I change the default settings so that I would not have to specify them for all function calls?

 2. Is it possible to easily change these settings in a way that functions from `colour.plotting` and custom functions using only `matplotlib` calls would have these settings shared?

**Comment by KelSolaar** [comment]
1. Yes, I think the following should work:

```python
import colour.plotting.common

colour.plotting.common.DEFAULT_FIGURE_WIDTH = 24
colour.plotting.common.DEFAULT_FIGURE_HEIGHT = 12
```

Take a look specifically at the default here: https://github.com/colour-science/colour/blob/develop/colour/plotting/common.py#L81

2. I'm not sure to understand this question, is it different from 1.?
