### ISSUE TITLE
Implement support for "ANSI/IES TM-30-18" computation.

### ISSUE THREAD

**Issue by Rob-Welch** [colour-science/colour#207]
IES have defined a new standard for colour quality in their paper '[IES Method for Evaluating Light Source Color Rendition](http://www.ies.org/store/product/ies-method-for-evaluating-light-source-color-rendition-3368.cfm)' which will apparently be out at the end of this month. As far as I can tell, it's basically a modified version of CRI\CQS and a modified version of GAI. Are there any plans to implement this in Colour?

By the way, thanks for producing this package!

**Comment by KelSolaar** [comment]
Quite interesting, I wasn't aware about it although I had this one somehow planned: [The CRI-CAM02UCS colour rendering index](http://onlinelibrary.wiley.com/doi/10.1002/col.20682/abstract)

**Comment by KelSolaar** [comment]
The standard has been updated and is available here: https://www.ies.org/product/ies-method-for-evaluating-light-source-color-rendition/

**Comment by KelSolaar** [comment]
Hey @Rob-Welch,

This has **finally**, been implemented as per #621.

Cheers,

Thomas
