### ISSUE TITLE
About "RuntimeWarning: invalid value in power ..." warnings.

### ISSUE THREAD

**Issue by henczati** [colour-science/colour#208]
I observed that when I run some plots, e.g.
```python
%matplotlib inline
import colour
from colour.plotting import *

single_spd_colour_quality_scale_bars_plot(colour.ILLUMINANTS_RELATIVE_SPDS['f11'])
```
in a notebook with a "fresh" or restarted IPython kernel (only the first time I run it!), I get the following in a red box above the displayed plot:
`[...]/anaconda/lib/python2.7/site-packages/colour/models/dataset/srgb.py:111: RuntimeWarning: invalid value encountered in power
  1.055 * (value ** (1 / 2.4)) - 0.055)`

Is this a problem or should I ignore it?

p.s.: I currently use Anaconda (v2.3.0) as my Python environment, with the Accelerate / MKL Optimizations commercial plugins/packages. `colour` is installed from the git repo's `feature/v0.3.6` branch at this point.

**Comment by KelSolaar** [comment]
I personally ignore them, it is happening in the conversion from tristimulus values to *RGB* as you may have negative values (which are perfectly fine). *Numpy* will generate some *nans* in that context, which is perfectly valid too. It is the way you handle them that matters, as it is only in colours display context is it is fine to ignore them as from the start we know *sRGB* cannot represent properly all the colours.

```python
import numpy as np

1.055 * (np.array([-2.0]) ** (1.0 / 2.4)) - 0.055
```
> -c:26: RuntimeWarning: invalid value encountered in power

**Comment by henczati** [comment]
Ok, thanks.

**Comment by KelSolaar** [comment]
You are welcome!
