### ISSUE TITLE
"colour.SpectralPowerDistribution" and "colour.TriSpectralPowerDistribution" classes operations happen in place.

### ISSUE THREAD

**Issue by naavis** [colour-science/colour#217]
I noticed that many of the SPD and TSPD operations (at least addition, subtraction, multiplication, division and align) happen in place, e.g. `a + b` results in `a` equalling `a + b`. The documentation warns about this, but why are the operations implemented like this in the first place? Doing basic arithmetic in-place is unexpected and a very easy way of introducing subtle and hard-to-find bugs in code using the colour science library. I also think the `align` operation shouldn't happen in-place, eventhough this can be argued.

**Comment by KelSolaar** [comment]
There is no rational that I remember behind it. It can definitely be error prone and is probably an unexpected behaviour. That being said it will change in the future as we are re-working (in a non-backward compatible way) the spectral code: https://github.com/colour-science/colour-ramblings/blob/master/spectral_signal.ipynb
