### ISSUE TITLE
Missing corresponding illuminants SPD <---> chromaticity coordinates data.

### ISSUE THREAD

**Issue by henczati** [colour-science/colour#219]
`colour.ILLUMINANTS['cie_2_1931']` has got `DCI-P3` and is missing `F11` compared to `colour.ILLUMINANTS_RELATIVE_SPDS` and `colour.ILLUMINANTS['cie_10_1964']`.

**Comment by KelSolaar** [comment]
Good catch with `F11`, I'm not even sure how it managed to slip through. From the history it is missing even before I push the first commits to Github.

`DCI-P3` doesn't have an official associated SPD and just exists as chromaticity coordinates for the `CIE 1931 2 Degree Standard Observer`. The closest theoretical SPDs for it are the ones from Xenon Arc Lamps: https://github.com/colour-science/colour/blob/develop/colour/colorimetry/dataset/light_sources/spds.py#L5079

**Comment by henczati** [comment]
Thanks.
