### ISSUE TITLE
Implement support for "Prismatic" colourspace.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#223]
## References
- http://www.cs.utah.edu/~shirley/papers/prismatic.pdf
- http://psgraphics.blogspot.co.nz/2015/10/prismatic-color-model.html

**Comment by KelSolaar** [comment]
@MichaelMauderer: I'm wondering if there is any real interest to implement this colourspace. What do you reckon?

**Comment by MichaelMauderer** [comment]
The paper looks interesting. Might be worth of inclusion to lower barrier to entry for its use.

**Comment by KelSolaar** [comment]
Sounds good! I had a Nuke implementation somewhere it was straightforward.
