### ISSUE TITLE
ACESproxy uses incorrectly AP0 primaries instead of AP1 as per ACES 1.0.

### ISSUE THREAD

**Issue by Nick-Shaw** [colour-science/colour#225]
With the 1.0 release of ACES, ACESproxy was updated to use AP1 primaries, instead of the AP0 primaries defined in the original spec. This makes it compatible with ACEScc. The updated documentation is here: http://j.mp/S-2013-001

The colour space definition for ACESproxy in aces.py appears to still use the original AP0 primaries.

**Comment by KelSolaar** [comment]
Good catch, I thought I have done it when I did the update pass following the 1.0 release, proven to be wrong! :)
