### ISSUE TITLE
Implement support for "RGBA" arrays.

### ISSUE THREAD

**Issue by foutoucour** [colour-science/colour#230]
Hey here,

Awesome work on this library! Really usefull and the interface is pretty neat!
We would need to manage RGBA color. Is it anything in your roadmap or it would be out of scope of the library?

Cheers from the other side of the world :)

Jordi

**Comment by KelSolaar** [comment]
Hi Jordi!

Thanks for the kind words :)

It is indeed somehow out of the scope of the API as most of colour science related work is applied on vectors with 3 or 1 component(s). Most of the functions should support n-dimensional arrays provided the last axis is the one with your vectors.

That being said, it is quite easy to work around that, and most of the time I assume you will want your **A** alpha channel not affected by any transformation (and maybe even un-premultiply your **RGB** values beforehand).

Here is a snippet illustrating how to split a given array and recombine it accordingly:

```python
import numpy as np
import colour

# Generating some data.
RGBA = np.random.rand(512, 256, 4)
print(RGBA)
print('*' * 79)

# Splitting the *RGBA* array in two *RGB* and *A* arrays.
RGB = RGBA[..., 0:3]
# Alpha channel shape massaging for later concatenation.
A = np.rollaxis(RGBA[..., 3][np.newaxis], 0, 3)

# Applying a function on *RGB*.
# Note: This example doesn't mean anything.
RGB = colour.XYZ_to_Lab(RGB)

# Combining the *RGB* and *A* arrays back together.
RGBA = np.dstack((RGB, A))
print(RGBA)
```

**Comment by KelSolaar** [comment]
Another probably more useful example (I actually haven't tried it :D), we will convert a given **RGBA** array to *Luminance*:

```python
import numpy as np
import colour

# Generating some data.
RGBA = np.random.rand(512, 256, 4)
# Alpha channel shape massaging for un-premultiplication.
A = np.rollaxis(RGBA[..., 3][np.newaxis], 0, 3)

# Un-premultiplied *RGB*.
RGB = RGBA[..., 0:3] / A

# Conversion to single channel *Luminance* *L* (3D array ---> 2D array).
L = colour.RGB_luminance(RGBA[..., 0:3],
                         colour.sRGB_COLOURSPACE.primaries,
                         colour.sRGB_COLOURSPACE.whitepoint)

# Dropping a dimension on *A* because *L* is now a 2D array.
A = np.squeeze(A)

# Pre-multiplied *L*.
L *= A

# *Tail* stacking using convenient `colour.tstack` definition.
# Note: *tail* splitting is performed with `colour.tsplit` definition.
LLLA = colour.tstack((L, L, L, A))

print(LLLA)
```

**Comment by foutoucour** [comment]
Thanks man!

It will be too complicated for what we are trying to do. We will do it the old way and come back to your lib once Marie will rethink our color pipeline.

Thanks for the examples!

Jordi
