### ISSUE TITLE
Implement support for "Hunter L,a,b" and "Hunter Rd,a,b" colour scales.

### ISSUE THREAD

**Issue by Ron024** [colour-science/colour#231]
It would be nice to see the addition of Hunter Lab calculations to the package.
http://www.easyrgb.com/index.php?X=MATH&H=05

**Comment by KelSolaar** [comment]
References
---------------
- http://www.hunterlab.se/wp-content/uploads/2012/11/Hunter-L-a-b.pdf
- http://www.hunterlab.com/an-1005b.pdf

Hi @Ron024, sounds like a good idea for completeness! Do you have any use for it? I assume that most people are using the *CIE* version.

**Comment by Ron024** [comment]
I do use it to work with historical data that I have.  If you would like I could try implementing it similar to the CIE calculations.

**Comment by KelSolaar** [comment]
Sounds good to me!

**Comment by KelSolaar** [comment]
@Ron024: Support is implemented in a [feature branch](https://github.com/colour-science/colour/tree/feature/hunterlab) through the following definitions:

- `colour.XYZ_to_Hunter_Lab`
- `colour.Hunter_Lab_to_XYZ`
- `colour.XYZ_to_Hunter_Rdab`

I noticed that *HunterLab* provides various table of optimised illuminants data depending the measurement apparatus. I have only implemented a generic table from one of their paper for now.
