### ISSUE TITLE
About having "SciPy" as a strong dependency.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#237]
Right now we have [SciPy](http://www.scipy.org/) as a soft dependency which implies that we have some [safeguard and fallback code scattered across the API](https://github.com/colour-science/colour/blob/645fd04524a1cec4f7150deaf47c59fc4c164cb7/colour/algebra/interpolation.py#L556). I'm not convinced it is really maintainable in the long term, especially as we may rely on it for core features.

When somebody installs [NumPy](http://www.numpy.org/) chances are usually high that *Scipy* will be installed with it. Python distributions like [Anaconda](https://www.continuum.io/downloads) ship the whole scientific stack which smooth a lot installation issues.

My main concern is that right now it is not really possible to install *Numpy* and *Scipy* at same time with *Pip* as *Numpy* must be already installed first but there is no guarantee it will be.

**Comment by Ron024** [comment]
I would think most users of the package would be coming from a scientific installation of Python with the prerequisites installed.  It is a shame for the shortcomings of the libraries that we have to work with.  However, it the problem was well documented in the installation readme users would have a resource to troubleshoot their installation issue.

**Comment by KelSolaar** [comment]
> However, it the problem was well documented in the installation readme users would have a resource to troubleshoot their installation issue.

Yeah it is what I'm assuming.

**Comment by KelSolaar** [comment]
I may be wrong but it looks like that just depending on *SciPy* should be enough to get *NumPy* installed: https://github.com/scipy/scipy/blob/master/setup.py#L205
