### ISSUE TITLE
Implement option to remove the background image from chromaticity diagram plots.

### ISSUE THREAD

**Issue by scooperly** [colour-science/colour#239]
Not sure if I'm just not seeing this, but there should be an option to disable the colored background of chromaticity plots.

Reasons for implementation:
* color in these plots is technically incorrect (unless limited to display gamut) and often misleading
* improve general readability, especially when included in published papers

**Comment by KelSolaar** [comment]
Good and fair points!

**Comment by KelSolaar** [comment]
This should be implemented in the *develop* branch: https://github.com/colour-science/colour/blob/develop/colour/plotting/diagrams.py#L141 through the `show_diagram_colours ` keyword argument.
