### ISSUE TITLE
Implement support for "Barten (1999)" contrast sensitivity function.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#246]
## References
- http://proceedings.spiedigitallibrary.org/proceeding.aspx?articleid=837000
- http://car.france3.mars.free.fr/Formation%20INA%20HD/HDTV/HDTV%20%202007%20v35/SMPTE%20normes%20et%20confs/Contrastm.pdf
- http://www.umich.edu/~ners580/ners-bioe_481/lectures/pdfs/Barten_ch3s1-9.pdf
- https://www.smpte.org/sites/default/files/2014-05-06-EOTF-Miller-1-2-handout.pdf
- https://www.smpte.org/sites/default/files/23-1615-TS7-2-IProc02-Miller.pdf
- http://www.avsforum.com/forum/139-display-calibration/2020689-need-help-barten-contrast-sensitivity-function.html

**Comment by Nick-Shaw** [comment]
As an additional reference, here is a link to Barten's original paper:

- https://pure.tue.nl/ws/files/1613279/9901043.pdf
