### ISSUE TITLE
Prevent extra line breaks on "Windows" when exporting CSV files.

### ISSUE THREAD

**Issue by Ron024** [colour-science/colour#249]
There is an issue when calling colour.write_spds_to_csv_file where every line has an extra line between it.  If the file is written as a binary instead of an ASCII this problem is resolved.

**Comment by Ron024** [comment]
See fix in [https://github.com/Ron024/colour/commit/c75ccc6182e0681fc45274b7abd4ad17657b4d3b](https://github.com/Ron024/colour/commit/c75ccc6182e0681fc45274b7abd4ad17657b4d3b)

**Comment by KelSolaar** [comment]
Thanks @Ron024!

Would you mind opening a PR, that would be great! :+1:
