### ISSUE TITLE
Error in "colour-science.org" tutorial.

### ISSUE THREAD

**Issue by scooperly** [colour-science/colour#253]
Example code error found in main tutorial documentation:

Plotting the *sRGB* colourspace colour of *neutral 5 (.70 D)* patch.
```
patch_name = 'neutral 5 (.70 D)'
patch_spd = colour.COLOURCHECKERS_SPDS['ColorChecker N Ohta'][patch_name]
XYZ = colour.spectral_to_XYZ(patch_spd, cmfs, illuminant)
RGB = colour.XYZ_to_sRGB(XYZ / 100)

single_colour_plot(ColourParameter(patch_name.title(), RGB), text_size=32)
```

`ColourParameter` should be `colour_parameter`

**Comment by KelSolaar** [comment]
Thanks for spotting that!

It is quite surprising because I theoretically should have re-run the notebook (as I usually do) for [v0.3.7](https://github.com/colour-science/colour/tree/v0.3.7).

I'll fix that upon code review for v0.3.8!

**Comment by scooperly** [comment]
No problem, Its not my intention to be nit-picky about trivial things. I just figure its healthy to bring up any oddities I notice as I keep looking at the module. Hopefully I'll be fixing them myself soon enough :P

**Comment by KelSolaar** [comment]
> Its not my intention to be nit-picky about trivial things.

Well I'm glad you picked that one out actually! It is of the most importance that the tutorial works :]

**Comment by KelSolaar** [comment]
Actually, it should be the other way around! `colour_parameter ` has been changed to `ColourParameter ` in [v0.3.7](https://github.com/colour-science/colour/tree/v0.3.7).

> Remove colour.plotting.colour_parameter definition, colour.plotting.ColourParameter class should be used instead. (@kelsolaar)
