### ISSUE TITLE
About component conversion / transfer functions (OECF / EOCF) implementation.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#258]
First thing for the context two official definitions [1]:

> **additive RGB colour space**
> colorimetric colour space having three colour primaries (generally red, green and blue) such that CIE XYZ tristimulus values can be determined from the RGB colour space values by forming a weighted combination of the CIE XYZ tristimulus values for the individual colour primaries, where the weights are proportional to the radiometrically linear colour space values for the corresponding colour primaries
> 
> **NOTE 1** A simple linear matrix transformation can be used to transform between CIE XYZ tristimulus values and the 3×3 radiometrically linear colour space values for an additive RGB colour space.
> 
> **NOTE 2** Additive RGB colour spaces are defined by specifying the CIE chromaticity values for a set of additive RGB primaries and a colour space white point, together with a colour component transfer function.

> **colour component transfer function**
> single variable, monotonic mathematical function applied individually to one or more colour channels of a colour space
> 
> **NOTE 1** Colour component transfer functions are frequently used to account for the nonlinear response of a reference device and/or to improve the visual uniformity of a colour space.
> 
> **NOTE 2** Generally, colour component transfer functions will be nonlinear functions such as a power-law (i.e. “gamma”) function or a logarithmic function. However, in some cases a linear colour component transfer function may be used.

I'm not very happy with the way we have the conversion functions implemented at the moment : https://github.com/colour-science/colour/tree/develop/colour/models/rgb

It is not straightforward to get that right from an implementation and naming convention point of views and I'm touching that on a regular basis in an attempt to find the right implementation. I would be keen on doing it once for good instead of breaking stuff on a regular basis.

Right now the current implementation is roughly as follows:

![image](https://cloud.githubusercontent.com/assets/99779/13649566/3aa9ef56-e6a3-11e5-94f1-fc49a2a4ecdb.png)

What bothers me is the following:

- We don't have a proper *gamma* definition. Right now each RGB colourspace using own define it, code is just an exponentiation so no big deal  but I think it could be part of the `conversion_functions` package or elsewhere if we want to add functionality such as Gamma fitting, etc... later. As a matter of fact I needed to do that recently.
- The RGB colourspaces define their component transfer / conversion functions and occasionally some of them are exported to the generic `log` functions module such as *ACEScc*, *Alexa LOG C*. It was a poor attempt at consolidating camera vendors Log conversion functions in a single place.
- I see OECF and EOCF and the Log functions as two different subsets of colour component transfer functions thus I'm not entirely comfortable with our RGB colourspace specification defining those particular methods `RGB_Colourspace.OECF` and `RGB_Colourspace.EOCF` where one of them could be a Log function.
- I reckon that for example BT 709 OECF could live separated from Rec. 709 colourspace, similarly to BT 1886.

Considering the above I would like to re-implement the code in the following way:

![image](https://cloud.githubusercontent.com/assets/99779/13650640/7d2c65ca-e6a8-11e5-8223-36034f1ae296.png)

- The various component transfer / conversion functions (OECF and EOCF, Gamma, Log) would be implemented in their respective module / package. What slightly bothers me though doing that, is that this will separate things that work well as a singular entity: I'm thinking for example about the `aces` module which define all the requisites for the ACES encodings in a single place. However it will be more consistent.
- I would like to rename the OECF and EOCF methods to something more generic like ECCTF (ECCCF) / DCCTF (ECCCF) for *encoding component transfer / function* and *decoding component transfer / function*. I'm also debating about losing the capitalisation as it yields names such as `BT_1886_EOCF` which is a typical name for a class in python, maybe `BT_1886_eocf`. At same time, I also quite like the capitalisation too as we do for important names such as RGB, XYZ, etc...
- **I despise things like** `sRGB_to_linear`, thus I would like to rename the Log functions: instead of having `linear_to_cineon`, we would have something like `cineon_ECCTF` or `cineon_ecctf`.
- I would like to implement a generic `gamma` definition.

Quite keen on hearing your thoughts about that @MichaelMauderer, @KevinJW, @hpd, @scooperly,  @Nick-Shaw, @sobotka and whoever interested as this is a quite generic discussion that could be applied to other applications / packages.

References
---------------

1. ISO. (2004). INTERNATIONAL STANDARD Photography and graphic technology — image storage , manipulation and, 2004.

**Comment by MichaelMauderer** [comment]
Looks good!

I'm usually not a fan of big abbreviations as they are hard to decipher as a novice user.
How commonly used are the OECF and EOCF terms? Would a "encode" and "decode" do, too?

**Comment by KelSolaar** [comment]
> I'm usually not a fan of big abbreviations as they are hard to decipher as a novice user.

Me neither although I reckon it is an opportunity to make them aware of the terminology in the field.

> How commonly used are the OECF and EOCF terms?

It is quite widespread in ISO standards / ITU-R recommendations [1], [2], [3]. Poynton use the terms heavily in [4].

References
---------------

1. International Telecommunication Union. (2011). Recommendation ITU-R BT.1886 - Reference electro-optical transfer function for flat panel displays used in HDTV studio production BT Series Broadcasting service.
2. International Telecommunication Union. (2002). Parameter values for the HDTV standards for production and international programme exchange BT Series Broadcasting service. In Recommendation ITU-R BT.709-5 (Vol. 5, pp. 1–32). ISBN:9519982000
3. Miller, S., & Dolby Laboratories. (2014). A Perceptual EOTF for Extended Dynamic Range Imagery. Retrieved from https://www.smpte.org/sites/default/files/2014-05-06-EOTF-Miller-1-2-handout.pdf
4. Poynton, C. (2012). Digital Video and HD, Second Edition: Algorithms and Interfaces (2nd ed.). Elsevier / Morgan Kaufmann. ISBN:978-0123919267

> Would a "encode" and "decode" do, too?

It could work but I would be keen on trying to use the exact term, maybe a combination of both worlds? It has also the advantage of bringing back small case components on the names.

- `cineon_encoding_CCTF `
- `cineon_decoding_CCTF `
- `sRGB_COLOURSPACE.encoding_CCTF`
- `sRGB_COLOURSPACE.decoding_CCTF`
- `BT_1886_decoding_EOCF`

**Comment by Nick-Shaw** [comment]
> I personally don't see a problem in an E/OTF being a log function if that's the behavior of the encoding.

I don't see a problem either with the use of EOCF and OECF when referring to log coding. At least it keeps things consistent. I tend casually to refer to them all as Transfer Functions, but when using that it is necessary to specify the direction of the transform as to/from linear. Nuke has probably introduced a lot of confusion in people's minds by using the term "colorspace" in read/write nodes, when actually it refers only to the transfer function, and does not specify primaries.

EOCF and OECF are used commonly in the literature when referring to Rec.709, sRGB, BT.1886, ST2084 etc.  Camera manufacturers tend to refer simply to "curves" in their documentation, so I am not aware of any standard there.

Incidentally, not that it really matters, but ITU-R BT.709 is now at revision 6, so the revision 5 referenced is technically out of date. However, as far as I can tell, revision 6 is simply a "cleaning up" of the document, removing various references to obsolete standards, and analogue representations.

**Comment by KelSolaar** [comment]
Thanks all for the replies, good to hear all that!

> I'm not quite sure that I understand your desire for a more generalized term.

One of the reason is that camera vendors (as you stated it) pretty much don't use the OECF / EOCF terms, I will have to read back the various documents to confirm that. It also does not seem that common on the ICC side, coincidentally I came across this a few days ago: http://www.color.org/scene-referred.xalter

> NOTE 1 The ISO22028-3_RIMM-RGB-exCR.icc profile includes the nonlinear **color component transfer function (CCTF)** specified in ISO 22028-3. This **CCTF** provides for efficient quantization, and should be used whenever RIMM RGB files will be downsampled to 8-bits per channel. The linear_RIMM-RGB_v4.icc profile contains a linear **CCTF**. It should be used when a linear scene-referred encoding is desired, but only with 16 (or more) bits per channel.

> And to be honest the cineon_encoding_CCTF and cineon_decoding_CCTF don't look that bad.

Yup :)

> I tend casually to refer to them all as Transfer Functions, but when using that it is necessary to specify the direction of the transform as to/from linear.

We originally had `RGB_Colourspace.transfer_function` and `RGB_Colourspace.inverse_transfer_function` but as it wasn't clear about the direction I changed it for *OECF* / *EOCF*. 

> EOCF and OECF are used commonly in the literature when referring to Rec.709, sRGB, BT.1886, ST2084 etc.  Camera manufacturers tend to refer simply to "curves" in their documentation, so I am not aware of any standard there.

It is then maybe a case of cherry picking the appropriate name on a per domain basis as there is a bit of variation (and document it properly):

- ITU-R / SMPTE:  *OECF* / *EOCF*
- Camera Vendors: *encoding_curve* / *decoding_curve* or whatever is the most common term but *curve* seems appropriate considering the print film legacy).

and when we plug that into a `RGB_Colourspace` we use generic `RGB_Colourspace.encoding_CCTF` / `RGB_Colourspace.decoding_CCTF` methods.

> Nuke has probably introduced a lot of confusion in people's minds by using the term "colorspace" in read/write nodes, when actually it refers only to the transfer function, and does not specify primaries.

Yup agreed, a lot of people are bitten by that, Fusion does a better job at providing granular and explicit controls for that.

> I don't believe there is anything specifically making the OCIO transforms transfer only, but rather a convention in the default configuration.

I need to double check but I don't think that Nuke uses the OCIO configuration for that actually (it wasn't in the past for sure) but separated hardcoded functions that you can define in its `init.py` and are found in the LUT tab of the project settings.

**Comment by KelSolaar** [comment]
Getting back onto this, here is a visual proposal on what I have in mind:

![image](https://cloud.githubusercontent.com/assets/99779/14228568/63de9562-f96c-11e5-9585-e950229b56a9.png)

Let me know what you think about it and I'll implement that accordingly. The big difference with my previous post is that now that naming would be `oecf_sRGB` or `eocf_BT1886` to be in line with other API sub-packages naming convention (`bandpass_correction_Stearns1988`, `lightness_Glasser1958`, `luminance_ASTMD153508`).

**Comment by scooperly** [comment]
This looks just fine to me :)

**Comment by KelSolaar** [comment]
Great, thanks!
