### ISSUE TITLE
Investigate correctness of "colour.luminous_efficacy" definition.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#266]
I noticed that the `colour.luminous_efficacy` returns what Wikipedia labels *Luminous Efficiency*: Our definition returns a percentage while *Luminous Efficacy* has unit of lumen per watt (lm/W) and is essentially *Luminous Efficiency* multiplied by *K_m = 683*.

We may have discussed about this with @canavandl but I'll have to dig a bit.

References
---------------

- https://en.wikipedia.org/wiki/Luminous_efficacy

**Comment by canavandl** [comment]
That seems to be a bug. AFAIK `colour.luminous_efficacy` should be in lm/W. It'd be useful to have both efficacy and efficiency (the normalized efficacy) implementations though.

**Comment by KelSolaar** [comment]
Yes it was something like that I had in mind, will just need to triple check that Wikipedia has the right information.
