### ISSUE TITLE
Rename "ACES*" log encoding curves arguments.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#276]
References
-----------
https://github.com/ampas/aces-dev/commit/5f5280776738524b68557f16d558ac693acb5d99

**Comment by Nick-Shaw** [comment]
Of course AP1 already has a name – ACEScg. You could use that as the argument, i.e.
```def log_encoding_ACESproxy(ACEScg, bit_depth='10 Bit'):```
After all that's what the function is, an ACEScg to ACESproxy transform.

**Comment by KelSolaar** [comment]
Yeah, this issue is really just to get inline with the official ACES documentation and use the same names as possible.

**Comment by Nick-Shaw** [comment]
I would argue that they could also use the name `ACEScg` in the CTL files for ACES <> ACESproxy and ACES <> ACEScc. It's only a temp variable in the transform. They could even use the ACES_to_ACEScg function as part of the other transforms.
