### ISSUE TITLE
"sRGB" and "Rec. 709" colourspaces have different normalised primary matrices.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#282]
As of *Colour 0.3.8* and the various changes in the RGB colourspaces implementation, a defect was introduced:

*sRGB* colourspace is using *IEC 61966-2-1:1999* normalised primary matrix definition:

```python
sRGB_TO_XYZ_MATRIX = np.array(
    [[0.4124, 0.3576, 0.1805],
     [0.2126, 0.7152, 0.0722],
     [0.0193, 0.1192, 0.9505]])
```

while *Rec. 709* colourspace computes it directly:

```python
REC_709_TO_XYZ_MATRIX = normalised_primary_matrix(
    REC_709_PRIMARIES, REC_709_WHITEPOINT)
```
 
This creates discrepancies in the related computations.

The tricky aspect is that both approaches are valid: for example matching V-Gamut whitepaper computations requires the directly computed normalised primary matrix while matching official sRGB values requires using  *IEC 61966-2-1:1999* normalised primary matrix definition.

We need to find an elegant solution to that problem.

**Comment by Nick-Shaw** [comment]
At least in this instance the _IEC 61966-2-1:1999_ matrix is just the computed NPM rounded to four decimal places. It's more complex where the rounding happens earlier in a process, making subsequent values more inaccurate.

I guess that is what is happening in the V-Gamut white paper. The ACES matrix is given to six decimal places, but calculated using an NPM which has been previously rounded to four decimal places. Correct?

Scary how much of a discrepancy that can create.

**Comment by KelSolaar** [comment]
The V-Gamut white paper defines *V-Gamut* to *Rec. 709* as follows:

```
1.806576 -0.695697 -0.110879
-0.170090 1.305955 -0.135865
-0.025206 -0.154468 1.179674
```

Colour *V-Gamut* to *Rec. 709* yields:

```
1.8065736	-0.6956981	-0.1108786
-0.1700890	1.3059548	-0.1358648
-0.0252057	-0.1544678	1.1796737
```

and Colour *V-Gamut* to *sRGB* yields:

```
1.8063853	-0.6956147	-0.1109453
-0.1699311	1.3058387	-0.1358616
-0.0251630	-0.1544899	1.1797117
```

I'm thinking about implementing a switch attribute in the `colour.RGB_Colourspace` class that will force the computation of the NPM instead of using pre-defined values.

**Comment by KelSolaar** [comment]
The adopted behaviour on that particular issue will be as follow for now: BT.709 ([1]) doesn't specify a NPM, thus we will keep the current implementation that computes it from the primaries. In order to support the literature and whitepapers, the `colour.RGB_Colourspace` class will now be able to provide both initialisation and derived transformation matrices.

Reference
----------
[1] International Telecommunication Union. (2015). Recommendation ITU-R BT.709-6 - Parameter values for the HDTV standards for production and international programme exchange BT Series Broadcasting service (Vol. 5). Retrieved from https://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.709-6-201506-I!!PDF-E.pdf
