### ISSUE TITLE
Improve angles representation.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#286]
At the moment the API use a mix of degrees and radians as output of various definitions. Currently degrees seem to dominate with all the colour appearance models and most of the colour models are using them. Some definitions are outputting radians such as the coordinates transform, `colour.IPT_hue_angle`, etc...

I would be keen on tidying that up and push a regular usage of the coordinates transform definitions.

**Comment by KelSolaar** [comment]
I have started to cleanup our stuff in this branch: https://github.com/colour-science/colour/tree/feature/angles_representation

@MichaelMauderer, I'm tempted to create a definition to perform those degrees conversion calls in a nicer way:

`angle = np.degrees(np.arctan2(b, a)) % 360`

to maybe

`angle = colour.degrees((np.arctan2(b, a))` that would take care of the normalisation between 0 and 360.

**Comment by MichaelMauderer** [comment]
Would it make sense for this to be optional (i.e, use a optional parameter
to tell it whether to normalise or not)?
In cases where the difference between angles is needed it might be valuable
to have a normalised version.
Mixing `np.degree` and 'colour.degree' for that purpose might be confusing.

**Comment by KelSolaar** [comment]
Yes I was exactly thinking about that, question is do we make it `True` or `False` by default.

**Comment by MichaelMauderer** [comment]
The more consistent thing would probably be to make it `False` and treat it
as an extended version. (Maybe also propose the change upstream?).
But is that too much clutter again?

**Comment by KelSolaar** [comment]
Yeah that would almost defeat the purpose of trying to make things shorter. We can leave things as his too, explicit is probably safer than implicit.

**Comment by KelSolaar** [comment]
@MichaelMauderer: What do we do about `colour.IPT_hue_angle`, `colour.XYZ_to_LLAB`? I think those are the only definitions beside the coordinates transformations that output radians at the moment.

**Comment by MichaelMauderer** [comment]
Hm... I think this might also be an issue with other CAMs (but might not be implemented for all of them at this point).
I'm somewhat hesitant to change it from the original description, but then I am pretty sure those are fairly arbitrary anyway. Having it consistent might trump sticking to whatever was in the original paper.

**Comment by KevinJW** [comment]
in my copy of Color Appearance Models, 2nd ed p 249 discusses hue angles in degrees for LLAB.

Kevin

**Comment by KelSolaar** [comment]
Hue correlate *h_L* and final opponent signals *A_L* and *B_L* are also expressed in degrees in *Table 14.3 Example LLAB color appearance model calculations* of the third edition.
