### ISSUE TITLE
"LLAB(l:c)" colour appearance model unit tests are not being run.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#287]
I noticed that decorating two methods in `colour.appearance.tests.tests_llab.TestLLABColourAppearanceModel` class with `mock.patch` prevents the unit tests to run properly. I commented those and discovered that the first fixture test case is broken: hue angle *h_L* should be equal to 229.5 ([1]) but we compute 270.

References
-----------
[1] Fairchild, M. D. (2004). Color Appearance Models (2nd ed.). book, Wiley. ISBN:978-0470012161

**Comment by KelSolaar** [comment]
After digging quickly the discrepancy is explained by not using the 4 decimals rounded matrix, so we are in a very similar situation to the RGB colourspace where there is a choice between sticking to the literature or using numerically exact invert matrices. In that case however I didn't find the matrix to be explicitly specified.

**Comment by MichaelMauderer** [comment]
I think the rounding issue is why we introduced the mock environment: to ensure we use the rounding that was used to generate the fixture data.

I'll need to have a look why this causes the tests to not be run properly (and subsequently why we get the wrong angle)

**Comment by KelSolaar** [comment]
> I think the rounding issue is why we introduced the mock environment: to ensure we use the rounding that was used to generate the fixture data.

Yes, now reading back the *Notes* in the code it was for that exact reason:

```
        Notes
        -----
        Reference data was computed using a rounded
        :attr:`colour.appearance.llab.LLAB_RGB_TO_XYZ_MATRIX`, therefore a
        patched version is used for unit tests.
```

**Comment by MichaelMauderer** [comment]
Seems the issue was related to the generator method, which creates the tests from the fixture, being subclassed by a regular method, thus not behaving correctly.
I've moved the decorator into the method (using a `with` environment), and then yielding the tests from the parent method.
This runs all the tests and allows the rounded matrice to be used (thus passing the tests).
