### ISSUE TITLE
Investigate issues in "colour.single_spd_plot" tickers and scaling.

### ISSUE THREAD

**Issue by scoopxyz** [colour-science/colour#300]
I can't find a reason yet, but when plotting an SPD of shape (384.0, 780.0, 4.0) there are two issues arising.

First is an outright error:
`Locator attempting to generate 3961 ticks from 384.05 to 780.05: exceeds Locator.MAXTICKS`
Clearly an x-axis ticker issue, though I'm not seeing where this is being set. I would have assumed it would do auto scaling, the current solution is to set `x_ticker=False`. I am using a _qt4agg_ backend for matplotlib, not that that should matter.

Which then creates the second issue, a plot with zero height. The values of the SPD are normalized, so should be visible as is.
![figure_1](https://cloud.githubusercontent.com/assets/22137450/21082476/30cc934a-bf91-11e6-80d7-431cbda56c97.png)

**Comment by KelSolaar** [comment]
The following code works without issues:

```python
import colour
from colour.plotting import *

spd = colour.ones_spd(colour.SpectralShape(384.0, 780.0, 4.0))

single_spd_plot(spd)
```

![image](https://cloud.githubusercontent.com/assets/99779/21082696/9dd49b4a-c045-11e6-930d-0081319d3490.png)

Would you be able to share the spd (privately or altered form if you don't want it public)?

Cheers,

Thomas

**Comment by scoopxyz** [comment]
Odd, only after running your command did my unchanged code work. I'm going to try and run it in off a clean python environment to see if there might be some weird initialization stuff happening. Or if it was just a hiccup in my interpreter.

**Comment by KelSolaar** [comment]
Yeah please let me know, I haven't look at the code in a while but I think the spd should be aligned to the CMF for plotting anyway.

**Comment by scoopxyz** [comment]
I am not able to reproduce the error within a virtualenv, so this can probably me marked as closed.

**Comment by KelSolaar** [comment]
No worries, we can leave it open for now, let's check back in a few days.
