### ISSUE TITLE
Implement support for "Dolby ICTCP" colourspace.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#301]
References
-----------

- http://wwwen.zte.com.cn/endata/magazine/ztecommunications/2016/1/articles/201603/P020160311294995790791.pdf

**Comment by ValZapod** [comment]
BT.2100-2 (that is version 2) created HLG ICtCp matrix. I also updated Wikipedia for that new matrix https://en.wikipedia.org/wiki/ICtCp#Derivation (that is last matrix "in HLG:"). I will also recommend to check that all 3 (two for PQ and one new for HLG) inverted matrixes are correct to 15 decimal places as recommended by Series H Supplement 18 [*] https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-H.Sup18-201710-I!!PDF-E&type=items

[*] But you can just use WolframAlpha to get the very same matrix for PQ https://www.wolframalpha.com/input/?i=Inverse%5BSetPrecision%5B%7B%7B2048%2F4096.%2C+2048%2F4096.%2C+0%7D%2C+%7B6610%2F4096.%2C+-13613%2F4096.%2C7003%2F4096.%7D%2C+%7B17933%2F4096.%2C+-17390%2F4096.%2C+-543%2F4096.%7D%7D%2C+30%5D%5D 
or even matrix with absolute precision in integers
https://www.wolframalpha.com/input/?i=Inverse%5BSetPrecision%5B%7B%7B2048%2F4096.%2C+2048%2F4096.%2C+0%7D%2C+%7B6610%2F4096.%2C+-13613%2F4096.%2C7003%2F4096.%7D%2C+%7B17933%2F4096.%2C+-17390%2F4096.%2C+-543%2F4096.%7D%7D%2C+Inf%5D%5D

Also the module of values in 2x2 submatrix of that inverted matrix are the same if you did not recognize that. Very cool, right?
