### ISSUE TITLE
Increase the velocity of the calculations.

### ISSUE THREAD

**Issue by iCagarro** [colour-science/colour#302]
Hello,

I have been working with this library and I wonder if it is possible to increase the velocity of the calculations of the CRI, CQS or CCT, for example. I am using a certified software (LightMtrX) and it can perform a very fast calculation of the CRI, CCT, luminous flux or color coordinates, giving certified measures. However, this library is very useful for other routines, so it would be a very nice issue to solve.

Thank you.

**Comment by KelSolaar** [comment]
@iCagarro : The spectral code path is a bit computation heavy, it can be optimised but I wouldn't expect massive speedup as the codebase is using Python. Which CCT algorithm were you using? Ohno (2013)?

**Comment by iCagarro** [comment]
@KelSolaar I'm using the Robertson1968 because it is the CCT algorithm used in the calculation of the CRI. Maybe reducing the size of the matrix (reducing, in this way, the wavelength resolution) could help to reduce also the computation time.

**Comment by KelSolaar** [comment]
Ah yeah Robertson (1968) is not vectorised because not trivial to do so and has a slow _for_ loop. I might take a look at it though as it is planned somehow. That being said I suspect that the spectral code path is the culprit here.

**Comment by KelSolaar** [comment]
Confirming that the spectral code path is what slows things down, did a bit of optimisation (±30% faster) as per 6503cbf802109477dbcb2e86a92b60d2fcd81adf but it is obviously still very slow. I can probably shave some milliseconds here and there but nothing huge without a massive overhaul of the spectral code.

**Comment by KelSolaar** [comment]
Code in 2616fc88518746b55fa37be61fd93bd0aa4ab498 is 2 times faster than in https://github.com/colour-science/colour/tree/develop. I'll continue and report as I go.

**Comment by KelSolaar** [comment]
Code in aecfdc16aca8e857f387c205ef9c729f07c5f5ad is now ±5.8 times faster compared to https://github.com/colour-science/colour/tree/develop.

**Comment by KelSolaar** [comment]
`colour.colour_rendering_index` is now ±10.5 times / one order of magnitude faster!

**Comment by KelSolaar** [comment]
Summary as of d86d25542b71fcc2ae13de072911f3179193cd56:

| Object                              | Speed Increase (±) |
|-------------------------------------|--------------------|
| colour.SpectralPowerDistribution    |          6         |
| colour.TriSpectralPowerDistribution |          6         |
| colour.colour_rendering_index       |        10.5        |
| colour.colour_quality_scale         |        13.1        |
| colour.uv_to_CCT_Ohno2013           |        15.7        |

**Comment by iCagarro** [comment]
Very nice! I have just tried it and it works like a charm. Thank you for developing this piece of art and for your fast response.

**Comment by KelSolaar** [comment]
Thank you for the nice comments!

Be aware that if you were using the API before CRI and CQS output values are minorly different (contextually):

- [CQS Unit Tests - Changes](https://github.com/colour-science/colour/commit/d86d25542b71fcc2ae13de072911f3179193cd56#diff-ffe9b11c2ff9cedbbb3963c0ab614256)
- [CRI Unit Tests - Changes](https://github.com/colour-science/colour/commit/1ed8d28ae9ce9f82177e6e33cf6e0b6209d6f6d0#diff-15be1f74f718af59c2e1700a01b90fed)

There is a PR that should be merged into develop in the next days.
