### ISSUE TITLE
About moving the colour encodings to a dedicated sub-package.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#305]
I was maybe considering moving the following colour encodings functions to a dedicated sub-package to separate them from `colour.models`:

- `colour.RGB_to_YCbCr`
- `colour.YCbCr_to_RGB`
- `colour.RGB_to_YcCbcCrc`
- `colour.YcCbcCrc_to_RGB`
- `colour.RGB_to_ICTCP`
- `colour.ICTCP_to_RGB`

Maybe `colour.encodings`?

**Comment by KevinJW** [comment]
They are normally considered to be colour difference encodings,  encodings sounds a bit too generic?

**Comment by KelSolaar** [comment]
Yes agreed, I'm actually not sure it is a good idea.

For reference, at the moment the related modules are sitting in the `colour.models.rgb` sub-package and as I was trying to find some classifier names, I thought they weren't maybe located properly.

**Comment by KelSolaar** [comment]
I will postpone that for now and close the issue, it is not a big problem at the moment that they are located in the `colour.models.rgb` sub-package.
