### ISSUE TITLE
Implement support for "hdr-CIELab" and "hdr-IPT" colourspaces.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#306]
References
-----------

- http://www.ingentaconnect.com/content/ist/cic/2010/00002010/00000001/art00057?crawler=true
- https://www.youtube.com/watch?v=fjt7VHarVu4

**Comment by sobotka** [comment]
Was there any progress on the differing of values present in the HDR-IPT versus what Mr. Fairchild showed in his presentation?

**Comment by KelSolaar** [comment]
Hi Troy,

I think the original issue you are referring to is this one: https://github.com/colour-science/colour/issues/347.

We opened an issue in regard to Mark updated parameterisation here: https://github.com/colour-science/colour/issues/366

And the corresponding PR is here: https://github.com/colour-science/colour/pull/367

Voila!
