### ISSUE TITLE
Implement "Yoshi Ohno" correlated color temperature calculation method.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#31]

**Comment by veonua** [comment]
done? any link

**Comment by KelSolaar** [comment]
@veonua: Yes absolutely! The definitions you are looking at are as follows:

- `colour.uv_to_CCT_Ohno2013`
- `colour.CCT_to_uv_Ohno2013`

``` python
>>> colour.uv_to_CCT_Ohno2013([0.1978, 0.3122])
array([  6.50751282e+03,   3.22335875e-03])
>>> colour.CCT_to_uv_Ohno2013(6.50751282e+03, 3.22335875e-03)
array([ 0.19779976,  0.31219969])
```

Yoshi Ohno has updated his reference implementation though, so we need to integrate the latest as per #285.
