### ISSUE TITLE
Change "L_B" and "L_W" default argument values for "BT.1886" eotf.

### ISSUE THREAD

**Issue by Nick-Shaw** [colour-science/colour#312]
Current default values are 64 and 940, i.e. 10-bit black and white code values. L_B and L_W should be screen luminance in cd/m^2 if the function is to return absolute luminance, or e.g. 0 and 1 to return normalised values.

**Comment by KelSolaar** [comment]
@Nick-Shaw : Do you want to tackle that, I can do it too, I don't mind either way.

**Comment by Nick-Shaw** [comment]
Probably easier and quicker for you to do it, if you don't mind

**Comment by KelSolaar** [comment]
No problem at all!
