### ISSUE TITLE
Handle interpolation code changes introduced with "Scipy" 0.19.0.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#313]
[Scipy 0.19.0](https://github.com/scipy/scipy/blob/master/doc/release/0.19.0-notes.rst#other-changes) introduced backward compatible breaking changes in `scipy.interpolate.interp1d` definition, as a result [our builds are breaking](https://travis-ci.org/colour-science/colour/builds/213341301).

We need to take a look on how to handle that properly.

**Comment by MichaelMauderer** [comment]
Would it be acceptable to reduce the significant digits we use for testing? It seems that this mostly affects the last one or two we look at. Not nice but it might also protect us in the future from similar changes.

Not sure that solves issues with doc strings, though, which we probably still would have to modify all u hand at this point.

**Comment by MichaelMauderer** [comment]
Also an interim solution: what about specifying the version that does not yet include this change for our tests?

**Comment by KelSolaar** [comment]
> Not sure that solves issues with doc strings, though, which we probably still would have to modify all u hand at this point.

Yeah it is the big issue at play here, we might have to update a lot of stuff, I'm not against it though but it is not very elegant, maybe we can annotate the code areas we lower the precision and go back to them with full precision once we elect having Scipy 0.19.0 as the minimal version?

> what about specifying the version that does not yet include this change for our tests?

It might be only very temporary, any update of conda will likely break Colour again.

**Comment by KelSolaar** [comment]
I went for the interim solution, this is going to be annoying but at least we have some headroom to continue working now.
