### ISSUE TITLE
Improve "Canon Log" and "Panasonic V-Log" implementations and consistency

### ISSUE THREAD

**Issue by Nick-Shaw** [colour-science/colour#343]
Following on from #336 and the changes implemented in PR #338 for "Sony S-Log", it would improve consistency if the same things were done for "Canon Log" and "Panasonic V-Log".

Like the Sony documentation, both Canon and Panasonic show tables in their documents which give equivalents of 0%, 18% and 90% reflectance as both IRE(%) and 10-bit code values. With ALEXALogC, for example, where 18% reflectance is coded as 10-bit code value 400 (in a 10-bit decode of an ARRIRAW image of a grey card) the IRE(%) on the SDI output of the camera is simply `100 * 400/1023 = 39.1`. For V-Log, the Panasonic table shows 128 as the 10-bit code value for black, and 7.3% as the IRE. To get 7.3% you need to do `100 * legal_to_full(128/1023)`.

Therefore I suggest that both Canon and Panasonic log encoding functions should include `out_legal=True` kwargs and `in_legal=True` for the decoding functions. Defaulting to `True` for these would give a result matching the manufacturer supplied IDTs.

While there could be an argument for including full/legal switches for all the transfer functions, to allow for results matching the code values on the SDI outputs of the cameras, in reality I do not believe that either RED or ARRI log material is ever stored or processed in this form. RED and ARRI SDKs produce raw decodes matching full range, and (almost) all ProRes decoders incorporate a legal_to_full scale, hidden from the user, so raw and ProRes recordings match.

For Canon there is an additional issue. Like Sony, Canon refer to 18% reflectance as 20% 'linear IRE'. Therefore, for example, the `CanonLog3_to_linear` function in the IDT requires its output to be multiplied by 0.9 to return 0.18 instead of 0.2 for the Canon Log 3 coding of mid grey. I suggest that the same `out_reflection=True` kwarg as has been added to the Sony functions should also be added for Canon. Currently to match the ACES IDT linearisation, the following is required: `0.9 * log_decoding_CanonLog3( ( y * 1023 - 64 ) / 876 )`, since the current `log_decoding_CanonLog3` function implements only the `CanonLog3 IRE to Linear` subfunction from the IDT.

The fact that the output of the Canon Log encoding functions is 'IRE' (in the common video levels sense, rather than the obtuse 'linear IRE' sense, used confusingly in the same Canon and Sony documents) and should be converted to code value using a full to legal scale is noted in the current docstring, but the 0.9 'reflectance factor' is not.

**Comment by KelSolaar** [comment]
Thanks @Nick-Shaw, that is great! I'll work on that after the Sony jazz.

**Comment by Nick-Shaw** [comment]
It may be worth noting that Lattice has added a "Canon Log (not scaled)" option in the latest update "for C100 Mk2 and C300 Mk 1", presumably to handle similar issues. See https://github.com/videovillage/Lattice-Issues/issues/69

**Comment by KelSolaar** [comment]
Thanks! I will come to that issue in a not too far future, I have started addressing the various transfer functions recent issues and this one should be part of the batch.
