### ISSUE TITLE
Discrepancy with "Michaelis-Menten" "epsilon" calculation for "hdr-IPT"?

### ISSUE THREAD

**Issue by sobotka** [colour-science/colour#347]
In Fairchild's [Brightness, Lightness, and Specifying Color in High-Dynamic-Range Scenes and Images](https://pdfs.semanticscholar.org/1c83/520be9486ebdcdfa597108e983bca16f3f2f.pdf)[PDF] page 8, it lists a different calculation for the MM exponent value when compared with https://github.com/colour-science/colour/blob/master/colour/models/hdr_ipt.py#L148.

The formula is listed as e=  0.59 / (sf • lf ), whereas in hdr_ipt.py it is defined as epsilon = 1.38 * sf * lf.

Which version is correct?

**Comment by KelSolaar** [comment]
Colour uses the parameterisation as it appears in [1]:

![image](https://user-images.githubusercontent.com/99779/30532800-3fa030d8-9caa-11e7-9494-7397147e991d.png)

I haven't read the paper you link, but it seems to bring improvement on hdr-IPT, so we might want to integrate that with arguments to the definition or another way.

References
---
1. Fairchild, M. D., & Wyble, D. R. (2010). hdr-CIELAB and hdr-IPT: Simple Models for Describing the Color of High-Dynamic-Range and Wide-Color-Gamut Images. In Proc. of Color and Imaging Conference (pp. 322–326). ISBN:9781629932156
