### ISSUE TITLE
Implement support for "SMPTE 240M" transfer function.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#349]
References
---
- http://car.france3.mars.free.fr/HD/INA-%2026%20jan%2006/SMPTE%20normes%20et%20confs/s240m.pdf

**Comment by Nick-Shaw** [comment]
The 2nd edition of Poynton appears not to give the SMPTE-240M OETF. Page 322 says "For details, refer to the first edition of this book." The OETF and EOTF are given in http://car.france3.mars.free.fr/HD/INA-%2026%20jan%2006/SMPTE%20normes%20et%20confs/s240m.pdf, which is the reference I used in `ycbcr.py` for the luma coefficients.

**Comment by KelSolaar** [comment]
I found it in his book on Google Books when searching for the parameterization, I did not notice it was in the first edition. Thanks! I'll update the issue accordingly.
