### ISSUE TITLE
Consider adding a "float" option for the "BT.2020" OETF and EOTF.

### ISSUE THREAD

**Issue by Nick-Shaw** [colour-science/colour#356]
`bt_2020.py` includes the kwarg `is_12_bits_system` to change the alpha and beta constants used in the OETF. These were the only two values given in the original BT.2020 spec. But the 2015 update (which is the reference given) mentions that those three and four decimal place versions of the constants are sufficient "for practical purpose [sic]". I take that to mean that at the specific bit depth the curve will appear to be continuous. But the precise values which will make the curve continuous in float are also given.

Should these values also be an option? The boolean `is_12_bits_system` kwarg obviously can't handle three possibilities, but an additional `is_float` kwarg creates the possibility of ambiguity. What would be the best way of handling this while preserving backwards compatibility?

**Comment by KelSolaar** [comment]
I don't mind updating the signature for something that would allow us to use the α = 1.09929682680944 and β = 0.018053968510807 constants. 

For reference we changed it there already: https://github.com/colour-science/colour/commit/dc4efa9c83d08f7b783d2310567d8843b4c09ff8

Now and for knowledge purposes, it is dangerous but you can leverage the `None` keyword to have tri-state. You however need to do perform exact comparisons: `if not is_12_bits_system` yields same value than `if is_12_bits_system is None` or `if is_12_bits_system is False`. While it is fine to use that in the private API, I'm reluctant to do it on the public API.

**Comment by KelSolaar** [comment]
@Nick-Shaw : We would have to account for those changes in `colour.RGB_to_YcCbcCrc` and `colour.YcCbcCrc_to_RGB` definitions too.
