### ISSUE TITLE
About Visible Spectrum Volume Boundaries.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#381]
I'm starting a thread in regard to https://stackoverflow.com/a/48396021/931625 as we will hit comments limit there.

I'm assuming @nschloe is author of the question and the snippet being discussed is as follows:

``` python
import colour
import numpy as np


def generate_square_waves(samples):
    square_waves = []
    square_waves_basis = np.tril(np.ones((samples, samples)))[0:-1, :]
    for i in range(samples):
        square_waves.append(np.roll(square_waves_basis, i))
    return np.vstack((np.zeros(samples), np.vstack(square_waves),
                    np.ones(samples)))


def XYZ_outer_surface(samples):
    XYZ = []
    wavelengths = np.linspace(colour.DEFAULT_SPECTRAL_SHAPE.start,
                            colour.DEFAULT_SPECTRAL_SHAPE.end, samples)

    for wave in generate_square_waves(samples):
        spd = colour.SpectralPowerDistribution(
            wave, wavelengths, interpolator=colour.LinearInterpolator).align(
                colour.DEFAULT_SPECTRAL_SHAPE)
        XYZ.append(colour.spectral_to_XYZ(spd))

    return np.array(XYZ).reshape(len(XYZ), -1, 3)


# 43 is picked as number of samples to have integer wavelengths.
colour.write_image(XYZ_outer_surface(43), 'CIE_XYZ_outer_surface.exr')
```

The output image is here: https://drive.google.com/file/d/1GScSAMyyljDQGvZqUWluix9n9fy66NNs/view?usp=sharing

**Comment by nschloe** [comment]
What I'm getting here is
```
Traceback (most recent call last):
  File "b.py", line 29, in <module>
    colour.write_image(XYZ_outer_surface(43), 'CIE_XYZ_outer_surface.exr')
  File "b.py", line 21, in XYZ_outer_surface
    wave, wavelengths, interpolator=colour.LinearInterpolator).align(
TypeError: __init__() got an unexpected keyword argument 'interpolator'
```
This is with
```
$ python3 -c "import colour; print(colour.__version__)"
0.3.10
```

**Comment by KelSolaar** [comment]
This is my fault, I should have mentioned that the code is using latest [develop](https://github.com/colour-science/colour/tree/develop) branch. We have changed the whole spectral computations backend and there are some backward incompatible changes.

I could adjust the code for v0.3.10 if convenient for you though?

**Comment by nschloe** [comment]
Let me just grad develop and try it out.

**Comment by nschloe** [comment]
Alright, same result: exrdisplay shows
![w](https://user-images.githubusercontent.com/181628/35829823-6d8878d8-0ac4-11e8-9042-fc2379b8ecb8.png)
Perhaps I should you another viewer?

**Comment by KelSolaar** [comment]
Oh right, this is the expected output, it is essentially a one pixel width image storing all the XYZ coordinates. I have used that because I can load it in [The Foundry Nuke](https://www.foundry.com/products/nuke) easily and it was more convenient to illustrate the SO thread than pushing data in MPL or Plot.ly.

Here is a Plot.ly example: https://plot.ly/~KelSolaar/91 and the generating code:

``` python
import plotly.plotly as py
import plotly.graph_objs as go

# From above "XYZ_outer_surface" definition.
XYZ = XYZ_outer_surface(43)

X, Y, Z = colour.utilities.tsplit(XYZ)
trace = go.Scatter3d(x=X, y=Y, z=Z)

data = [trace]
layout = go.Layout(margin=dict(l=0, r=0, b=0, t=0))
figure = go.Figure(data=data, layout=layout)
py.iplot(figure, filename='Visible Spectrum Volume Boundaries')

```

**Comment by nschloe** [comment]
Alright, I think I get it now. Here's an image of a small test code I wrote:
![d](https://user-images.githubusercontent.com/181628/35830374-516b36ac-0ac6-11e8-8aaf-5c192045f946.png)
One generates "block spectra" which are 0 everywhere except in a certain range of wavelengths, and computed the XYZ coordinates of that. The value of the block is simply set _some_ constant, e.g., 1; it doesn't really matter for the shape.

I'm wondering now what the significance of that shape is at all. I mean, the fact that one sets the limit to 1 doesn't really constitute something physical, right? I could easily just crank up some wavelengths here and there, and bam, the blob expands. Eventually there's be some cone saturation, but that's perhaps dependent on the cone type; I don't know.

**Comment by KelSolaar** [comment]
> I mean, the fact that one sets the limit to 1 doesn't really constitute something physical, right?

As discussed on SO, it is a normalisation process, so you could scale the volume uniformly ideally.

> I could easily just crank up some wavelengths here and there, and bam, the blob expands.

Yes although it would not yield a very useful volume representation! :)

**Comment by nschloe** [comment]
Yes, I guess you just scale the thing such that the full spectrum maps to [100,100,100]. Fair enough.

Let me say thanks _very_ much for the discussion! This really enhanced my understanding of color theory.

**Comment by KelSolaar** [comment]
You are very much welcome!

**Comment by KelSolaar** [comment]
Oh and before I forget if you are happy about the SO answer, would you mind accepting it please? 

Cheers,

Thomas

**Comment by nschloe** [comment]
> Oh and before I forget if you are happy about the SO answer, would you mind accepting it please?

Yeah, sure. Before that, it probably needs some cleaning up, and give the answer, too. :) For example:

> The upper boundary is the result of CIE Y, the central Colour Matching Function of the CIE 1931 2 Degree Standard Observer being normalised to 1.

I don't think this is true, is it? The maximum of CIE Y is 1 alright, but even if the functions were scaled in any other way, the shape would come up. It is rather a consequence of the fact that one restricts oneself to two values in the spectrum, 0 and alpha (where alpha is arbitrarily chosen), right?

Also, the answer should probably mention that "gamut of visible colors" is a bit of a misnomer. It's the gamut of colors generated by spectra with a certain maximum value.

All this is more or less mentioned in the section _Outer Surface Generation_ of the answer. This part should probably be moved to the beginning of the reply.

**Comment by nschloe** [comment]
Ah, I think now I understood something else: The visible gamut is the visible gamut _under a particular illuminant!_ Taking as "arbitrary" reference spectrum of all ones, corresponding to a perfectly white object, the integral
```
∫_360nm^830nm observer(λ) illumination(λ) dλ
```
will give you the "whitest" color possible – under that illuminant. You're not just feeding square spectra into the observer, but chunks of the illuminant.

Setting the illuminant to 1, as we have to so far, is essentially equivalent to picking the rarely used E illuminant.

**Comment by KelSolaar** [comment]
> I don't think this is true, is it? The maximum of CIE Y is 1 alright, but even if the functions were scaled in any other way, the shape would come up. It is rather a consequence of the fact that one restricts oneself to two values in the spectrum, 0 and alpha (where alpha is arbitrarily chosen), right?

Yes, I need to reformulate that part to account for the whole surface not just the upper limit, I originally did not understand what you were originally looking for.

**Comment by KelSolaar** [comment]
> The visible gamut is the visible gamut under a particular illuminant!

Not really under a particular illuminant but under the Equal Energy illuminant which have constant radiant power.

The [CIE definition](http://eilv.cie.co.at/term/236) where every word is important is actually as follows:

**The colour matching functions are the tristimulus values of monochromatic stimuli of equal radiant power.**

It is the first sentence of our dedicated (not-up-to-date) notebook here: https://github.com/colour-science/colour-notebooks/blob/master/notebooks/colorimetry/cmfs.ipynb

There is an important but critical subtlety when you compute the tristimulus values XYZ of a sample, the **illuminant** part is actually the illuminant S under which you are viewing the sample, it is independent of the CMFS:

![image](https://user-images.githubusercontent.com/99779/35880031-a38f0302-0be1-11e8-89c6-e3e1946ba9ff.png)

Notice that there is no parameterisation _to include an hypothetical illuminant under which the CMFS would have been measured_, they are _pure_. You can replace them with camera sensor sensitivities and still not have to include any illuminant during the measurement conditions for the sensitivities.

This is the reason I was saying "crank(ing) up some wavelengths here and there" would not be useful because you would be artificially increasing HVS sensitivity at some particular wavelengths.

This page has some really interesting further reading on how the CMFS were derived through colour matching experiments by Wright & Guild following Maxwell work: http://www.handprint.com/HP/WCL/color6.html

**Comment by nschloe** [comment]
Thanks again for the replies. I think we're on the same page now.

>> The visible gamut is the visible gamut under a particular illuminant!
>
>Not really under a particular illuminant but under the Equal Energy illuminant which have constant radiant power.

Alright. What I meant to say is: It doesn't make sense to speak of the visible gamut _per se_, but only with an illuminant; equal energy, D65, pick your poison. That illuminant then shines upon the object to consider, and it reflects the wavelengths more or less well (β(λ)).

> The colour matching functions are the tristimulus values of monochromatic stimuli of equal radiant power.

"Equal radiant power" actually means I can pick and, because at the end of the day they are all normalized by `Y_W=100`, right?

> Notice that there is no parameterisation to include an hypothetical illuminant under which the CMFS would have been measured, they are pure.

I don't know what that wants to say.

> This page has some really interesting further reading on how the CMFS were derived through colour matching experiments by Wright & Guild following Maxwell work: http://www.handprint.com/HP/WCL/color6.html

Looks super interesting, thanks for the hint!

**Comment by KelSolaar** [comment]
> It doesn't make sense to speak of the visible gamut per se

We are probably entering the meta-discussion stage here. The way I see it is as follows, the HVS is a sensory system whose purpose is to measure something thus there is an envelope to the extent of what it is capable of measuring. The visible gamut represents the envelope for an event that would stimulate the sensor fully. It is obviously more complex because the envelope is relative and we don't account for saturation, etc...

> I don't know what that wants to say.

What I was trying to say is that when you use the CMFS, you don't care about the conditions under which they were assembled and put together. They are pure in that they are self-contained like a blackbox and you don't have any parameter to change the way they measure radiant energy. A parallel would be a thermometer, in order to use one, you don't need knowledge of how it was assembled and you don't have hooks to tweak the way it measure temperature, it simply measure it.

Does it make sense?

**Comment by nschloe** [comment]
> Does it make sense?

Sure, feel free to close this one. For your extraordinary effort, I've awarded a 100 points bounty on stackoverflow. Thank you again!

**Comment by KelSolaar** [comment]
Thanks @nschloe, this is much appreciated!
