### ISSUE TITLE
Improvements to CIECAM02.

### ISSUE THREAD

**Issue by nschloe** [colour-science/colour#383]
I recently implemented CIECAM02 (and CAM16) and found some improvements. colour could also profit from it. Check out https://arxiv.org/pdf/1802.06067.pdf?fname=cm&font=TypeI, in particular page 3, or its implementation in colorio https://github.com/nschloe/colorio/blob/master/colorio/ciecam02.py.

**Comment by KelSolaar** [comment]
That looks great @nschloe! I think it would be worth contacting the authors about it. We are usually not integrating anything that is not coming from _official_ literature though but will definitely keep an eye on it.

**Comment by nschloe** [comment]
Yeah well I _am_ the author. Just a quick write-up right there.

**Comment by KelSolaar** [comment]
Oh I was referring to the CAM16 authors :)

**Comment by nschloe** [comment]
Ah yes. Okay, let's try to get officially endorsed. :)

**Comment by KelSolaar** [comment]
That would be great!

**Comment by KelSolaar** [comment]
@nschloe : Any news on this front?

**Comment by nschloe** [comment]
Uh... What exactly do you have in mind? I wrote the authors and got

>  Thank you for sending us your note to CAM16. We will study your note and do hope your implementation of the CAM16 can make the CAM16 more robust.

back from Changjun Li (in Feb 2018).

**Comment by KelSolaar** [comment]
Fair enough! Your last comment was:

> Ah yes. Okay, let's try to get officially endorsed. :)

So I was just inquiring if there were any progress.

**Comment by nschloe** [comment]
Yeah, I mean, it'd be nice if this was used by upstream since the standard is a bit flawed here and there, but I cannot _make_ anyone use it. At least the ideas are out there for everyone to implement.

And besides, I'm working on a color model that will perhaps obsolete all of CAM ones anyway. :smile: 

https://github.com/nschloe/colorio/commit/eedda66bf06826ba656969fd979516df9aac9069

**Comment by KelSolaar** [comment]
Ah! :)

Thanks, I will close this one to tidy up our stack a bit!

**Comment by nschloe** [comment]
I wouldn't close this before having made the respective changes, e.g., [here](https://github.com/colour-science/colour/blob/a3e7182d6a991beecd7162dd8ba891b556d79732/colour/appearance/ciecam02.py#L847).
