### ISSUE TITLE
[help] How can i find out a color's dominant wavelength?

### ISSUE THREAD

**Issue by Edwardlin-zlt** [colour-science/colour#386]
since I've got a color's CIE-XYZ coordinate, and I try to find out its dominant wavelength.
can I achieve that by this module?

**Comment by Ron024** [comment]
Yes, please see dominant wavelength.
<https://colour.readthedocs.io/en/latest/generated/colour.dominant_wavelength.html#colour.dominant_wavelength>

**Comment by KelSolaar** [comment]
Hi @Edwardlin-zlt,

Yes, as @Ron024 said this is performed with the definition he linked. Typical usage, taken from the README.rst file is as follows:

``` python
>>> import colour
>>> xy = [0.26415, 0.37770]
>>> xy_n = [0.31270, 0.32900]
>>> colour.dominant_wavelength(xy, xy_n)
(array(504.0),
 array([ 0.00369694,  0.63895775]),
 array([ 0.00369694,  0.63895775]))
```

**Comment by Edwardlin-zlt** [comment]
Thanks~
You guys done a wonderful job~

**Comment by KelSolaar** [comment]
Cheers and you are welcome @Edwardlin-zlt !
