### ISSUE TITLE
Change "DCI-P3" colourspace CCTFs to "Gamma 2.6" and implement support for "DCDM XYZ" colourspace.

### ISSUE THREAD

**Issue by codycuellar** [colour-science/colour#399]
The current P3-DCI colourspace utilizes the CCTFs that are actually defined for DCDM X'Y'Z'. The P3-DCI RGB colourspace is defined as having RGB encoding/decoding functions of gamma 2.6. The current EOTF and OETF should be moved and renamed to a different module (possibly DCDM_XYZ), and the P3-DCI colourspace should implement gamma 2.6.

Here's an example of usage that would make a little more sense (using a proposed DCDM_XYZ colourspace):

```python
>>> RGB = [.5, .5, .5]
>>> wp = P3.whitepoint
>>> XYZ_trisitim = colour.RGB_to_XYZ(RGB, wp, wp, P3.RGB_to_XYZ_matrix,
... decoding_cctf=P3.decoding_cctf)
>>> XYZ_tristim = XYZ_tristim * 48
>>> XYZ_tristim
array([ 7.08248691,  7.91704746,  7.55615641])
>>> XYZ_prime = DCDM_XYZ.encoding_cctf(XYZ_tristim)
>>> (XYZ_prime * 4095).round()
array([ 1897.,  1980.,  1945.])
```

The proposed DCDM_XYZ colourspace would have primaries [[1, 0], [0, 1], [0, 0]], whitepoint [1/3, 1/3], and CCTFs which are currently in the P3-DCI transfer functions. It would probably make more sense if those CCTFs returned normalized floats as well as demonstrated in the proposed code usage above.

**Comment by KelSolaar** [comment]
Thanks @codycuellar, totally makes sense!

**Comment by KelSolaar** [comment]
@codycuellar: It should be in develop branch!
