### ISSUE TITLE
"Edit on Github" button in documentation yields a 404 error.

### ISSUE THREAD

**Issue by sobotka** [colour-science/colour#407]
http://colour.readthedocs.io/en/develop/_modules/colour/models/jzazbz.html

Hit "Edit on Github" 404s.

**Comment by KelSolaar** [comment]
@sobotka : Thanks, I don't think we have ever written the `_modules` RST files containing the code anywhere, seems like this button should not exist when looking at the source code from the documentation. Will probably look on how to disable it.

**Comment by KelSolaar** [comment]
`html_show_sourcelink = False` this option set in the `conf.py` file will remove the button although I guess we want to keep it for actual and maintained documentation files.

**Comment by KelSolaar** [comment]
More information: https://github.com/sphinx-doc/sphinx/issues/2386

**Comment by KelSolaar** [comment]
I think this one was addressed, I cannot see the `Edit on Github` button on the aforementioned page.
