### ISSUE TITLE
Incorrect computation results of "CAM16".

### ISSUE THREAD

**Issue by crowsonkb** [colour-science/colour#411]
When I do the following in CAM16:

```python3
white = colour.sRGB_to_XYZ([1, 1, 1]) * 100
cam = colour.XYZ_to_CAM16(white, white, 16, 16, discount_illuminant=True)
```

the output has high C/M/s (C = ~18). Meanwhile for CIECAM02 C is very low and it goes to zero when `discount_illuminant` is set to True. `discount_illuminant` does not fix this issue with CAM16—C of pure white is still ~18!

Admittedly I don't know whether CAM16 is *supposed* to behave this way, but it looks to be wrong behavior to me.

**Comment by KelSolaar** [comment]
Hi @crowsonkb,

It is on my radar and I think our implementation is broken, I asked authors data to verify our computations but I never got an answer. I'll take a look again.

Cheers,

Thonas

**Comment by KelSolaar** [comment]
I think I found out, https://github.com/colour-science/colour/blob/develop/colour/appearance/cam16.py#L235:

```
D_RGB = D[..., np.newaxis] * XYZ_w / RGB_w + 1 - D[..., np.newaxis]
```

should be

```
D_RGB = D * Y_w / RGB_w + 1 - D
```

`XYZ_w` must be changed to `Y_w`, I'll check further but this gets results that are consistent:

```
CIECAM02_Specification(J=100.0, C=2.8259607028183682, h=210.76534506431318, s=11.608898983500501, Q=169.89280036673421, M=2.2895864130356429, H=267.59062692194436, HC=None)
CAM16_Specification(J=100.0, C=2.7618799602055351, h=209.55362378666368, s=11.476085011439855, Q=169.90580073425403, M=2.2376683529305423, H=266.02364589844717, HC=None)
```

while before:

```
CAM16_Specification(J=100.0, C=18.073707151949172, h=210.21954480227944, s=29.502003599285754, Q=168.24227746334171, M=14.643273095417717, H=266.8859454560166, HC=None)
```

**Comment by crowsonkb** [comment]
Making this change fixed the problem for me, and I get C ~1e-12 now when setting `discount_illuminant` to True.

**Comment by KelSolaar** [comment]
Excellent! I'll push a change to `develop` very soon.

**Comment by KelSolaar** [comment]
@crowsonkb: It is in `develop` as of now! Thanks Katherine.
