### ISSUE TITLE
Controlling the annotation arrows of "colour.plotting.diagrams.spds_chromaticity_diagram_plot" definition.

### ISSUE THREAD

**Issue by Floschoe** [colour-science/colour#414]
When creating a plot for the standard 'D' illuminants the arrows overlap each other without an option to control them. Adding a way to control them would be marvelous.
![grafik](https://user-images.githubusercontent.com/33455817/40412448-a7c8b83e-5e73-11e8-889b-1ebcf4bc257d.png)

**Comment by KelSolaar** [comment]
Thanks @Floschoe, I will expose some controls!

**Comment by KelSolaar** [comment]
So I have pushed an update in the [feature/v0.3.12 branch](https://github.com/colour-science/colour/commit/b9a01dd0745159443555dc2d325d6b2789646264):

```
import colour.plotting
from colour import ILLUMINANTS_SPDS

D50 = ILLUMINANTS_SPDS['D50']
D55 = ILLUMINANTS_SPDS['D55']
D60 = ILLUMINANTS_SPDS['D60']
D65 = ILLUMINANTS_SPDS['D65']
D75 = ILLUMINANTS_SPDS['D75']

colour.plotting.spds_chromaticity_diagram_plot_CIE1931(
    [D50, D55, D60, D65, D75],
    annotate_parameters={
        'xytext': (-100, 75),
        'textcoords': 'offset points',
        'arrowprops': {
            'arrowstyle': '->',
            'connectionstyle': 'arc3, rad=-0.25'
        }
    })

colour.plotting.spds_chromaticity_diagram_plot_CIE1931(
    [D50, D55, D60, D65, D75],
    annotate_parameters=[{
        'annotate': False,
    }, {
        'xytext': (100, 75),
    }, {
        'xytext': (75, -100),
        'arrowprops': {
            'arrowstyle': '-|>'
        }
    }, {
        'xytext': (-75, 100),
        'arrowprops': {
            'arrowstyle': 'fancy'
        }
    }, {
        'xytext': (-100, -75),
    }])
```

![image](https://user-images.githubusercontent.com/99779/40417227-621290b6-5ed3-11e8-8461-75549d1ea71e.png)

![image](https://user-images.githubusercontent.com/99779/40417240-67d8869a-5ed3-11e8-9aa8-8a45ca3eec7b.png)

**Comment by KelSolaar** [comment]
I forgot to precise that `annotate_parameters` feed that definition: https://matplotlib.org/api/_as_gen/matplotlib.pyplot.annotate.html
