### ISSUE TITLE
"colour.plotting.*_spd_colour_rendering_index_bars_plot" definitions show negative individual colour rendering as positive value.

### ISSUE THREAD

**Issue by LaszloBalazs** [colour-science/colour#416]
There is a contradiction between calculated and plotted individual colour rendering index:
This is my test code:
import colour
import colour.plotting as cp
from colour import (ILLUMINANTS_RELATIVE_SPDS)
illuminant = ILLUMINANTS_RELATIVE_SPDS['F2']
a = colour.colour_rendering_index(illuminant, additional_data="True")
print(a.Q_as[9][1]) # The output is -83.9 which is correct
cp.single_spd_colour_rendering_index_bars_plot(illuminant) # The Q9 value is  +83.9, which is false

The same issue may be with cp.multi_spd_colour_rendering_index_bars_plot

I would suggest to use a patterned bar for negative value to keep the y axis scale between 0-100 but make sure the negative value pops out. Also the number above the bar should show the negative sign.

**Comment by KelSolaar** [comment]
Sorry for the delay @LaszloBalazs.

Here we go!

![image](https://user-images.githubusercontent.com/99779/41525661-e2532ef4-7335-11e8-97e5-1a04912a7bd6.png)
