### ISSUE TITLE
Should "oetf_DCDM" be called "eotf_reverse_DCDM"?

### ISSUE THREAD

**Issue by nick-shaw** [colour-science/colour#420]
https://github.com/colour-science/colour/blob/aee956f9f386e1ca8f7e5ed470025440534dbd4f/colour/models/rgb/transfer_functions/dcdm.py#L42
For consistency with e.g. BT.1886 and BT.2100, this should probably be referred to as a reverse EOTF. DCI spec does not define an OETF (AFAIK) as it is a display specification.

**Comment by KelSolaar** [comment]
Yup!

**Comment by KelSolaar** [comment]
Yes!
