### ISSUE TITLE
Iridas .cube writer always writes domain attribute.

### ISSUE THREAD

**Issue by Nick-Shaw** [colour-science/colour#421]
https://github.com/colour-science/colour/blob/8db0d07b342855521f03e080d9d149336a939965/colour/io/luts/iridas_cube.py#L234
The domain for an Iridas .cube should be (2, 3) whether the LUT is 2D or 3D. This line sets `default_domain` to [0, 1] for 2D LUTs, but then compares this to the (2, 3) domain of the LUT, and because they never match, always writes the domain lines to the file.

**Comment by KelSolaar** [comment]
Thanks @Nick-Shaw! I'm not sure what was the reasoning behind that.

I changed the line to `default_domain = np.array([[0, 0, 0], [1, 1, 1]])` which I think should fix the problem.
