### ISSUE TITLE
Add support for shaper LUTs.

### ISSUE THREAD

**Issue by Nick-Shaw** [colour-science/colour#422]
The colour.io.luts module currently supports only 1D, 2D and 3D LUTs. I think it should be expanded to support "combined LUTs" which include a shaper which may be 1D or 2D. Although neither of the LUT file formats currently implemented support combined LUTs, other formats added in future will do. In fact some may support input and output shapers, so I suggest that the necessary groundwork for that be laid now.

I think it makes sense to add a fourth sub-class of `AbstractLUT`, `LUTcombined` which included `input_shaper` and `output_shaper` as attributes. These would be instances of `LUT1D` or `LUT2D`.

**Comment by KelSolaar** [comment]
Yes as discussed on Slack, it makes total sense!

I think it will actually inherit from `LUT3D` and as far as the name goes he are some options:

- `LUTCombined`
- `LUTAggregate`
- `LUTAssembly` <--- My vote! :)

**Comment by KelSolaar** [comment]
Implemented as `colour.LUTSequence` class.
