### ISSUE TITLE
Add support for "Resolve" ".cube" LUTs.

### ISSUE THREAD

**Issue by Nick-Shaw** [colour-science/colour#423]
Although at a base level, Resolve .cube is identical to Iridas .cube, when the domain is not implicitly 0-1, the domain declaration differs. There does not seem to be any official documentation on the Resolve .cube format, but it is detailed in this post by Resolve Product Manager Peter Chamberlain – https://forum.blackmagicdesign.com/viewtopic.php?f=21&t=40284#p232952

Resolve .cube does not support 1D LUTs, but I suggest that it is sensible for both Resolve and Iridas .cube to implement an automatic conversion to `LUT2D` with 3 identical columns, to allow writing of `LUT1D`s to .cube files.

Resolve .cube also supports 3D LUTs with 2D input shapers, which would obviously require #422 to be implemented first.

Some thinking is required regarding automatic handling of reading .cube files, as until they are parsed, it is not know whether they are Iridas or Resolve. To add more confusion, the Truelight Cube format also sometimes uses the extension .cube, although .cub is now more common in order to differentiate it.

**Comment by KelSolaar** [comment]
Yes! I will address #422 first and we need the LUT conversion definitions too.

**Comment by Nick-Shaw** [comment]
I have a simple 1D to 2D conversion method implemented in my fork - https://github.com/Nick-Shaw/colour/commit/c5c8fcbf9a6eec6f8a3d1defb4774ad8c02ff762

**Comment by KelSolaar** [comment]
Implement as per #426.
