### ISSUE TITLE
Implement support for writing LUT Matrix formats.

### ISSUE THREAD

**Issue by sobotka** [colour-science/colour#435]
Implement support for 3x3 matrices with offsets via spimtx etc.

**Comment by KelSolaar** [comment]
@sobotka : What are your expectations in regard to the above? Do you want to write arbitrary matrices? Do you need a particular set of matrices, e.g. RGB to XYZ, RGB to RGB?

Something like that given a bit of massaging should be close to whatever *.spimtx* spec is:

```python
>>> str(list(np.ravel(np.hstack([colour.models.sRGB_COLOURSPACE.RGB_to_XYZ_matrix, np.zeros((3, 1))]))))
'[0.41239999999999999, 0.35759999999999997, 0.18049999999999999, 0.0, 0.21260000000000001, 0.71519999999999995, 0.0722, 0.0, 0.019300000000000001, 0.1192, 0.95050000000000001, 0.0]'
```

**Comment by sobotka** [comment]
I figured it fit in with the existing LUT support. Formatting and dumping a stanza to a text file as with the others more or less?

**Comment by Nick-Shaw** [comment]
If we add `matrix`, `range` and `ASC_CDL` as `AbstractLUTSequenceOperator`s then we have all the operators that make up CLF, so have the building blocks to support that.

**Comment by Nick-Shaw** [comment]
I've now created `ASC_CDL`, `Matrix` and `Range` operators in the `feature/CLF` branch as a stepping stone towards CLF support. So the ability to read, write and apply `.spimtx` files is there.

**Comment by KelSolaar** [comment]
We have now support for this with the `colour.LUTOperatorMatrix` class and the `colour.io.read_LUT_SonySPImtx` and `colour.io.write_LUT_SonySPImtx` definitions.
