### ISSUE TITLE
Difference in HLG constants between ARIB STD-B67 and ITU-R BT.2100.

### ISSUE THREAD

**Issue by Nick-Shaw** [colour-science/colour#437]
In ARIB STD-B67 the constants a, b & c are all declared explicitly, whereas in ITU-R BT.2100 c is defined as a function of a. in ARIB STD-B67, `c = 0.55991073` whereas in BT.2100,`c = 0.5 - a * ln(4*a) = 0.559910729529562`. Since `itur_bt_2100.py` uses the functions from `arib_std_b67.py` for HLG, this is not strictly accurate.

In fact BT.2100 also defines b in terms of a, as `b = 1 - 4 * a` but that gives an identical result to the explicitly declared constant.

**Comment by Nick-Shaw** [comment]
In fact, in BT.2100, NOTE 5b says "The values of b and c are calculated to b = 0.28466892, c = 0.55991073" so I suppose it is open to interpretation which value should be used.

**Comment by KelSolaar** [comment]
Should we do it a bit similarly to what we did with *BT.2020*: https://github.com/colour-science/colour/blob/416858bb2ced37c10e90b82af3bdea9eecb538a2/colour/models/rgb/transfer_functions/itur_bt_2020.py#L57?

**Comment by KelSolaar** [comment]
(and add some descriptive notes!)

**Comment by Nick-Shaw** [comment]
That's probably a good idea – add the option for the perfectionists.
Of course in BT.2020 it makes a real difference, in that the curve segments do not join exactly unless you use the precise values. Here only the shape of the curve is modified imperceptibly in a way which probably makes no real difference.
