### ISSUE TITLE
Update "eotf_BT2100_HLG" to July 2018 BT.2100-2 specification.

### ISSUE THREAD

**Issue by nick-shaw** [colour-science/colour#450]
The black handling in the HLG EOTF and OOTF has been changed with the July 2018 update to BT.2100 (thanks to Tim Borer for alerting me to this.)

For completeness, I suppose we should add a `use_legacy` kwarg, so the previous version can be used.

**Comment by KelSolaar** [comment]
We should probably look at this one sooner than later. I guess the update is the black lift here:

![image](https://user-images.githubusercontent.com/99779/57601401-85250300-75b0-11e9-8afe-3601d4cf1818.png)

References
---
- https://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.2100-2-201807-I!!PDF-E.pdf

**Comment by KelSolaar** [comment]
@nick-shaw : I was looking at that and I just noticed there is a negative clamp that might prevent the full reverse implementation, I'm thinking about dropping it.
