### ISSUE TITLE
"colour.write_image" definition method may need to be updated due to the most recent update of "OpenImageIO" .

### ISSUE THREAD

**Issue by miaoqiz** [colour-science/colour#454]
There are a few changes with regard to writing images by "OpenImageIO" 2.0.4. 

https://github.com/OpenImageIO/oiio/blob/master/CHANGES.md

In addition to create a updated version of "write_image(...)" method, there is a need to examine the version of installed "OpenImageIO" before calling the correct version of "write_image(...)" in colour-science.

**Comment by miaoqiz** [comment]
Also, "**ImageOutputOpenMode**" is not available for "import" in the latest "OpenImageIO".

**Comment by KelSolaar** [comment]
Thanks, I will try to look at either this weekend or next week.
