### ISSUE TITLE
I build a dict to make a SPD instance but encountered a error

### ISSUE THREAD

**Issue by Edwardlin-zlt** [colour-science/colour#455]
I have no idea where goes wrong~

- build the dict
![build the dict](https://user-images.githubusercontent.com/35733429/50951467-468b1900-14e8-11e9-81ae-34f26f48e6a2.png)

- something went wrong
![error occur](https://user-images.githubusercontent.com/35733429/50951488-53a80800-14e8-11e9-9913-e1d2dfd5f93f.png)

**Comment by Edwardlin-zlt** [comment]
OK，My bad... I didn't turn the wavelengths into numbers...

**Comment by KelSolaar** [comment]
Glad you figured out the issue, the exception is quite cryptic!
