### ISSUE TITLE
Fix regressions introduced to "CIECAM02" and "CAM16" implementations by "Colour 0.3.12".

### ISSUE THREAD

**Issue by nschloe** [colour-science/colour#467]
I just noticed that the CIECAM02 implementation of colour diverged from https://github.com/nschloe/colorio and https://github.com/njsmith/colorspacious (which both coincide) in commit 5992be6adfcf28a3c4260376007b0ddcf3b8d1a1. You might want to tighten the screws on your tests.

**Comment by KelSolaar** [comment]
@nschloe : Which tests did u run? I ran this file https://github.com/nschloe/colorio/blob/master/test/test_comparisons.py and all the assertions are passing.

**Comment by nschloe** [comment]
https://github.com/nschloe/colorio/blob/master/test/test_comparisons.py#L64

**Comment by KelSolaar** [comment]
They pass for me, which Python / OS are you running that from?

![image](https://user-images.githubusercontent.com/99779/56091568-b86a6880-5f04-11e9-98d5-07b8cc8acfcd.png)

**Comment by nschloe** [comment]
Running `python` on the file just executes the `__main__` function. Do
```
pytest test_comparison.py
```

**Comment by KelSolaar** [comment]
I added the `print('Done!')` statement (visible in screengrab above) to show that the assertion are passing.

**Comment by nschloe** [comment]
Weird. Okay, let's dig some more. This
```python
import colorspacious
import colorio
import colour

xyz = [61.45276998, 7.00421901, 82.24067384]
whitepoint = (95.047, 100, 108.883)
L_A = 4.074366543152521
Y_b = 20

cs1 = colorspacious.ciecam02.CIECAM02Space(
    whitepoint, Y_b, L_A, surround=colorspacious.CIECAM02Surround.AVERAGE
)
ref1 = cs1.XYZ100_to_CIECAM02(xyz)
print(ref1.J)

c = 0.69
cs2 = colorio.CIECAM02(c, Y_b, L_A)
J, C, H, h, M, s, Q = cs2.from_xyz100(xyz)
print(J)

ref2 = colour.appearance.ciecam02.XYZ_to_CIECAM02(xyz, whitepoint, L_A, Y_b)
print(ref2.J)
```
gives
```
21.727294359
21.727294359
21.6885754407
```
on my machine.

**Comment by KelSolaar** [comment]
Confirming the above

*0.3.11*
(colour-3.7) Kali:test kelsolaar$ python test_colour.py
21.727294359
21.727294359
21.6885754407

*0.3.12*
(colour-3.7) Kali:test kelsolaar$ python test_colour.py
21.727294358955028
21.727294358955028
21.72729435895502

The thing I don't get is that your tests are passing!

**Comment by nschloe** [comment]
> The thing I don't get is that your tests are passing!

Me neither. They don't pass here, so that seems legit. Also weird: I get the wrong value from colour master, too. With versions:
```
1.1.2
21.727294359

0.2.4
21.727294359

0.3.12
21.6885754407
```

**Comment by KelSolaar** [comment]
I found out the issue, will push a fix tomorrow, thanks for spotting that!
