### ISSUE TITLE
Division by zero errors occurring when plotting the CIE 1976 UCS chromaticity diagram.

### ISSUE THREAD

**Issue by leklbk** [colour-science/colour#468]
When Plotting CIE1976 chromaticity diagram in python IDLE, "divide by zero errors" occurs. 
However When I plot it in spyder, the error doesn't appear.

How can I run this code in IDLE without error?

**Comment by KelSolaar** [comment]
Hi @leklbk,

Do you have a traceback or something? The zero-division depending where they happen should not be an issue.

Cheers,

Thomas

**Comment by leklbk** [comment]
Hi @KelSolaar 
for the security issues, I can't copy it. Last trace back is about
site-packages\colour\algebra\common.py:164: RuntimeWarning: invalid value encountered in sign
 a_p = np.sign(a) * np.abs(a) **p

This warning occurs both spyder IDLE and basic IDLE. However spyder can plot, basic IDLE cannot.

**Comment by KelSolaar** [comment]
Right so this is a warning, it should be meaningless!

In your script try the following:

At the top:

```python
import matplotlib.pyplot as plt
```

and where you want to see the figure:

```python
plt.show()
```

**Comment by KelSolaar** [comment]
@leklbk : This should be addressed in [develop](https://github.com/colour-science/colour/tree/develop).
