### ISSUE TITLE
Implement support for Academy Spectral Similarity Index (SSI).

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#472]
This one should be relatively straight-forward but will require a bit of work, the process is outlined in the [Academy Spectral Similarity Index (SSI): Overview](https://www.oscars.org/sites/oscars/files/ssi_overview_2019-03-04.pdf) pdf file.

The new code would sit in a new `colour.quality.ssi` module along with unit tests.

References
---

- https://www.oscars.org/science-technology/projects/spectral-similarity-index-ssi

**Comment by anshulxyz** [comment]
Hi, I'd like to work on this issue

**Comment by KelSolaar** [comment]
Hi @anshulxyz,

Thanks, that would be fantastic!

**Comment by anshulxyz** [comment]
awesome! I would like if you assigned this issue to me 
![Screenshot from 2019-10-01 11-13-46](https://user-images.githubusercontent.com/6121530/65937164-9629c000-e43c-11e9-81cf-f56ab146a9e6.png)


That would help me find the issues that are assigned to me :pray:

**Comment by KelSolaar** [comment]
Sure thing, done! :)

**Comment by anshulxyz** [comment]
hi Thomas, just keeping you updated that I am working on it. Didn't get time last few weeks, am starting now.

**Comment by KelSolaar** [comment]
Cheers! Let me know if you need any help!

**Comment by anshulxyz** [comment]
I ran tests without writing any code and this is the final report.
```
Ran 2317 tests in 356.003s
FAILED (errors=8, failures=6)
```
my branch is up-to-date with your `develop` branch. Can you run the tests and tell me your tests report?

**Comment by KelSolaar** [comment]
It could be because of missing EXR reading file support, can you try installing the **FreeImage** plugin for **imageio** in your python environment for **Colour** as follows:

```bash
python -c "import imageio;imageio.plugins.freeimage.download()"
```

**Comment by KelSolaar** [comment]
@anshulxyz : I'm taking over this one! It is mostly implemented already! Thank you.
