### ISSUE TITLE
Implement support for "Spectral Primary Decomposition for Rendering with sRGB Reflectance".

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#487]
References
---
- https://geometrian.com/data/research/spectral-primaries/EGSR2019_SpectralPrimaryDecomposition.pdf
- https://graphics.geometrian.com/research/spectral-primaries.html

**Comment by KelSolaar** [comment]
The publication has a [Supplemental Materials](https://geometrian.com/data/research/spectral-primaries/supplemental.zip) archive with some Matlab code to generate the basis functions. This is certainly not trivial as my initial assessment seemed to imply, thus I removed the *Good First Issue* label.

**Comment by sobotka** [comment]
So this is exactly the edge case I was getting at in the channel, and it seems to be negating the illuminant in the solve for the primaries. That is, I _think_ we can target Illuminant E here for both sum-to-one and the target SDs, and the result would be the same?

Needless to say, does it not make sense to make this more versatile in Colour and target any set of primaries? Would that be logical?
