### ISSUE TITLE
SpectralDistribution align for non-uniform shapes?

### ISSUE THREAD

**Issue by briend** [colour-science/colour#493]
With a weird shape like this (below), the "shape" property doesn't seem to be useful or accurate.  I'm trying to plug this non-uniform distribution in the Spectral_to_XYZ recovery functions but I cannot align the CMFS and illuminant to this funky SpectralDistribution.  Is there something I'm missing or do I need to manually do the alignment somehow?  Thank you for any advice!

data = {
    467: 0.0,
    495: 0.0,
    532: 0.0,
    570: 0.0,
    580: 0.0,
    590: 0.0,
    630: 0.0
}SpectralDistribution(data).shape
SpectralShape(467.0, 630.0, 10.0)

**Comment by KelSolaar** [comment]
Hi @briend,

There is no direct way to do that indeed. You could however manually extract the values as follows:

```
from colour import SpectralDistribution, ILLUMINANTS_SDS

data = {
    467: 0.0,
    495: 0.0,
    532: 0.0,
    570: 0.0,
    580: 0.0,
    590: 0.0,
    630: 0.0
}
sd = SpectralDistribution(data)

illuminant = SpectralDistribution(ILLUMINANTS_SDS['D65'][sd.wavelengths], sd.wavelengths)

print(illuminant)
```

**Comment by briend** [comment]
Thanks, that worked out well after tweaking the related recovery functions to use the custom shape for CMFS and illuminant

**Comment by KelSolaar** [comment]
Awesome thanks! Closing this one then :)
