### ISSUE TITLE
Writing an ndarray using "colour.write_image" definition modifies the array in place.

### ISSUE THREAD

**Issue by nick-shaw** [colour-science/colour#495]
https://github.com/colour-science/colour/blob/239410c06d4b73028f7affafdbea28e1adee3e4a/colour/io/image.py#L418

For example writing a float array to an uint16 file results in the entire array being multiplied by 65535.

This seems like undesirable behaviour. Should an `np.copy` be added?

**Comment by KelSolaar** [comment]
Yes this should not happen! Do you mind opening a PR @nick-shaw ?

Cheers,

Thomas
