### ISSUE TITLE
Implement support for the "JzAzBz" based colour appearance model.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#499]
References
---
- https://www.ingentaconnect.com/content/10.2352/ISSN.2169-2629.2018.26.96

**Comment by pathakcodes** [comment]
@KelSolaar  I am here through GSoC page and interested in implementing new CAM.

I have studied colour.appearance module and can't access the paper as its paid.
Help me get access to it. I am interested in working on this project.

**Comment by KelSolaar** [comment]
Hi Shivam,

Welcome :)

I got back to you via email, see you there!

Cheers,

Thomas

**Comment by KelSolaar** [comment]
Closing in favour of *ZCAM* that was implemented.
