### ISSUE TITLE
Fix missing spaces in "colour.encoding_cctf" and "colour.decoding_cctf" definitions docstrings.

### ISSUE THREAD

**Issue by sobotka** [colour-science/colour#505]
Missing a space after the `the`.

https://github.com/colour-science/colour/blob/2bf80feb352ce88292e904174411023a48b67fa5/colour/models/rgb/transfer_functions/__init__.py#L782

**Comment by KelSolaar** [comment]
Good catch! Actually there is another one two lines above, there must be some other similar in the file.

**Comment by KelSolaar** [comment]
@sobotka : Mind opening a PR for this one please whenever you have some cycles, should be very easy :)

**Comment by sobotka** [comment]
Will do! If you catch others, drop them here and I’ll do one squished commit.

**Comment by KelSolaar** [comment]
Thanks @sobotka! I did not see any but I must admit I'm not actively chasing them, just taming them as I go usually.
