### ISSUE TITLE
"colour.SpectralDistribution_IESTM2714.read" method should probably return "self".

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#506]
The `colour.SpectralDistribution_IESTM2714.read` method returns `True` currently while it should probably return `self`: https://github.com/colour-science/colour/blob/8eb5c73fbd986f47ef5fbc7cb48d0288bdfb12c0/colour/io/ies_tm2714.py#L996

This would allow one to do something along those lines:

```python
sd = SpectralDistribution_IESTM2714('Fluorescent.spdx').read()
```

instead of

```
sd = SpectralDistribution_IESTM2714('Fluorescent.spdx')
sd.read()
```

**Comment by BPearlstine** [comment]
I'll take this on and push up tomorrow

**Comment by KelSolaar** [comment]
Thanks @BPearlstine!

**Comment by Apoorva-13** [comment]
Hey,can i take up this issue?

**Comment by KelSolaar** [comment]
@Apoorva-13 : I think it would be fair to do it on a claim order basis, and give some more time to @BPearlstine.

Cheers,

Thomas

**Comment by Apoorva-13** [comment]
ok sure

**Comment by BPearlstine** [comment]
Hey I apologize for any spam you may have gotten off failed tests. I'm not used to your testing set up and ran into issues getting travis to work on my fork and running nosetest locally. I believe the doctests should work after applying the #doctest: +ELLIPSIS  that you are using elsewhere to only check for the first line of the returned object's representation, but am unsure how you want me to handle test_ies_tm2714.TestIES_TM2714_Sd.test_read line 312? having a giant  string representation of the object in the test to assertEqual against seems not great.

**Comment by KelSolaar** [comment]
Sorry for not getting back to you earlier, what you could do is something along those lines for the docstring:

from

```python
        >>> sd = SpectralDistribution_IESTM2714(
        ...     join(directory, 'Fluorescent.spdx'))
        >>> sd.read()
        True
```

to

```python
        >>> sd = SpectralDistribution_IESTM2714(
        ...     join(directory, 'Fluorescent.spdx')).read()
```

And for the unit tests, maybe doing something like that:

from

```python
        if sd is None:
            sd = SpectralDistribution_IESTM2714(
                os.path.join(RESOURCES_DIRECTORY, 'Fluorescent.spdx'))

        self.assertTrue(sd.read())
```

to

```
        if sd is None:
            sd = SpectralDistribution_IESTM2714(
                os.path.join(RESOURCES_DIRECTORY, 'Fluorescent.spdx')).read()
```

I haven't checked at your PR yet though, bit swamped at work currently!

**Comment by BPearlstine** [comment]
@KelSolaar 

No problem, I reverted the branch and remade my changes and updated the tests but there is still a failure in one test that I'm a little confused by. But it's almost there
