### ISSUE TITLE
Fix "from collections import Mapping, MutableMapping" with Python 3.8.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#511]
This relates directly to #489 which has unfortunately not been updated by the original contributor. 

The takeaway is that for Python 3.8 not breaking our imports we need to change a few imports from:

```python
from collections import Mapping, MutableMapping
```

to:

```python
from collections.abc import Mapping, MutableMapping
```

So I'm suggesting we use the following import scheme:

```python
import sys

if sys.version_info[:2] >= (3, 8):  # pragma: no cover
    from collections.abc import Mapping, MutableMapping
else:  # pragma: no cover
    from collections import Mapping, MutableMapping
```

These are the imports I noted that would need change when I looked at it a few weeks ago:

```python
/colour-science/colour/colour/algebra
    interpolation.py
        from collections import OrderedDict, Mapping
/colour-science/colour/colour/continuous
    multi_signals.py
        from collections import Iterator, Mapping, OrderedDict, Sequence
    signal.py
        from collections import Iterator, Mapping, OrderedDict, Sequence
/colour-science/colour/colour/plotting
    models.py
        from collections import Mapping
/colour-science/colour/colour/utilities
    array.py
        from collections import Mapping
    data_structures.py
        from collections import Mapping, MutableMapping
```

We cannot really check if the code works on 3.8 as we don't build against it but I'm assuming this should work.

**Comment by Chinmayrane16** [comment]
Hey @KelSolaar, is anyone working on this?

**Comment by KelSolaar** [comment]
Hi @Chinmayrane16,

Nobody currently! You can claim it if you want :)

Cheers,

Thomas

**Comment by Chinmayrane16** [comment]
Cool.. then basically in each python file listed above, I have to check for the version of python installed.. and import the necessary modules, right!?

**Comment by Chinmayrane16** [comment]
Hey @KelSolaar, 

Actually, I am new to open source and facing an issue here, there are some failed checks due to conditional importing which is not alowed by pep8.

Is there any other way to include conditional importing??

**Comment by Chinmayrane16** [comment]
Hey @KelSolaar, 

I have updated the code. Kindly look into it and suggest changes, if any! :)

**Comment by KelSolaar** [comment]
Thanks a lot, this is merged! :)
