### ISSUE TITLE
Figures based on "colour.plotting.plot_multi_colour_swatches" definition have the grid and ticks enabled on "RtD".

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#521]
The figures based on `colour.plotting.plot_multi_colour_swatches` definition have the grid and ticks enabled on "RtD":

![image](https://user-images.githubusercontent.com/99779/67129685-cf936580-f25b-11e9-89e6-728c11407bc6.png)
![image](https://user-images.githubusercontent.com/99779/67129710-db7f2780-f25b-11e9-8623-5253a484ef10.png)

I have no idea as to why currently, this does not happen in the tests we did for Windows, macOS and Linux. Matplotlib version was the same and is dictated by the `requirements.txt` file.

**Comment by Aryan1Mahahjan** [comment]
I noticed this issue hasn't been updated in a while. Is it still relevant and open for contributions? Specifically, I'm interested in working on #521.

**Comment by KelSolaar** [comment]
Hi @Aryan1Mahahjan,

Thanks for the very nice offer, it seems like this was fixed and probably an issue on the Matplotlib side: https://colour.readthedocs.io/en/develop/generated/colour.plotting.plot_multi_colour_swatches.html#colour.plotting.plot_multi_colour_swatches

Feel free to hop onto another one.

Closing this one!

Cheers,

Thomas
