### ISSUE TITLE
Reading 65^3 Iridas 3D LUT is incredibly slow. 

### ISSUE THREAD

**Issue by lavrovd** [colour-science/colour#573]
First time using Colour. Trying to read loads of  65^3 .cube files in Jupyter notebook. It takes over 3 mins on the first one. 

```
%time LUT = cs.io.read_LUT_IridasCube(luts[126])

CPU times: user 3min 20s, sys: 1.88 s, total: 3min 22s
Wall time: 3min 22s
```
Changing 
https://github.com/colour-science/colour/blob/2b2ad0a0f2052a1a0b4b076b489687235e804fdf/colour/io/luts/iridas_cube.py#L135

to 
``` Python
table.append(tokens)
```

gives no difference to the result and computes faster
```
%time LUTfast = read_LUT_IridasCube(luts[126])
CPU times: user 633 ms, sys: 26.2 ms, total: 659 ms
Wall time: 661 ms
```

```
np.allclose(LUTfast.table, LUT.table)

True
```

**Comment by KelSolaar** [comment]
Hi @lavrovd,

Thanks this is really good finding!

I think your change piggy-back on some internal Numpy magic that casts the strings to float:

```python
>>> import numpy as np
>>> np.asarray(['0.797894', '-0.035412', '-0.035412'], dtype=np.float_)
array([ 0.797894, -0.035412, -0.035412])
```

I did not even know this was a thing! We should look at where `colour.io.luts.common.parse_array` is involved and maybe let Numpy do its thing. @nick-shaw what do you think?

**Comment by KelSolaar** [comment]
BTW @lavrovd : For the time being, you could probably monkey patch `colour.io.luts.common.parse_array` so that it passes the value through straight instead of attempting to parse.

**Comment by lavrovd** [comment]
Yes. Thanks. Doing exactly that.

**Comment by njwardhan** [comment]
Hello @lavrovd!

I am Nishant Joywardhan, and I am working with Colour under the GSoC-2020 program for improvement of its LUT IO support. I took up this issue, but haven't been able to replicate it. If you could provide me with your test case LUT file(s) which you have tried to load, it would be really helpful for me to go about understanding the issue properly and then fixing it. Thanks! :)

**Comment by lavrovd** [comment]
Sure thing. [There]( https://af0a41c0-358f-496c-b559-adf398d49857.s3.eu-west-2.amazonaws.com/large.cube.zip)

Just tried again for sanity. Still there. 

```python
# Colour 
%time LUT = cs.io.read_LUT_IridasCube(filename)
CPU times: user 3min 8s, sys: 992 ms, total: 3min 9s
Wall time: 3min 9s

# Patched
%time lut = readLUTFast(filename)
CPU times: user 539 ms, sys: 25.8 ms, total: 565 ms
Wall time: 564 ms
```

**Comment by njwardhan** [comment]
Thanks for the follow up @lavrovd.

I tried to read the file which you have attached in the previous comment with the as it is `read_LUT_IridasCube()` function of colour, and it got finished in just 2 seconds, (without any patch):

![LargeCubeReading](https://user-images.githubusercontent.com/59248171/83719368-9249df80-a654-11ea-8ffe-419fe7562203.png)

Am I committing any error in understanding your issue?

**Comment by KelSolaar** [comment]
Hi,

This is really puzzling me too, because:

![image](https://user-images.githubusercontent.com/99779/83722372-f5f1fe00-a690-11ea-83ee-f834cecffd5e.png)


@lavrovd: When you have a chance, is it possible to get an output from `colour.utilities.describe_environment()` please?

**Comment by lavrovd** [comment]
```
===============================================================================
*                                                                             *
*   Interpreter :                                                             *
*       python : 3.7.2 (default, Dec 29 2018, 00:00:04)                       *
*                [Clang 4.0.1 (tags/RELEASE_401/final)]                       *
*                                                                             *
*   colour-science.org :                                                      *
*       colour : 0.3.15                                                       *
*                                                                             *
*   Runtime :                                                                 *
*       imageio : 2.5.0                                                       *
*       matplotlib : 2.2.3                                                    *
*       numpy : 1.15.4                                                        *
*       pandas : 0.24.2                                                       *
*       scipy : 1.1.0                                                         *
*       six : 1.12.0                                                          *
*                                                                             *
===============================================================================
Out[4]:
defaultdict(collections.OrderedDict,
            {'Interpreter': OrderedDict([('python',
                           '3.7.2 (default, Dec 29 2018, 00:00:04) \n[Clang 4.0.1 (tags/RELEASE_401/final)]')]),
             'colour-science.org': OrderedDict([('colour', '0.3.15')]),
             'Runtime': OrderedDict([('imageio', '2.5.0'),
                          ('matplotlib', '2.2.3'),
                          ('numpy', '1.15.4'),
                          ('pandas', '0.24.2'),
                          ('scipy', '1.1.0'),
                          ('six', '1.12.0')])})
```

**Comment by KelSolaar** [comment]
Thanks @lavrovd, still cannot reproduce with my slightly different setup, maybe something with your Numpy version:

```
===============================================================================
*                                                                             *
*   Interpreter :                                                             *
*       python : 3.7.6 (default, Dec 30 2019, 19:38:26)                       *
*                [Clang 11.0.0 (clang-1100.0.33.16)]                          *
*                                                                             *
*   colour-science.org :                                                      *
*       colour : v0.3.15                                                      *
*                                                                             *
*   Runtime :                                                                 *
*       imageio : 2.6.1                                                       *
*       matplotlib : 3.0.3                                                    *
*       networkx : 2.4                                                        *
*       numpy : 1.18.1                                                        *
*       pandas : 0.24.2                                                       *
*       pygraphviz : 1.5                                                      *
*       scipy : 1.4.1                                                         *
*       six : 1.14.0                                                          *
*       OpenImageIO : 2.1.11                                                  *
*                                                                             *
===============================================================================
```

@njwardhan is implementing the changes anyway, thanks for your time and patience!

**Comment by KevinJW** [comment]
Randome thoughts to check:

- What OS platform
- What locale is in place

there can sometimes be odd behaviours due to these kinds of things

**Comment by MichaelMauderer** [comment]
Another random thought: what type of hard drive?

**Comment by KelSolaar** [comment]
@KevinJW and @MichaelMauderer: Excellent points!

en_US / UTF8 all the way here:

```
Kali:~ kelsolaar$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8
```

And SSD drive.

**Comment by lavrovd** [comment]
```LANG="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_CTYPE="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_ALL=```

macOS 10.15.5 / 2.4 GHz 8-Core Intel Core i9  / 32 GB 2667 MHz DDR4

**Comment by KelSolaar** [comment]
Thanks @lavrovd, does not seem to shed more light on what could be the underlying problem unfortunately.

**Comment by lavrovd** [comment]
Tried on my Linux box (Ubuntu 18.04) and read time is about 2 secs for that file. It is definitely Mac specific. Could be my setup.

**Comment by KelSolaar** [comment]
Could it be related to any antivirus checking all the IO of the Python process?

**Comment by KelSolaar** [comment]
@lavrovd : @njwardhan's PR #596 has been merge in the develop branch, so it should be up to full speed now! When you have a chance, let us know if it is fine, I'm assuming it is!
