### ISSUE TITLE
"UnicodeDecodeError" exception raised while installing development version.

### ISSUE THREAD

**Issue by sianyi** [colour-science/colour#577]
Not sure if it is a general issue or just happen at my Windows PC.

I used "pip install -e ." to install developement version in my Windows laptop and it shows 
UnicodeDecodeError: 'cp950' codec can't decode byte 0xf0 in position 2241: illegal multibyte sequence

After made the below change then I can install it properly.
https://github.com/sianyi/colour/commit/12bc73a78a67f31e84b26d38aecae4bf922f0bbc

**Comment by KelSolaar** [comment]
Hi @sianyi,

Which Python version are you using?

Cheers,

Thomas

**Comment by sianyi** [comment]
Python 3.7.3

**Comment by KelSolaar** [comment]
It looks like your locale or something is changing the default Python encoding. Would you mind trying that in the same shell you tried to install Colour:

```python
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'
```

**Comment by sianyi** [comment]
Here is my result..

Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 22:01:29) [MSC v.1900 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'

**Comment by KelSolaar** [comment]
Ok this is good, can you try that then please:

```python
>>> import locale
>>> locale.getdefaultlocale()
('en_US', 'UTF-8')
```

**Comment by sianyi** [comment]
You catch it!, so it is my enviroement problem ? 

```
>>> import locale
>>> locale.getdefaultlocale()
('en_US', 'cp950')
>>>
```

**Comment by KelSolaar** [comment]
So it is indeed related to your locale!

I think it is reasonable to change the `open` call and force `utf-8` however, I think it would be safer to use an `utf-8` locale generally as this is the default Python encoding and you might run into other issues.

As for the actual change, we should use `codecs.open` because `open` does not support the `encoding` parameter in 2.7 (and we still release for it).

**Comment by sianyi** [comment]
Got it and thanks for the explanation

**Comment by KelSolaar** [comment]
Here is some info on how to change it if you need/want: https://www.tecmint.com/set-system-locales-in-linux/

I will make a note about updating the `open` thing, although because the `setup.py` file is partially generated by Poetry, it is not entirely trivial.

**Comment by KelSolaar** [comment]
@sianyi : This should hopefully be fixed in the latest develop, can you give it a stab please?

**Comment by sianyi** [comment]
It works well on my windows PC, thanks for have the change.
