### ISSUE TITLE
"SonyCorporation12" bibliography link seems to be redirected.

### ISSUE THREAD

**Issue by sobotka** [colour-science/colour#582]
Summary: SonyCorporation12 seems to not link to citation any longer.

**Comment by KelSolaar** [comment]
@sobotka : I cannot find a `SonyCorporation12` either in the code, Mendeley or the .bib file. Which branch are looking at?

**Comment by sobotka** [comment]
https://colour.readthedocs.io/en/latest/generated/colour.models.log_encoding_SLog2.html?highlight=Slog2

**Comment by sobotka** [comment]
Is it just me or has the document disappeared online from Sony's official sources?

**Comment by KelSolaar** [comment]
Looks like the link is dead AND there are also some .bib file related issues, some links are looking weird and the key, in this case, should be `SonyCorporation2012a`

**Comment by sobotka** [comment]
Well there I go again finding broken bits. Sorry.

**Comment by KelSolaar** [comment]
All good the .bib file is fixed, as for the link, will check later.

**Comment by KelSolaar** [comment]
I migrated our reference database from **Mendeley** to **Zotero**, regenerated all the citations across all our repositories and fixed that particular one.
