### ISSUE TITLE
How to plot log curves?

### ISSUE THREAD

**Issue by priikone** [colour-science/colour#608]
I was admiring the plots in @nick-shaw cinematiccolor repo, such as [https://nick-shaw.github.io/cinematiccolor/assets/figures/log-encoding-curves.svg](https://nick-shaw.github.io/cinematiccolor/assets/figures/log-encoding-curves.svg) and was wondering how they were plotted?  I believe I can get it done by doing something like:

`math.log2(colour.log_decoding(1, function='Log3G10')/.18)`

And go through the values between 0-1 (handling negative results separately). But I was wondering is there a more elegant way of doing this in colour? I don't think there's a way to directly plot them this way, is there?

**Comment by KelSolaar** [comment]
Glad that you are sorted @priikone! :)
