### ISSUE TITLE
Implement support for "HyAB" large colour difference metric.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#610]
References
---
- https://onlinelibrary.wiley.com/doi/abs/10.1002/col.22451

**Comment by NekoAlosama** [comment]
Here's a copy of the PDF provided by one of the authors (Mark D. Fairchild) on their website: http://markfairchild.org/PDFs/PAP40.pdf

**Comment by NekoAlosama** [comment]
@KelSolaar 
Here's a copy of the research paper provided by one of the authors (Mark D. Fairchild) on their website: http://markfairchild.org/PDFs/PAP40.pdf

**Comment by NekoAlosama** [comment]
HyAB is just the combination of a city-block expression for L* and the Euclidean distance with a* and b*.
So alike `abs(base.L*- test.L*) + math.dist([base.a*, base.b*], [test.a*, test.b*])` with L\*a\*b\* colors 'base' and 'test'.

**Comment by KelSolaar** [comment]
Thanks @NekoAlosama! I have the papers but did not find the time so far to implement the metric! If you want to give it a go, you are very much welcome do to so!
