### ISSUE TITLE
Cheung (2004): Transforms with 4 and 35 terms not implemented.

### ISSUE THREAD

**Issue by rsnitsch** [colour-science/colour#616]
Cheung et al. [1] define polynomial transforms with the following numbers of terms:
- 3
- 4 (not implemented)
- 5
- 10
- 20
- 35 (not implemented)

I just noticed that 4 and 35 terms are not supported by ``augmented_matrix_Cheung2004``. Is this intentional, and if yes, why? If not, I can implement the missing options (i.e. create a pull request).

[1] A comparative study of the characterisation of color cameras by means of neural networks and polynomial transforms, 2004 - https://www.researchgate.net/publication/227522365_A_comparative_study_of_the_characterisation_of_color_cameras_by_means_of_neural_networks_and_polynomial_transforms

**Comment by KelSolaar** [comment]
Hi @rsnitsch,

I don't remember but I suspect it is because I probably used Westland (2004) reference, and not the original Cheung (2004) paper one! The book is at work so I can only confirm Monday.

A PR would be very much welcome! 👍 

Cheers,

Thomas

**Comment by rsnitsch** [comment]
Have you been able to check on this?

**Comment by KelSolaar** [comment]
Hi @rsnitsch,

No sorry, been hell of a week at work will try to check tomorrow!

Cheers,

Thomas

**Comment by chnmasta05** [comment]
@rsnitsch @KelSolaar
I can confirm that the current implementation is based on Westland (2004). Also, there are no discrepancies between the two references. I will make a PR later today to implement the rest if that's okay.

**Comment by KelSolaar** [comment]
Hi @chnmasta05,

That would be great yes! Thank you :)
