### ISSUE TITLE
Matplotlib dependency is missing in "setup.py" file.

### ISSUE THREAD

**Issue by jackjansen** [colour-science/colour#626]
Just installed colour-science with pip (Python 3.8.5, venv, MacOS 10.13), and my first attempt to `import colour.plotting` resulted in 

```
ModuleNotFoundError: No module named 'matplotlib'
```

A quick `pip install matplotlib` fixed it, but apparently that dependency is missing in your setup.py.

**Comment by KelSolaar** [comment]
Hi @jackjansen,

_Matplotlib_ is an optional dependency and it should be here in the `setup.py` file: https://github.com/colour-science/colour/blob/develop/setup.py#L147

We only give installation steps for the core in the [README.rst](https://github.com/colour-science/colour#4installation) file but there is a link at the end of the section to this page which has all the details to get the various other dependencies: https://www.colour-science.org/installation-guide/

I will make it more obvious in the README file though and add a better error message during the import.

Cheers,

Thomas

**Comment by KelSolaar** [comment]
There should be a message and better documentation now!

```python
>>> import colour.plotting
Traceback (most recent call last):
  File "/Users/kelsolaar/Documents/Development/colour-science/colour/colour/utilities/common.py", line 326, in is_matplotlib_installed
    import matplotlib  # noqa
ModuleNotFoundError: No module named 'matplotlib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kelsolaar/Documents/Development/colour-science/colour/colour/plotting/__init__.py", line 7, in <module>
    is_matplotlib_installed(raise_exception=True)
  File "/Users/kelsolaar/Documents/Development/colour-science/colour/colour/utilities/common.py", line 331, in is_matplotlib_installed
    raise ImportError(
ImportError: "Matplotlib" related API features are not available: "No module named 'matplotlib'".
Please refer to the installation guide for more information: https://www.colour-science.org/installation-guide/
```
