### ISSUE TITLE
"colour.RGB_to_ICTCP" real input domain: contradiction with SMPTE ST 2084?

### ISSUE THREAD

**Issue by xjossy** [colour-science/colour#631]
As to [help page](https://colour.readthedocs.io/en/develop/generated/colour.RGB_to_ICTCP.html), the input range of function `RGB_to_ICTCP` is 0..1.

Internally, I see, that `RGB_to_ICTCP(x,y)`, where `y` is max display luminance equals to `RGB_to_ICTCP(x/y,1)` - normalization of `x` is division to display peak luminance.

What is the actual domain of `x`?

1. If `x` is 0..1 as the documentation says, then 1 corresponds to the maximum display luminance. And then, the bigger `y` the bigger actual brightness of `x==1`, but the value of `RGB_to_ICTCP` is the lesser (because `x/y` is lesser).

2. If `x` is 0..`y`, then `x` corresponds to real luminance in cd/m². In this case, the value of `RGB_to_ICTCP` shouldn't depend on `y` (but it actually does), because [specification of PQ EOFT in Wikipedia](https://en.wikipedia.org/wiki/High-dynamic-range_video#Perceptual_quantizer) operates real luminance with maximum 10,000 cd/m². For example, while calling `RGB_to_ICTCP([300,300,300],300)` we will get the same values, as if input luminances were 10,000, but actual value is 300 in this case.

I think the correct formula for normalization of `x` is `x*y/10000` - so, 1 should correspond to display maximum luminance.

Or at least, [help page](https://colour.readthedocs.io/en/develop/generated/colour.RGB_to_ICTCP.html) for `RGB_to_ICTCP` should be fixed.

**Comment by KelSolaar** [comment]
Hi @xjossy,

The page needs some update, at the very least with some more details like the underlying ST2084 one: https://colour.readthedocs.io/en/develop/generated/colour.models.eotf_ST2084.html

One important thing to understand for the domain-range values given in the documentation is that they are "soft" values: https://colour.readthedocs.io/en/develop/basics.html#domain-range-scales

As for the actual domain, it should be [0.0001, 10000] like PQ. I will amend the docs accordingly to make that clearer.
