### ISSUE TITLE
Y_b is misdocumented and should be scale-dependent

### ISSUE THREAD

**Issue by dfoxfranke** [colour-science/colour#643]
The `Y_b` parameter used when converting in and out of the CIECAM02, CAM16, and LLAB color spaces is documented as having units of cd/m^2. This is not correct: `Y_b` is a dimensionless ratio, namely the ratio between the background luminance L_b and the reference white luminance L_w. Accordingly, this parameter should respect the scale setting. It should have a Reference-scale domain of [0,100] (this is its current behavior) and a 1-scale domain of [0,1].

**Comment by KelSolaar** [comment]
Hi @dfoxfranke,

Thanks, I noted the documentation error quite a few times as it confused me at work but never came around to fix it. Let's discuss the scale in #644.

Cheers,

Thomas

**Comment by dfoxfranke** [comment]
You have a typo in the docs you added. In ``:math:`L_w` can be the average :math:`Y` value for the pixels in the entire image``, `L_w` should be `Y_b`.

**Comment by KelSolaar** [comment]
Thanks fixed!
