### ISSUE TITLE
Implement support for plotting gamut rings.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#647]
I have been meaning to do that for a while and just got reminded by Cedric (Lejeune) about it.

References
---
- https://www.displaydaily.com/index.php?option=com_content&view=article&id=72932:you-can-t-describe-colour-volume-in-2d-or-can-you&catid=152
- https://github.com/cielab-gamut-tools/gamut-volume-m
- ![image](https://user-images.githubusercontent.com/99779/98453245-f05a9000-21bb-11eb-9d44-a79c6b4a166c.png)
- ![image](https://user-images.githubusercontent.com/99779/98453250-f51f4400-21bb-11eb-8253-4abdf88687b4.png)

**Comment by hminle** [comment]
Hi @KelSolaar 
Just curious, does the area of the ring ALWAYS increase as the `L` channel increases?
