### ISSUE TITLE
DaVinci Wide Gamut - Primaries from White Paper

### ISSUE THREAD

**Issue by fredsavoir** [colour-science/colour#658]
Hi,
The DaVinci Wide Gamut Primaries are wrong in your implementation.
Here the correct one from the Official White Paper.
red | 0.8000 | 0.3130
green | 0.1618 | 0.9877
blue | 0.0790 | -0.1155
white | 0.3127 | 0.3290

Hope it's help.

Thanks,

Fred Savoir

https://documents.blackmagicdesign.com/InformationNotes/DaVinci_Resolve_17_Wide_Gamut_Intermediate.pdf?_v=1607414410000

**Comment by KelSolaar** [comment]
Hi @fredsavoir,

As mentioned in #650, the primaries were defined as specified by Resolve itself, but it looks like they changed them in the whitepaper, at least the matrices, which hints at something that was wrong on their end:

![image](https://user-images.githubusercontent.com/99779/101470745-41bc9180-39ab-11eb-877d-a34736f90740.png)

**Comment by fredsavoir** [comment]
Indeed thanks

**Comment by KelSolaar** [comment]
This is quite annoying as we might need to push a hotfix release for that...

Duplicates #648.
