### ISSUE TITLE
"colour.sd_to_XYZ" definition cache should return a copy of the data.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#662]
We cache the output of `colour.sd_to_XYZ` definition, however doing so, we do not return a copy of the data which can have some side effects, i.e. mutate the cached value.

Consider this example:

```python
XYZ = colour.sd_to_XYZ(my_sd)
XYZ *= 0.5
```

Future invocation of `colour.sd_to_XYZ` with `my_sd` would return tristimulus values halved.

We need to return a copy here:

```python
    if hash_key in _CACHE_SD_TO_XYZ:
        return _CACHE_SD_TO_XYZ[hash_key]
```

**Comment by KelSolaar** [comment]
This is can be generalised to the various caches we use across **colour**.

**Comment by remia** [comment]
Just bumped on that one in 0.3.16!

Thanks for the fix.

**Comment by KelSolaar** [comment]
Yeah, it was a nasty one!
