### ISSUE TITLE
iOS, iPadOS do no have support for "float128".

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#663]
As reported here: https://www.colour-science.org/posts/numfocus-colour-0314-and-colour-datasets-010/#comment-5187531290

```python
File "../../../downloadable-site-packages/compiled/numpy/__init__.py", line 214, in __getattr__
File "Documents/site-packages/colour/io/image.py", line 98, in <module>
'float128', np.float128, None, 1, False)
AttributeError: module 'numpy' has no attribute 'float128'
File "../../../downloadable-site-packages/compiled/numpy/__init__.py", line 214, in __getattr__
>>> AttributeError: module 'numpy' has no attribute 'float128’
```

**Comment by KelSolaar** [comment]
A quick hack to get colour 0.3.16 running in Pyto is to patch it locally on iOS.

Assuming you have pytest (or any other Pypi packaged) manually installed, you can run that once:

```python
import os
import pytest

SITE_PACKAGES_ROOT = os.path.abspath(os.path.join(pytest.__path__[0], '..'))

COLOUR_ROOT = os.path.join(SITE_PACKAGES_ROOT, 'colour')

COLOUR_IO_IMAGE_PATH = os.path.join(COLOUR_ROOT, 'io', 'image.py')

with open(COLOUR_IO_IMAGE_PATH) as MODULE_FILE:
    CONTENT = MODULE_FILE.readlines()

with open(COLOUR_IO_IMAGE_PATH, 'w') as MODULE_FILE:
    for _LINE in CONTENT:
        MODULE_FILE.write(_LINE.replace('np.float128', 'np.float64'))


```

**Comment by fredsavoir** [comment]
Hi thanks for patch but don't work
On my iOS.
Running as script change nothing ;(

**Comment by KelSolaar** [comment]
Do you have any specific errors?

**Comment by fredsavoir** [comment]
Simply don’t run in as script :(

**Comment by KelSolaar** [comment]
Here is a video of the steps I took that work for me: https://drive.google.com/file/d/1z78Et5I5XplTr1J1XI2t1WNrGA5ZEKtV/view?usp=drivesdk

**Comment by fredsavoir** [comment]
No it.s simply don.t run 

Not output at all 

Never mind no more Colour on IOS

Thanks anyway

**Comment by fredsavoir** [comment]
OK fixed….

Something was corrupted so I uninstall the app and delete prefs. Re-install and reinstall python modules and now it’s working.

So the patch is working .

Perfect.

Thanks a lot.

Fred

**Comment by KelSolaar** [comment]
Glad to hear!

**Comment by baileyji** [comment]
I'll point out this also makes the library fail on Raspberry Pi.

> In [2]: import  colour.temperature as ct
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-2-aeb4d114c299> in <module>()
> ----> 1 import  colour.temperature as ct
> 
> /home/pi/.local/lib/python3.7/site-packages/colour/__init__.py in <module>()
>      95 from .geometry import (PRIMITIVE_METHODS, primitive,
>      96                        PRIMITIVE_VERTICES_METHODS, primitive_vertices)
> ---> 97 from .io import (LUT1D, LUT3x1D, LUT3D, LUTSequence, READ_IMAGE_METHODS,
>      98                  SpectralDistribution_IESTM2714, WRITE_IMAGE_METHODS,
>      99                  read_image, read_LUT, read_sds_from_csv_file,
> 
> /home/pi/.local/lib/python3.7/site-packages/colour/io/__init__.py in <module>()
>       5 from .luts import *  # noqa
>       6 from . import luts
> ----> 7 from .image import ImageAttribute_Specification, convert_bit_depth
>       8 from .image import read_image_OpenImageIO, write_image_OpenImageIO
>       9 from .image import read_image_Imageio, write_image_Imageio
> 
> /home/pi/.local/lib/python3.7/site-packages/colour/io/image.py in <module>()
>      97     if platform.system() not in ('Windows', 'Microsoft'):  # pragma: no cover
>      98         BIT_DEPTH_MAPPING['float128'] = BitDepth_Specification(
> ---> 99             'float128', np.float128, None, 1, False)
>     100 
>     101 
...
> AttributeError: module 'numpy' has no attribute 'float128'

**Comment by fredsavoir** [comment]
Hi,

Try to patch it like on this one :)

Here is a video of the steps I took that work for me: https://drive.google.com/file/d/1z78Et5I5XplTr1J1XI2t1WNrGA5ZEKtV/view?usp=drivesdk <https://drive.google.com/file/d/1z78Et5I5XplTr1J1XI2t1WNrGA5ZEKtV/view?usp=drivesdk>
Hope it will work for you too.

Fred

**Comment by baileyji** [comment]
Yes, that hack worked, though I should note that the assumptions about SITE_PACKAGES_ROOT are not robust.

**Comment by KelSolaar** [comment]
Hi @baileyji,

> Yes, that hack worked, though I should note that the assumptions about SITE_PACKAGES_ROOT are not robust.

Absolutely and it is only temporary as the `develop` branch does not require that anymore.
