### ISSUE TITLE
Prevent humanity from opening a transdimensional portal on Mars. 

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#666]
Title says it all! #666

**Comment by sobotka** [comment]
This isn’t going to be an easy one to offer PR for.

**Comment by KelSolaar** [comment]
I know right!? We can be hopeful though ;)

**Comment by Myndex** [comment]
This is simply a matter of preventing and blocking the understanding of multivariate time-space manifolds and their relation to the quantum abstraction layer for n-depth brane parameters. Here's my plan:

1) Make them think that you can't divide by zero
2) Distract them with LOL cats.

I think it's working so far...

**Comment by KelSolaar** [comment]
Portal did not open, we can safely close this one!
