### ISSUE TITLE
About "CIE XYZ" to "CIE xyY" transformations behaviour with negative numbers.

### ISSUE THREAD

**Issue by sobotka** [colour-science/colour#671]
Long ago, in a galaxy far, far away, the calculation for xyY was formed back when simpler times existed, and all coordinates were positive.

Right now, in the galaxy very, very close, the calculation for normalization falls apart with negatives. With digital cameras and modern encodings using negative chromaticities to define their respective colour encodings, this is sadly a show stopper.

TODO: This is likely an issue with Ye Old 1976 L*u*v* and probably 1960 stuffs.

**Comment by KelSolaar** [comment]
This is a rather big one, we need to give more explanation and examples on what fails, how and why.

Given the CIE recommendations have not changed, our default behaviour must be compliant, so we will need some "magic" to activate the fixed behaviour.

**Comment by sobotka** [comment]
Indeed. I can understand the vantage that the CIE reference is canonized. I also believe that the default implementation, in 2021, the formulas should work for displaying, for example, camera encodings. I have caught a few plot errors out in the wild that are directly attributed to the negative errors, and it makes one wonder how many are spotted?

Challenging and nuanced surface.

**Comment by nick-shaw** [comment]
When plotting, I have found it preferable to cull pixels with a Y value below a certain threshold, in order to remove extreme xy values in the noise floor. There could be an argument that what is really needed is a `Y_threshold` parameter in the plotting functions.

**Comment by sobotka** [comment]
> There could be an argument that what is really needed is a Y_threshold parameter in the plotting functions.

I don’t think that helps for the case of arbitrary encoding primaries, does it? We should be able to see the 2D or 3D Cartesian position regardless, no?
