### ISSUE TITLE
Red Log3G10 Missing Linear Extension

### ISSUE THREAD

**Issue by jedypod** [colour-science/colour#673]
Greetings!
I noticed that in `colour.models.rgb.transfer_functions.red_log`, `log_encoding_Log3G10_v2` does not include the linear extension included in the [official whitepaper](https://docs.red.com/955-0187/PDF/915-0187%20Rev-C%20%20%20RED%20OPS,%20White%20Paper%20on%20REDWideGamutRGB%20and%20Log3G10.pdf). 

Is this an issue, perhaps because this implementation predated the whitepaper's release? Or did the v2 method exist for a while in RedCineX Pro before the whitepaper was released? Should there be a v3 matching the whitepaper?

I'd be happy to put in a pull request if any knowledgeable folks here know the right solution.

Thanks!

**Comment by nick-shaw** [comment]
Interesting. It was a long time ago, and my memory is hazy! My own code does include a v3, but it obviously never made it into Colour.
The `red_log` module could certainly do with an update. As well as the missing v3, the docstrings refer to very old versions of Resolve and REDCINE-X.

**Comment by KelSolaar** [comment]
Hey @jedypod,

HNY! PR is certainly welcome :)
