### ISSUE TITLE
Implement support for "ProLab" colourspace.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#675]
References
---
- https://github.com/konovalenko-iitp/proLab
- https://arxiv.org/abs/2012.07653

**Comment by ASCcool** [comment]
Is this issue still active @KelSolaar ?

**Comment by KelSolaar** [comment]
Hi @ASCcool,

Yes it is! :)

**Comment by Alt-Shivam** [comment]
Hey @SGeetansh are you working on this?
If not, then I can take it forward.
Thanks

**Comment by KelSolaar** [comment]
We have a branch close to completion for this one somewhere, I need to double-check it. I'm not sure it will make it for the 0.4.0 release though.

**Comment by KelSolaar** [comment]
Implemented and merged in #932.
