### ISSUE TITLE
Second radiation constant "c2" was changed in 2019

### ISSUE THREAD

**Issue by ValZapod** [colour-science/colour#676]
https://en.wikipedia.org/wiki/Planckian_locus#International_Temperature_Scale

All (?) these needs to be fixed to latest value 1.438776877. 

https://github.com/colour-science/colour/search?q=1.4388

The latest value from 2018 is exact, because other constants are also exact now, after https://en.wikipedia.org/wiki/2019_redefinition_of_the_SI_base_units

**Comment by KelSolaar** [comment]
Thanks for the note! The real question is whether the CIE has adopted the new value and which one. Unless they change it, we won't. I will check later on Colorimetry 4th Edition.

**Comment by KelSolaar** [comment]
So reading Colorimetry 4th Edition, 2018 but released end of 2019:

The usual note on the radiation constant `c2` change is still there, unchanged:

![image](https://user-images.githubusercontent.com/99779/104823146-c48b1300-58ac-11eb-861c-a131ada80b3f.png)

And there is also a note of the upcoming changes to it at the end, reading through them (which I actually remember doing back then), I decided it was not worth changing the constants as the CIE itself does not seem to do it either:

![image](https://user-images.githubusercontent.com/99779/104823194-4da24a00-58ad-11eb-8f89-2b27a59edd19.png)

That being said, I'm not closed to the idea of a) at the very least documenting the new values b) implementing a mechanism to be able to switch between them.
