### ISSUE TITLE
Incorrect deprecation handling of "DCI-P3" colourspace in Colour 0.3.16.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#758]
I just noticed that which can create all sort of issues for people not looking at warnings as this swaps the two colourspaces:

```python
    [
        'colour.models.DCI_P3_COLOURSPACE',
        'colour.models.RGB_COLOURSPACE_DCI_P3_P',
    ],
    [
        'colour.models.DCI_P3_P_COLOURSPACE',
        'colour.models.RGB_COLOURSPACE_DCI_P3',
    ],
```

https://github.com/colour-science/colour/blob/4494cb42ce6c7ee78464c93a4824638e42450a00/colour/models/__init__.py#L311

Wondering if we should not get a hotfix release out just for that.

@nick-shaw, @zachlewis, @MichaelMauderer: Thoughts?

**Comment by zachlewis** [comment]
Hmm. I think I'm in favor of a hotfix, especially given DCI P3's popularity.

**Comment by MichaelMauderer** [comment]
Agree this is a subtle bug that can be really messy for people running into it.

**Comment by KelSolaar** [comment]
Yeah, the thing I need to check is whether I can even regenerate the dev environment for that release. It was a Python 2 & 3 compatible one... Makes things really complicated!

**Comment by KelSolaar** [comment]
This will be part of the **v0.4.0** release, closing!
