### ISSUE TITLE
Implement support for "Recommendation ITU-R BT.2124-0", i.e. DeltaE IPT.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#774]
References
---
- https://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.2124-0-201901-I!!PDF-E.pdf

**Comment by ValZapod** [comment]
Some comments on magic number 720 (3*240) 
https://www.lightillusion.com/forums/msg.php?id=3022 (very funny)

And some comments from Dolby https://professional.dolby.com/siteassets/pdfs/dolby-vision-measuring-perceptual-color-volume-v7.1.pdf
