### ISSUE TITLE
ASTME313 Yellowness Index computation equation has been superseeded.

### ISSUE THREAD

**Issue by romanovar** [colour-science/colour#779]
It seems that 'yellowness_ASTME313()' does not implement the formula proposed by  ASTM Designation: E313 − 15´1.  

The published([chapter 6 page 3](http://materialstandard.com/wp-content/uploads/2019/10/E313-15e1.pdf)) formula by ASTM  is: 
![image](https://user-images.githubusercontent.com/9212575/107847761-a0a8e780-6dee-11eb-8e09-63bed9ac691f.png)

with coefficient values C_x = 1.3013 and C_z = 1.1498. 

The implementation in this library [is currently](https://colour.readthedocs.io/en/latest/_modules/colour/colorimetry/yellowness.html#yellowness_ASTME313):
```python
def yellowness_ASTME313(XYZ):
    """
    .....
    """
    _X, Y, Z = tsplit(to_domain_100(XYZ))
    WI = 100 * (1 - (0.847 * Z) / Y)
    return from_range_100(WI)
```

Environment: Python == 3.6.9, colour-science==0.3.16
Resources: http://materialstandard.com/wp-content/uploads/2019/10/E313-15e1.pdf
https://pdf4pro.com/view/yellowness-indices-hunterlab-e101e.html

**Comment by KelSolaar** [comment]
Hi @romanovar,

Thank you! So I took a look at the [X-Rite reference I](https://www.xrite.com/-/media/xrite/files/apps_engineering_techdocuments/c/09_color_calculations_en.pdf) used back then, and the equation is correct WRT that reference:

![image](https://user-images.githubusercontent.com/99779/107860461-4ff3c600-6ea4-11eb-936b-8d4d224319b1.png)

Using the 1931 coefficients for C, given by the reference ASTME313 formula for [95, 100, 105] I get:

> 100 * (1.2769 * 95 -  1.0592 * 105) / 100 = 10.0895

Our current implementation yields 11.065 which is incorrect, I played quickly with some other values and no dice, so I'm not sure how X-Rite factorised their equation.

I will fix that and check the other metrics as we used that reference for whiteness computation also.

**Comment by KelSolaar** [comment]
Allright, so reading the ASTME paper, which in its current variant is more recent than the X-Rite reference, I think I got to the bottom of it:

```
6.2.1 In the original form of Test Method E313, an alternative
equation was recommended for a yellowness index. In
terms of colorimeter readings, it was YI = 100(1 − B/G). Its
derivation assumed that, because of the limitation of the
concept to yellow (or blue) colors, it was not necessary to take
account of variations in the amber or red colorimeter reading A.
This equation is no longer recommended.
```

So the equation we use is correct but has been superseeded.
