### ISSUE TITLE
The exe file generated by PyInstaller does not work when importing colour module

### ISSUE THREAD

**Issue by farhanalfin** [colour-science/colour#781]
I am working over a project using colour library, using python 3.9 32 bit and pycharm is working, but when I convert it to exe using pyinstaller the exe does not work. To debug I created a simple program, the exe of this program does not work 
my system is windows 10 64 
converting command pyinstaller simple_colour.py

the error
Application Error The Exception Unknown Software Exception 0xC06D007E

import colour
from PyQt5.QtWidgets import QApplication, QMainWindow, QLabel

class mainwindow(QMainWindow):
    def __init__(self):
        QMainWindow.__init__(self)
        
        self.label = QLabel("Colour module is loaded")
        self.setCentralWidget(self.label)

app = QApplication([])
window = mainwindow()
window.show()
app.exec_()

**Comment by MrLixm** [comment]
Hello, I think it was not necessary to open a new issue but first answer to the replies you had on the first issue you opened here:
[https://github.com/colour-science/colour-checker-detection/discussions/16#discussioncomment-348455](https://github.com/colour-science/colour-checker-detection/discussions/16#discussioncomment-348455).

Please answer on the thread linked above.
Cheers.
Liam.
