### ISSUE TITLE
Slog3 transformations incorrectly applied to legal range data.

### ISSUE THREAD

**Issue by willSmallHD** [colour-science/colour#785]
Data is transformed into legal range before passing through the log_decoding_SLog3 and log_encoding_SLog3 functions. This is incorrect according to the [Technical Summary for S-Gamut3.Cine/S-Log3 and S-Gamut3/S-Log3 ](https://pro.sony/s3/cms-static-content/uploadfile/06/1237494271406.pdf) document (see FAQ Q4.)

**Comment by nick-shaw** [comment]
That is the purpose of the `out_normalised_code_value` (encoding) and `in_normalised_code_value` (decoding) kwargs. You can choose whether to apply a range scaling or not. This is to deal with cases such as recording the S-Log3 SDI output of a Sony camera with a "naive" ProRes Recorder, and then decoding the ProRes as if it were "video", mapping 0% IRE to 0.0 and 100% IRE to 1.0.
```
>>> colour.models.log_encoding_SLog3(0.0, out_normalised_code_value=True)
0.092864125122189639
>>> colour.models.log_encoding_SLog3(0.0, out_normalised_code_value=False)
0.035388127853881277
```
Those two results match the 3.5% IRE and 10-bit CV 95, as given in the table in the Sony paper.
```
>>> colour.models.log_encoding_SLog3(0.0, out_normalised_code_value=True) * 1023
95.0
```

**Comment by willSmallHD** [comment]
I agree that that matches the provided table, I will have to go back and understand what I am missing in the documentation. Thank you for clarifying.

**Comment by nick-shaw** [comment]
Believe me, I have spent a lot of time in a camera test rooms with cameras and waveform monitors, working out what is meant by ambiguous documentation!

**Comment by nick-shaw** [comment]
The arguments were originally called `in_legal` and `out_legal`, but were changed because "legal range" and "full range" are potentially ambiguous terms.

**Comment by willSmallHD** [comment]
I understand the arguments. My confusion mostly stems from the difference between slog and slog3. The slog transformation is applied to full range data, whereas the slog3 one is applied to legal.

**Comment by nick-shaw** [comment]
Yes. Sony changed the way they did things with the different S-Log papers. They also changed the handling of "reflectance" vs "linear IRE" just to keep everybody more confused.
