### ISSUE TITLE
The *.spimtx reader in the "feature/clf" branch reads offsets incorrectly.

### ISSUE THREAD

**Issue by nick-shaw** [colour-science/colour#792]
https://github.com/colour-science/colour/blob/6638055709a87162dd1a738bc8ec2101d99d75ad/colour/io/luts/sony_spimtx.py#L36

Looking at the [.spimtx parser in OCIO](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/9b23e9623792d8cc6e6c1dfd5394335ee148bcf3/src/OpenColorIO/fileformats/FileFormatSpiMtx.cpp#L134), it would appear that where a .spimtx file includes offsets, these should be treated as 16-bit integer scaled, not normalised float. Likewise the .spimtx writer should do the inverse. When writing the .spimtx parser, I had assumed incorrectly that the format used float offsets, the same as the matrix operator in CLF.

**Comment by KelSolaar** [comment]
This one was addressed a long time ago!
