### ISSUE TITLE
Forced use of "--user" is incompatible with editable install on Raspberry Pi 4.

### ISSUE THREAD

**Issue by baileyji** [colour-science/colour#805]
In trying to do an editable install to work round #663 on the RPi4 i discovered that the install scripts use of --user (which is not compatible with -e I believe) causes the install to fail.

> ➜  src pip3 install -e ./colour
> Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
> Obtaining file:///home/pi/src/colour
>   Installing build dependencies ... done
> Requirement already satisfied: imageio in /home/pi/.local/lib/python3.7/site-packages (from colour-science==0.3.16) (2.9.0)
> Requirement already satisfied: scipy<2.0.0,>=1.1.0 in /usr/lib/python3/dist-packages (from colour-science==0.3.16) (1.1.0)
> Requirement already satisfied: six in /usr/lib/python3/dist-packages (from colour-science==0.3.16) (1.12.0)
> Requirement already satisfied: numpy in /home/pi/.local/lib/python3.7/site-packages (from imageio->colour-science==0.3.16) (1.20.2)
> Requirement already satisfied: pillow in /usr/lib/python3/dist-packages (from imageio->colour-science==0.3.16) (5.4.1)
> Installing collected packages: colour-science
>   Running setup.py develop for colour-science
>     Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/home/pi/src/colour/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=:
>     usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>        or: -c --help [cmd1 cmd2 ...]
>        or: -c --help-commands
>        or: -c cmd --help
>     
>     error: option --user not recognized

**Comment by KelSolaar** [comment]
Hi @baileyji,

I'm not sure to understand when or where this happens, how are you triggering the installation? Do you have more log details?

Cheers,

Thomas

**Comment by baileyji** [comment]
This arose when I was using a git clone to make the edits to patch the numpy128 bug and tried to do an editable install. 

cd ~/src
git clone https://github.com/colour-science/colour.git
conda activate py37play
pip install -e ~/src/colour

**Comment by baileyji** [comment]
Note that this was not on an Rpi4. While I'm looking at using the library there I was playing around on os x 10.15.7. I think I recall something about --user, -e, pip and possibly conda being an inherently incompatible mix. Generally --user isn't used with a user conda environment in my experience.

**Comment by KelSolaar** [comment]
We should be handling `float128` much more gracefully in `develop` now, closing this one!
