### ISSUE TITLE
Example in "colour.contrast.contrast_sensitivity_function_Barten1999" definition docstring contains an error.

### ISSUE THREAD

**Issue by RutNij** [colour-science/colour#806]
L.S.,

in relation to function 'contrast_sensitivity_function_Barten1999'

the line containing the following:
'return as_float(np.array(maximised_spatial_frequency))' in function 'def maximise_spatial_frequency(L):'
**is indented 1 too many to the right**.

Though the example is executing, it outputs the incorrect values.
The given output data of this example corresponds to these incorrect values. So these need to be updated as well.

Note that this function will give the Barten 'flat' curve. (and not the Barten 'ramp' curve.)

Thanks,
Rutger

https://colour.readthedocs.io/en/v0.3.16_a/generated/colour.contrast.contrast_sensitivity_function_Barten1999.html#colour.contrast.contrast_sensitivity_function_Barten1999

see example code at bottom of page

**Comment by KelSolaar** [comment]
Hi @RutNij,

Really good catch! The example in the docstrings is taken from the actual example here: https://github.com/colour-science/colour/blob/4e2abd6c6b812f76184d208dec5a0d23b55c5213/colour/examples/contrast/examples_contrast.py#L45

Under the assumption it was working, I never really checked that the numbers in the docstrings were correct.
