### ISSUE TITLE
Add TE-226 reference values.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#901]
References
---
- https://www.image-engineering.de/content/products/charts/te226/downloads/TE226_D_data_sheet.pdf

**Comment by Alt-Shivam** [comment]
Hey @KelSolaar sir 
How to get started with this issue?
Can you help me out. :)

**Comment by Alt-Shivam** [comment]
Hey @KelSolaar sir 
How to get started with this issue?
Can you help me out. :)

**Comment by Rusching** [comment]
Hi @KelSolaar I'd like to work on this issue, can you please give me more information on how to start it?

**Comment by KelSolaar** [comment]
Hi @Rusching,

We would want to add the original CIE XYZ tristimulus values along with their converted CIE xyY counterpart in this module and expose it wherever relevant like the other color checkers: https://github.com/colour-science/colour/blob/develop/colour/characterisation/datasets/colour_checkers/chromaticity_coordinates.py

`CCS_TE226_V2` is appropriate for a final name!

Cheers,

Thomas

**Comment by Rusching** [comment]
Actually, TE226 has 45 colors while previous color checkers only contains 24. So should I add all these 45 colors?

**Comment by Rusching** [comment]
Hope my operation process is correct, this is my first time to propose a formal PR ^^

**Comment by KelSolaar** [comment]
Thank you!
