### ISSUE TITLE
"colour.convert" definition should memoize or provide access to the computed conversion function directly for more efficient reuse.

### ISSUE THREAD

**Issue by KrisKennaway** [colour-science/colour#905]
colour.convert is very useful especially for conversions that would require a number of intermediate steps (e.g. RGB --> CAM16UCS).  But if I need to make such a conversion multiple times (e.g. inside a program loop) then it dynamically reconstructs the path every time, which presumably has overhead (though admittedly I've not measured it)

Ideally convert() would either memoize the conversion between argument pairs, or a helper function could return the composed conversion function that can be reused directly.

**Comment by KelSolaar** [comment]
Hi @KrisKennaway,

I would honestly be surprised if finding the shortest path is noticeable,  especially compared to performing the colour transformations. It would be trivial to memoize though if required. Providing a composed function would be a bit harder though.

Cheers,

Thomas

Cheers,

Thomas

**Comment by KrisKennaway** [comment]
Thanks Thomas, I really should have benchmarked this before opening the issue.  Having done so I agree that this is not worth optimizing.  Thanks for taking the time to reply!
