### ISSUE TITLE
Possible docstring error in "zcam.py" module.

### ISSUE THREAD

**Issue by nick-shaw** [colour-science/colour#908]
https://github.com/colour-science/colour/blob/20c698729688cc999426f7c421d994d789cccd34/colour/appearance/zcam.py#L344
I think this is probably meant to be `*` rather than the letter `x`, so it should be:
```
:math:`Y_b = 100 * L_b / L_w`
```

**Comment by gajendra0180** [comment]
Hey! I would like to fix this error if nobody has yet started working on it.
Thanks.

**Comment by KelSolaar** [comment]
Thanks @nick-shaw! @gajendra0180: Sure thing!
