### ISSUE TITLE
Spelling errors in "zcam.py" module docstrings.

### ISSUE THREAD

**Issue by nick-shaw** [colour-science/colour#909]
https://github.com/colour-science/colour/blob/20c698729688cc999426f7c421d994d789cccd34/colour/appearance/zcam.py#L369
Should read "symmetrical" and "adaptation".

**Comment by gajendra0180** [comment]
Hey! I would like to fix this typo if nobody has yet started working on it.
Thanks.

**Comment by KelSolaar** [comment]
References #908.

@nick-shaw : Thanks again! @gajendra0180: Likewise, feel free to fix if you want.
