### ISSUE TITLE
colour.convert alters user-set domain range scale

### ISSUE THREAD

**Issue by daviesj** [colour-science/colour#913]
Using Python 3.8.1 (64-bit) on Windows, Using colour module version 0.3.16.

It seems that the conversion graph function colour.convert() (which is super cool, by the way) changes the domain range scale to 'reference' if the user set it to '1' beforehand. This is an unexpected side-effect and seems to go against the documentation which says more than once that the domain range scale for the function itself is '1' (such as [here](https://github.com/colour-science/colour/blob/fb92a8af34f6a1de95278e826978fc79450a45f3/colour/graph/conversion.py#L926) and [here](https://github.com/colour-science/colour/blob/fb92a8af34f6a1de95278e826978fc79450a45f3/colour/graph/conversion.py#L1031)).

Expected behavior:
```
>>> colour.set_domain_range_scale('1')
>>> colour.get_domain_range_scale()
'1'
>>> colour.convert([.5,.5,.5], 'RGB', 'CMYK')
array([ 0. ,  0. ,  0. ,  0.5])
>>> colour.get_domain_range_scale()
'1'
```

Observed behavior:
```
>>> colour.set_domain_range_scale('1')
>>> colour.get_domain_range_scale()
'1'
>>> colour.convert([.5,.5,.5], 'RGB', 'CMYK')
array([ 0. ,  0. ,  0. ,  0.5])
>>> colour.get_domain_range_scale()
'reference'
```

This does not happen when manually executing the individual conversion functions:
```
>>> colour.set_domain_range_scale('1')
>>> colour.get_domain_range_scale()
'1'
>>> cmy = colour.RGB_to_CMY([.5, .5, .5])
>>> colour.get_domain_range_scale()
'1'
>>> colour.CMY_to_CMYK(cmy)
array([ 0. ,  0. ,  0. ,  0.5])
>>> colour.get_domain_range_scale()
'1'
```

**Comment by KelSolaar** [comment]
Hi @daviesj,

This should have been fixed in develop by https://github.com/colour-science/colour/commit/17dd6dd60311e83dfee53e8f277ce45fd083cf22 and was reported in #838.

Cheers,

Thomas

**Comment by daviesj** [comment]
Seems so. I tried searching but I guess I must not have included closed issues. Thanks.
