### ISSUE TITLE
The "colour.CAM16*_to_XYZ" definitions do no call the correct underlying "colour.models.cam16_ucs.UCS_Li2017_to_XYZ" definition.

### ISSUE THREAD

**Issue by wuuawu** [colour-science/colour#914]
In the `cam16_ucs.py`, the `CAM16UCS_to_XYZ` function call `XYZ_to_UCS_Li2017` instead of `UCS_Li2017_to_XYZ`. The same problem occurs in `CAM16SCD_to_XYZ` and` CAM16LCD_to_XYZ`.

**Comment by KelSolaar** [comment]
Hi @wuuawu,

Thanks for the report, it is unfortunate that a place where the code is not tested because it was deemed not necessary is broken!

For reference for the conversation:

```python
XYZ_to_CAM16LCD = partial(
    XYZ_to_UCS_Li2017, coefficients=COEFFICIENTS_UCS_LUO2006['CAM02-LCD'])
XYZ_to_CAM16LCD.__doc__ = (
    _UCS_Luo2006_callable_to_UCS_Li2017_docstring(XYZ_to_CAM02LCD))

CAM16LCD_to_XYZ = partial(
    XYZ_to_UCS_Li2017, coefficients=COEFFICIENTS_UCS_LUO2006['CAM02-LCD'])
CAM16LCD_to_XYZ.__doc__ = (
    _UCS_Luo2006_callable_to_UCS_Li2017_docstring(CAM02LCD_to_XYZ))
```
