### ISSUE TITLE
Implement support for Rayleigh-Jeans spectral distribution.

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#919]
References
---
- https://colab.research.google.com/drive/1Oyn913zkXYB8Uf8k1hiM8_5gifuMVqta?usp=sharing

**Comment by Alt-Shivam** [comment]
Hey @KelSolaar 
I just visited your given reference.
But Still, I am slightly confused.
Can you please help me to get started with this issue.
Thanks

**Comment by Alt-Shivam** [comment]
I want to work on this.

**Comment by KelSolaar** [comment]
Hi @Alt-Shivam,

The idea is to implement the Rayleigh-Jeans function and the corresponding spectral distribution like it is done in the `colour.colorimetry.blackbody` module.

Cheers,

Thomas

**Comment by Alt-Shivam** [comment]
Thanks @KelSolaar 
I have started working on it.
Is there any method to contact you?
anything like slack :)

**Comment by Alt-Shivam** [comment]
Thanks a lot, @KelSolaar sir for the guidance 

*Update* 
*Status* - Feedback Appreciated i.e Still under development
Example is yet to be added

here is the result sir
[File](https://github.com/Alt-Shivam/colour/blob/develop/colour/colorimetry/Rayleigh-Jeans-spectral-distribution.py)

**Comment by KelSolaar** [comment]
Hi @Alt-Shivam,

Because this function models a blackbody, we should probably put it in the `colour.colorimetry.blackbody` module.

**Comment by Alt-Shivam** [comment]
Sure sir
I will do that. :)

**Comment by Alt-Shivam** [comment]
Hey @KelSolaar sir 
I have created a PR for this issue 
have a look. :)

also, I left the Reference section empty for now.
