### ISSUE TITLE
[FEATURE]: Support alternative norms for LUT1D etc?

### ISSUE THREAD

**Issue by sobotka** [colour-science/colour#936]
### Description

Would it be feasible to support an additional parameter that specifies how a norm should be handled? Perhaps a function passed to the `apply` function?

**Comment by KelSolaar** [comment]
Hi @sobotka,

Trying to clarify, were you thinking that `LUT1D.apply` should work on `max(RGB)` for example instead of being applied per-channel.

Cheers,

Thomas

**Comment by sobotka** [comment]
Exactly. With the option for more sophisticated functions perhaps?

Not entirely sure the sanest way to approach it, but perhaps something akin to the `interpolator` approach could work?

**Comment by KelSolaar** [comment]
Seems like this type of functionality could live outside the `apply` method, i.e. you could produce the data according to the _norm_ of your liking and apply the LUT on that? That said, we could certainly write some examples / How-To showing how to do that.

**Comment by KelSolaar** [comment]
Closing this one for now as this can be done easily indirectly.
