### ISSUE TITLE
[BUG]: API Documentations Broken with Latest & 0.3.16

### ISSUE THREAD

**Issue by fredsavoir** [colour-science/colour#953]
### Description

Hi,
On the web page: API Reference all link from 0.3.16 til latest are broken.
They are displaying : 
       \    SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet.

Anyone else ?

**Comment by KelSolaar** [comment]
Hi @fredsavoir,

I tested all the links and they are fine! I noted that v0.3.16 and v0.3.10 are missing though.

Cheers,

Thomas

**Comment by fredsavoir** [comment]
Hi,

Thanks. But here under safari or Firefox :
https://colour.readthedocs.io/en/latest/manual.html <https://colour.readthedocs.io/en/latest/manual.html>

= SORRY this page does not exist yet.

:(

**Comment by fredsavoir** [comment]
Hi,

OK The issue is

Up to 0.3.15 no need to be a log-in user to reathedocs.

From 0.3.16 link you need to have a log-in access the pages :)

So I guess it’s the difference between I can’t access it.

Could you confirm ?

Thanks for your support,

Fred

**Comment by KelSolaar** [comment]
On Safari / Not Logged In

**Develop**
![image](https://user-images.githubusercontent.com/99779/156309754-e21b4da2-8422-402b-b9f4-9ca19d4b65dc.png)

**v0.4.1**
![image](https://user-images.githubusercontent.com/99779/156309891-e4e778aa-a7ce-4462-919d-dcbc5efc9ae5.png)

**v0.3.15**
![image](https://user-images.githubusercontent.com/99779/156310012-ac44141b-fd00-4284-b32c-660e740cd88d.png)

There is no v0.3.16 nor v0.3.10 version.

Cheers,

Thomas

**Comment by KelSolaar** [comment]
The v0.3.16 version was reinstated.
