### ISSUE TITLE
Parameter standalone=False not working in Function plot_multi_colour_checkers

### ISSUE THREAD

**Issue by kljumat** [colour-science/colour#968]
### Description

colour.plotting.plot_single_colour_checker function does not respect render parameter standalone. It doesn’t matter if set to False or True, ColorChecker is always plotted immediately.

colour.plotting.plot_single_colour_checker( 'babel_average', standalone=False )
plt.show()

The same way also works function plot_multi_colour_checkers which indeed does the job also for plot_single_colour_checker.

To add support for parameter standalone, code in function plot_multi_colour_checkers should be changed in a way that input state of parameter be transferred to the end and not statically changed to True at the end of function in this part of code:

settings.update(
        {
            "axes": axes,
            "standalone": True,
            "title": ", ".join(colour_checker_names),
        }
    )

### Code for Reproduction

```python
colour.plotting.plot_single_colour_checker( 'babel_average', standalone=False )
plt.show()
```

**Comment by KelSolaar** [comment]
Thanks and good catch @kljumat, this should be fixed! I forgot to add the update statement.
