### ISSUE TITLE
[BUG]: Fix "DeprecationWarning" issued with usage of "convolve1d" from the "scipy.ndimage.filters" namespace.

### ISSUE THREAD

**Issue by andurilhuang** [colour-science/colour#973]
https://github.com/colour-science/colour/blob/bbaea60e9c6cda5fdc81f401da213237d075257e/colour/quality/ssi.py#L19

DeprecationWarning: Please use convolve1d from the scipy.ndimage namespace, the scipy.ndimage.filters namespace is deprecated

**Comment by KelSolaar** [comment]
Thanks @andurilhuang, should be fixed soon! It is worth noting that the minimum Scipy version we support [as per Scientific Python](https://scientific-python.org/specs/spec-0000/), i.e. 1.5, does not exhibit this warning, neither 1.6 nor 1.7 afaik.
