### ISSUE TITLE
[BUG]: BT.2020 OETF is incorrectly labeled as EOTF

### ISSUE THREAD

**Issue by fxthomas** [colour-science/colour#983]
### Description

As far as I can tell, [ITU-R BT.2020](https://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.2020-2-201510-I!!PDF-E.pdf) only defines an OETF (ITU-R BT.1886 is noted as a possible reference EOTF in the footnotes).

Specifically, the recommendation defines `E' = OETF(E)`, where E is said to be "proportional to the implicit light intensity", corresponding to the "opto" part of the OETF, and "E’ is the resulting non-linear signal", corresponding to the "electro" part of the OETF.

However, colour-science label the following two functions with "EOTF":

* `colour.models.eotf_inverse_BT2020` (should be `oetf_BT2020`, corresponds to what's described in the recommendation)
* `colour.models.eotf_BT2020` (should be `oetf_inverse_BT2020`,  corresponds to the mathematical inverse of the OETF described in the recommendation)

**Comment by KelSolaar** [comment]
Hi @fxthomas,

Thank you, I tried to understand why we renamed it in this commit but could not: https://github.com/colour-science/colour/commit/7849001cbd2891105202419c797e341ec7a278fb

Cheers,

Thomas

**Comment by fxthomas** [comment]
Nice, thanks for the quick fix!

ITU-R BT.2020 does not explicitly mention the term "OETF" near its definition and leaves that understanding to the reader, that was probably the cause for the initial mixup when trying to clarify things.

**Comment by KelSolaar** [comment]
I think I simply changed the wrong one by mistake at the time.

**Comment by ValZapod** [comment]
> Nice, thanks for the quick fix!
> 
> ITU-R BT.2020 does not explicitly mention the term "OETF" near its definition and leaves that understanding to the reader, that was probably the cause for the initial mixup when trying to clarify things.

BT.2020 transfer is very same as BT.709 transfer for 10 bit and slightly higher precision for 12 bit... And BT.709 was only OETF, since EOTF was compensating for dark room. So BT.1886 was done later, much later. BT.2020 is just SDR, because HDR means a new transfer function PQ or HLG.

**Comment by ValZapod** [comment]
> Hi @fxthomas,
> 
> Thank you, I tried to understand why we renamed it in this commit but could not: [7849001](https://github.com/colour-science/colour/commit/7849001cbd2891105202419c797e341ec7a278fb)
> 
> Cheers,
> 
> Thomas

Change of primaries must happen on scene linear light that is produced using inverse OETF. Only after again applying OETF you can apply EOTF, 2.4 gamma for OLED in dark room of BT.1886.
