### ISSUE TITLE
[FEATURE]: Implement support for "slugified" colourspace names.

### ISSUE THREAD

**Issue by MrLixm** [colour-science/colour#991]
### Description

Hello,

I'm looking to insert or retrieve `colour.RGB_COLORSPACES` names from file names. 
For example, I would like to use the `ALEXA Wide Gamut` colorspace into a file name which could be slugified to something like `alexaWideGamut`. I could also run the invert where something like `colour.RGB_COLORSPACES.get("alexaWideGamut")` would return me the `ALEXA Wide Gamut` `RGB_COLORSPACE` instance.

This means colour could be an alternative method (to OCIO) to convert imagery files colorspaces, where file name / metadata would provide the source colorspace name of the file. 
I'm trying to answer the question *How one would encode colorspace metadata in a library of imagery files that would be easily translated to a code object for conversions.*
OCIO is one way to go but I would like to see how colour would behave in that role.

Some technicalities to have a look at:
- what characters are allowed ? Do we keep dots, dashes ? Or only something like `[a-zA-Z\d_]`
- does we modify literature of colorspace names, like `sRGB` would become `srgb` ?

Cheers.
Liam.

**Comment by KelSolaar** [comment]
Here is a quick notebook to illustrate what we could do for example: https://colab.research.google.com/drive/1xlhqI0W71g7uX4HQ9pUiV13HqRsxWmny#scrollTo=2lbGErCPHmjM

The main question is whether we want to support that by default or provide a way for people to implement that easily.

Given that we use `CaseInsensitiveMapping/LazyCaseInsensitiveMapping` in a lot of places, we could maybe implement that across the board. We would have to choose a default style that is not ambiguous, e.g. separated with dashes:

`ALEXA Wide Gamut` --> `alexa-wide-gamut`

It would be trivial to write *camelCase*, *PascalCase*, *snake_case* mappings from there.

**Comment by MrLixm** [comment]
Thanks ! This looks great.
How should it treat dots like in `Venice S-Gamut3.Cine` that with your current function is turned into `venice-s-gamut3cine`. Would it be preferable to turn the dot into a dash ?

Having it implemented straight into `CaseInsensitiveMapping/LazyCaseInsensitiveMapping` seems to be a great idea, I hope it will not cause you collision issues or something in that regards.

**Comment by fredsavoir** [comment]
Yes very cool

**Comment by KelSolaar** [comment]
We cannot change `.keys` like that, it would break everything down the lines, it would be either we extend `.keys` with the *slugified* variants, or we have a `.slugs` method (probably cleaner) that returns them.

**Comment by MrLixm** [comment]
What about 
- `.keys` : combinaison of all the three other method under. Compared to actual it's the same but with the slugs.
- `.names` : original colorspace names
- `.slugs`: return slugs only
- `.aliases`: return aliases only like `aces, adobe1988, ...`
