### ISSUE TITLE
[FEATURE]: Implement support for "ARRI Wide Gamut 4" and "ARRI LogC4".

### ISSUE THREAD

**Issue by KelSolaar** [colour-science/colour#992]
### Description

References
--- 
- https://www.arri.com/resource/blob/278790/bea879ac0d041a925bed27a096ab3ec2/2022-05-arri-logc4-specification-data.pdf
- https://github.com/ampas/aces-dev/pull/131

@JGoldstone for VIS!

**Comment by JGoldstone** [comment]
It might be good to wait until some issues raised by Doug for the aces-dev stuff get worked out, e.g. I would like to exactly match the precision of any constants that appear in equations. Given the motivation — supporting a camera only weeks away from FCS — I do not thing those issues will linger. When they are resolved, then I would like to move forward with my contribution being a PR.

**Comment by KelSolaar** [comment]
Hi @JGoldstone,

Any news on this one?

Cheers,

Thomas
